### ISSUE TITLE
Saving Live Stream Packets as Video

### ISSUE THREAD

**Issue by juanjose49** [dgreif/ring#101]
Can somebody please describe a process for converting the live stream to a file that is readable by a video player? This seems like it would be a very common use case but doesn't appear to be described anywhere.

**Comment by dgreif** [comment]
@juanjose49 I think what you are looking for is currently being worked on in https://github.com/bourdakos1/ring-streamer.  @bourdakos1 helped me refactor some of the SIP code to make it work with his setup.  I suggest you take a look at his repo to see if it fits your needs.

The other option is to use `camera.getRecording(dingIdStr)` method, which will give you back a url to the recording associated with a specific ding.  Please note, the `dingIdStr` _must_ be the `id_str` field from active dings, or `ding_id_str` from `location.getEvents()`.  Using the `id` field from active/historical dings won't work because it is a rounded number.

**Comment by juanjose49** [comment]
Recordings hosted by Ring ultimately require a membership (right?). My goal is to start a live stream, create a video, and host the videos myself. It's probably more work to achieve this goal than it would cost for the service, but hey, I'm a tinkerer.

**Comment by juanjose49** [comment]
@dgreif I created this PR to address my enhancement request above. Thank you for referring me to @bourdakos1's repository. It was exactly what I needed!
