### ISSUE TITLE
Using Home/Away modes in Homebridge 'resets' Modes feature in Ring app

### ISSUE THREAD

**Issue by t829913** [dgreif/ring#1012]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
After triggering a mode (etc Away) via the Home app, if I then go into the Ring app, the “modes” options normally available at the top of the main dashboard screen have disappeared, and the app acts as though the feature has not even been enabled before. If I select to enable them, the motion / live view options for each camera per Mode have been reset to the defaults.
### To Reproduce
- In your Ring environment, enable the 'Modes' feature for cameras
- Change the Home / Away / Disarmed behaviours for some devices away from the defaults
- Pair to Homebridge plugin
- Start Homebridge
- In the Home app, set the mode to Away and wait a few seconds
- Return to the Ring app. Notice the Home / Away / Disarmed Modes options are now missing from the Dashboard view.
- In the Ring app, go to Settings > Modes. Notice the screen asks "Ready to start using Modes?" as though the features has been disabled until now. Selecting either "Use Default Mode Settings" or "Customise Mode Settings" results in modes settings being reset to their defaults.

### Expected behavior
 A clear and concise description of what you expected to happen.
'Modes' functionality should continue as always with the Ring app only reflecting any change in state due to changes made via the Homebridge plugin.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
  {
            "refreshToken": xxx,
            "hideDoorbellSwitch": true,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "avoidSnapshotBatteryDrain": true,
            "onlyDeviceTypes": [
                "location.mode",
                "stickup_cam_mini"
            ],
            "platform": "Ring"
        },


```

### Environment

 - OS: Raspbian
 - Node.js: 16.16.0
 - NPM: 8.11.0
 - homebridge-ring: 11.0.7
 - homebridge: 1.5.0
 - hoobs: N/A

**Comment by dgreif** [comment]
@t829913 I really appreciate the detailed report! I normally don't have my cameras set up with basic Modes since I have a Ring alarm, but I jumped through the hoops to move a camera to a test account to recreate this. Unfortunately I was unable to reproduce. If I switch modes via homebridge, they properly update and _do not_ clear any settings. I also combed through the code and verified we are setting the mode using the exact same api call as the Ring web app, so it shouldn't be causing different behavior. It might be worth checking for updates to the Ring app and homebridge plugin. Please give it another try and let me know if you are still experiencing this issue.
