### ISSUE TITLE
is offline or on cellular backup.  Waiting for status to change

### ISSUE THREAD

**Issue by scottclift** [dgreif/ring#1063]
# Bug Report

### Describe the Bug
is offline or on cellular backup.  Waiting for status to change.
Have already reset the hoobs box & the network
Have already checked older version of the plugin 9.24.0 (same issue)
Have already checked that all cameras are on network and does not have access to celluar
Have already ensured that hoobs box is fully upto date as well as have reset the hoobs network settings, hoobs remote support ensured that everything is running correctly with hoobs box (other plugins are working without issue)
Have uninstalled and reinstalled trying differnt versions
Have went to my ring control center and do not see the authorized client device for homebridge-ring for the new plugin (on new and old versions of ring plugin)
Have already tried "unbridgeCameras": true

### To Reproduce
Install ring plugin, sign in, put in 2fa, wait for bridge to load, check logs as cameras do not load

### Expected behavior
 A clear and concise description of what you expected to happen.
Expected cameras to show

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.
9/30/2022, 11:15:39 AMRing BridgeRingERRORRing beams_bridge_v1 0b7db197-339e-438e-5f8d-86a4e24a2a20 is offline or on cellular backup.  Waiting for status to change

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

{
    "platform": "Ring",
    "refreshToken": "xxx"
}

```

### Environment

 - OS: [hoobs HSLF-1 V4.2.8]
 - Node.js: 16.17.1
  - homebridge-ring: 11.2.1
 - homebridge: 1.5.0
 - hoobs: 4.2.8

**Comment by dgreif** [comment]
`is offline or on cellular backup` indicates that your Ring Alarm or Ring Lighting Bridge is not currently connected to wifi. In this scenario, the list of devices cannot be retrieved from Ring (this is a limitation on Rings end). You need to reconnect your device to wifi, and then homebridge-ring will be able to fetch the device list and proceed.

**Comment by jmporter34** [comment]
@dgreif I'm seeing the same issue when Homebridge starts: "Ring beams_bridge_v1 a11a19bd-1afa-43d1-4d3e-65bd8128e957 is offline or on cellular backup.  Waiting for status to change".  

I'm sure that my Ring bridge is connected (with Ethernet rather than WiFi) because the Ring iOS app says so and I can see all my sensor status there, also I can log in to the Ring website and see everything online there as well.

What I am trying to do is create a new Homebridge image on a second Raspberry Pi, installing everything including your plug-in from scratch and making sure that I see everything as expected before turning off and re-imaging the first Raspberry Pi running Homebridge (where everything is working as expected - except that I keep seeing old names for some of my Ring devices there, after renaming them in the Ring app, checking that they appear as I want on the Ring website, restarting Homebridge, etc. etc.  This is something that I asked you about a while ago, and the only solution was to wipe Homebridge and start over, which I did and the device names all appeared as expected at the time.  Now I've renamed a bunch more Ring devices and keep seeing the old names.  Rather than wipe my only running Homebridge image and start over, I decided to create a second Homebridge image on a second Pi and make sure everything is working before retiring and re-imaging the first one.  But the second one gets the "offline or cellular backup" message.

My point in writing this novel (sorry) is that the Ring bridge being offline is not the only possible cause for the error message described by @scottclift - it's probably (in my case) something to do with Ring not allowing two instances of your plug-in running on different machines to simultaneously access my Ring data.

That's my best guess - I'm open to being corrected though if I'm wrong :-)
Thanks

**Comment by jmporter34** [comment]
@dgreif I was seeing the same issue when Homebridge starts: "Ring beams_bridge_v1 a11a19bd-1afa-43d1-4d3e-65bd8128e957 is offline or on cellular backup. Waiting for status to change".

The diagnosis that you provided to @scottclift was correct.  I have both a Ring Alarm and Ring Lighting bridge.  The Ring Alarm was connected (via Ethernet) but the Ring Lighting bridge was not connected.  I removed the Lighting bridge from my Ring account temporarily and now your plugin starts normally and the devices are shown on the Accessories page.

Thanks, and sorry to trouble you with my previous long-winded post, deleting it now.
