### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'subscribe')

### ISSUE THREAD

**Issue by Macksly** [dgreif/ring#1114]
I am trying to run te example project and when I run it I get the following error:

/Users/maxpeters/Documents/ring/example.js:70
      camera.onNewDing.subscribe((ding) => {
                       ^

TypeError: Cannot read properties of undefined (reading 'subscribe')
    at /Users/maxpeters/Documents/ring/example.js:70:24
    at Array.forEach (<anonymous>)
    at example (/Users/maxpeters/Documents/ring/example.js:69:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5

onMotionEvent is working however onNewDing not.. could someone help me

**Comment by tsightler** [comment]
What example are you attempting?  onNewDing doesn't exist since the switch to push notifications, it should be onNewNotification.  See https://github.com/dgreif/ring/blob/main/packages/examples/example.ts

**Comment by dgreif** [comment]
I believe they were referring to the separate [example project](https://github.com/dgreif/ring-client-example). It had both JS and TS examples, but the JS one fell behind (because it didn't have types to tell me something was broken 😂). I've decided to e5a9a55d695949cd5a673a4b8f10d05a51018455, as using TypeScript is a far better option. @Macksly you can run the TS example with `npm start`
