### ISSUE TITLE
No Camera Snapshot Update

### ISSUE THREAD

**Issue by MoTechnicalities** [dgreif/ring#1124]
# Bug Report

### Describe the Bug
 Snapshots don't update. I I have several Ring and Other cameras. Only the Ring don't update.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 ![image](https://user-images.githubusercontent.com/68468472/208258421-128f5392-93e6-4c1b-8863-b774710d8a44.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by Kaiserben** [comment]
Same issue as described here : https://github.com/dgreif/ring/issues/1118#issuecomment-1356138005

**Comment by databoy01** [comment]
Having a similar issue, but basically i cannot see any cameras at all anymore…. After I upgraded to 16.2 the HomeKit app shows cameras not found. 

Says “Ring beams bridge v1 xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx is offline or on cellular backup. Waiting for status to change” (I removed the actual numbers with X’s) as not sure if they are important numbers that distinguish my service.  I tried to reset my HomeKit, deleted it from the Home app and reinstalled the plug-in and added it again to my home.  Needless to say the Ring beams offline doesn’t change. 

Help would be appreciated.  Thanks

**Comment by jchristianj** [comment]
Hi, I am having the same issue. Camera live streaming is working fine in home.app, but none of the cams is updating the thumbnail. Before iOS16.2 it did update after 10s (being in home wifi). Now it does not update at all, and rich notifications is not working, too (notification comes in, but shows no image).

**Comment by databoy01** [comment]
And just like that, all of the sudden it starts working again for no known reason…. I havent done anything since yesterdays reflash and reset that originally didnt work.

**Comment by Kaiserben** [comment]
> And just like that, all of the sudden it starts working again for no known reason…. I havent done anything since yesterdays reflash and reset that originally didnt work.

Are the snapshots working and per se rich notification? Or only the video feed?

**Comment by Kaiserben** [comment]
I dig a bit and I believe there is an issue with Ring API itself, not with Homedridge nor the home bridge-ring plugin.

I used the work there : https://github.com/tchellomello/python-ring-doorbell/issues/124#issuecomment-506542756 to try to get a snapshot directly from RING API with a GET on the URL `https://api.ring.com/clients_api/snapshots/image/xxxxxx` --> The response was : `no snapshot`

**Comment by databoy01** [comment]
> > And just like that, all of the sudden it starts working again for no known reason…. I havent done anything since yesterdays reflash and reset that originally didnt work.
> 
> Are the snapshots working and per se rich notification too? Or only the video feed?

Both for me.  The snapshot does take a few seconds, but it does work.

**Comment by Kaiserben** [comment]
Weird.

One of the thing worth noting is that I completely reinstalled my raspbian setup after the memory card crashed some days ago. I went trough the new procedure to do so : https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian which is totally different from what is used to be.

Maybe there is a side effect of this new way homebridge is running. 

I even tried the full reinstall again of homebridge and ring plugin again, still snapshots failing to save.

I arrived to the end of my basic skills and will wait patiently until @dgreif have some free time to help :)

**Comment by jchristianj** [comment]
> I arrived to the end of my basic skills and will wait patiently until @dgreif have some free time to help :) I've updated my first post with all the elements [#1124 (comment)](https://github.com/dgreif/ring/issues/1124#issuecomment-1356723339).

Will not put too much hope in this, I assume it is not related to the plugin.
I've had the issue of non-refreshing thumbnails during the complete iOS14 lifecycle, and it was solved with iOS15.1 (as far as I can remember, maybe it was 15.2). Under iOS16.0 is was still working, but after migrating my home to the new architecture introduced in 16.2 it is failing again. I feel it is an iOS issue.

**Comment by Kaiserben** [comment]
> > I arrived to the end of my basic skills and will wait patiently until @dgreif have some free time to help :) I've updated my first post with all the elements [#1124 (comment)](https://github.com/dgreif/ring/issues/1124#issuecomment-1356723339).
> 
> Will not put too much hope in this, I assume it is not related to the plugin. I've had the issue of non-refreshing thumbnails during the complete iOS14 lifecycle, and it was solved with iOS15.1 (as far as I can remember, maybe it was 15.2). Under iOS16.0 is was still working, but after migrating my home to the new architecture introduced in 16.2 it is failing again. I feel it is an iOS issue.

What do you have in your logs? Same message: `Failed to cache snapshot for Portail ` ? From what I understand is that it seems the plugin is not able to get it from Ring server so it should not be iOS related.

**Comment by jchristianj** [comment]
Yes, it appears in my log as well:

[12/21/2022, 12:26:30 PM] [homebridge-ring] iceConnectionStateChange: connected
[12/21/2022, 12:26:31 PM] [homebridge-ring] Failed to cache snapshot for Haustür (15.019s), The camera currently reports that it is online
[12/21/2022, 12:26:31 PM] [homebridge-ring] Snapshot for Haustür (lpd_v4 - Doorbell Pro 2) failed to refresh after 15 seconds
[12/21/2022, 12:26:31 PM] [homebridge-ring] Failed to cache snapshot for Ring (15.065s), The camera currently reports that it is online
[12/21/2022, 12:26:31 PM] [homebridge-ring] Snapshot for Ring (cocoa_doorbell - Doorbell Gen 2) failed to refresh after 15 seconds.  This is normal behavior since this camera is unable to capture snapshots while streaming

Ok, so let's see if it can be fixed.

**Comment by databoy01** [comment]
> > I arrived to the end of my basic skills and will wait patiently until @dgreif have some free time to help :) I've updated my first post with all the elements [#1124 (comment)](https://github.com/dgreif/ring/issues/1124#issuecomment-1356723339).
> 
> Will not put too much hope in this, I assume it is not related to the plugin. I've had the issue of non-refreshing thumbnails during the complete iOS14 lifecycle, and it was solved with iOS15.1 (as far as I can remember, maybe it was 15.2). Under iOS16.0 is was still working, but after migrating my home to the new architecture introduced in 16.2 it is failing again. I feel it is an iOS issue.

Question for you, after I upgraded to 16.2 on my phone and Apple TV. I upgraded my HomePod, through the Home App on my iPad, it gave me a warning asking if I wanted to upgrade to the newest release of HomeKit (I’m thinking the matter support). I of course said yes because I knew that was the main reason for 16.2. Have you seen that screen and also say yes to it?  It also said once you upgrade you wouldn’t be able to downgrade to whatever it was before. 

To get to that screen, under the home app, the three dots has a spot that then opens to a settings area, under software updates (where I can update the HomePod), is where I saw it. Hope this helps. It’s also where after I said ok, a day later my ring plugin stopped working..

**Comment by databoy01** [comment]
Plus I found this article about someone that saw a similar warning. Maybe this will help you too. 

https://discussions.apple.com/thread/254473562

and this

https://forums.macrumors.com/threads/after-16-2-any-one-have-luck-upgrading-the-architecture.2373452/

**Comment by jchristianj** [comment]
@databoy01 Yes, I did this home-upgrade: After bringing all my devices (iPhones, HomePod and ATV) to 16.2 I performed the home-upgrade successfully. Right after that my Ring snapshots froze forever.

**Comment by databoy01** [comment]
Hmm. Have you deleted the bridge and removed it from the home? Plus remove it from the Homebridge device?  Then reinstall it like new?  Because until I did that mine was broken. The only other difference between my setup before 16.2 and now is that I had my cameras set up as unbridged in the ring plugin and now I don’t. Originally that was a mistake I didn’t ‘fix’ but like I said after a day of still not working all of the sudden it did start working. Something between Ring and the matter support is screwing this up. On Dec 21, 2022, at 8:04 AM, jchristianj ***@***.***> wrote:﻿
@databoy01 Yes, I did this home-upgrade: After bringing all my devices (iPhones, HomePod and ATV) to 16.2 I performed the home-upgrade successfully. Right after that my Ring snapshots froze forever.

**Comment by MoTechnicalities** [comment]
It isn't likely be the new architecture. Or Homebridge itself needing to be uninstalled and reinstalled.

I also have a camera running from Homebridge under homebridge-camera-ffmpeg v3.1.4, and its snapshots update just fine every 10 seconds. While all the Ring shots just sit there.

**Comment by databoy01** [comment]
Well guess what, it broke again. All on its own…. So yeah definitely something with either ring or the plug-in…

**Comment by dgreif** [comment]
@Kaiserben thank you for posting logs, that's definitely helpful. `Failed to cache snapshot for Portail (15.002s)` indicates the plugin tried to fetch a snapshot, waited 15 seconds, then timed out. This could happen if Ring is unable to fetch a snapshot from the camera (because the camera isn't responding properly, possibly, which a power cycle should help with), or Ring is simply refusing to provide a snapshot (possibly because you are on a free account as you mentioned). One easy test would be to open the real Ring app and see if snapshots are able to load properly there. Could you give that a try?

@databoy01 @MoTechnicalities as far as I can tell, the 16.2 update shouldn't be impacting snapshots. As long as you are seeing snapshot requests attempted in the homebridge logs, that means homebridge is getting the proper communication from HomeKit. I _think_ I'm on the new framework, though I'm not sure there is a good way to tell, and my snapshots are working properly.

**Comment by jchristianj** [comment]
I am on the new home architecture (as I had all the common problems with invited users during migration) and I am on a Ring subscription plan, and snapshots within the Ring App are working. They appear within 20s after opening the Ring App.

There seem to be requests from Apple Home to the homebridge plugin, upon opening the home App and going into the room with the cam thumbnail the log shows:

[12/23/2022, 9:38:50 PM] [homebridge-ring] No snapshot cached for Haustür
[12/23/2022, 9:38:50 PM] [homebridge-ring] Loading new snapshot into cache for Haustür
[12/23/2022, 9:38:56 PM] [homebridge-ring] Failed to cache snapshot for Ring (15s), The camera currently reports that it is online
[12/23/2022, 9:38:56 PM] [homebridge-ring] Snapshot for Ring (cocoa_doorbell - Doorbell Gen 2) failed to refresh after 15 seconds.  This is normal behavior since this camera is unable to capture snapshots while streaming
[12/23/2022, 9:39:00 PM] [homebridge-ring] No snapshot cached for Haustür
[12/23/2022, 9:39:05 PM] [homebridge-ring] Failed to cache snapshot for Haustür (15.002s), The camera currently reports that it is online
[12/23/2022, 9:39:05 PM] [homebridge-ring] Snapshot for Haustür (lpd_v4 - Doorbell Pro 2) failed to refresh after 15 seconds
[12/23/2022, 9:39:21 PM] [homebridge-ring] No snapshot cached for Haustür
[12/23/2022, 9:39:21 PM] [homebridge-ring] Loading new snapshot into cache for Haustür
[12/23/2022, 9:39:36 PM] [homebridge-ring] Failed to cache snapshot for Haustür (15.002s), The camera currently reports that it is online
[12/23/2022, 9:39:36 PM] [homebridge-ring] Snapshot for Haustür (lpd_v4 - Doorbell Pro 2) failed to refresh after 15 seconds
[12/23/2022, 9:39:51 PM] [homebridge-ring] No snapshot cached for Haustür
[12/23/2022, 9:39:51 PM] [homebridge-ring] Loading new snapshot into cache for Haustür
[12/23/2022, 9:40:06 PM] [homebridge-ring] Failed to cache snapshot for Haustür (15.001s), The camera currently reports that it is online
[12/23/2022, 9:40:06 PM] [homebridge-ring] Snapshot for Haustür (lpd_v4 - Doorbell Pro 2) failed to refresh after 15 seconds

**Comment by dgreif** [comment]
I'm running some tests and it appears Ring may have changed some of the timing restrictions for battery cameras. It used to be that you could "force" a snapshot and it would respond in a reasonable timeframe (within a second or two). Now it can take up to 15 seconds to get a response, and that response is sometimes a `504 Gateway Timeout`, indicating Rings servers cut off the request. Unfortunately there isn't anything I can do on my end to improve this API, it's completely controlled by Ring. Snapshots have always been a pain point with the Ring plugin, which is why we have the [Snapshot Limitations Wiki](https://github.com/dgreif/ring/wiki/Snapshot-Limitations).

I welcome PRs if anyone is able to find something I missed, but I don't think there is anything to be done here. The plugin makes the most of the available API, but it has restrictions we simply can't get around when it comes to snapshots.

**Comment by jchristianj** [comment]
It is not a battery camera. In my case it's a hardwired Pro 2 model. And how about rich notifications? Is that issue related?

**Comment by dgreif** [comment]
@jchristianj thanks for clarifying

> They appear within 20s after opening the Ring App

The Ring API appears to time out after 15 seconds, so maybe the 20s is just too long? How is your upload/download speed? This seems like it might just be a limitation on your network, but it's hard to say for sure

**Comment by jchristianj** [comment]
@dgreif 
Checked with watch: after opening Ring App the snapshots are updated within 7-11 seconds for hardwired cam.

**Comment by Kaiserben** [comment]
> @Kaiserben thank you for posting logs, that's definitely helpful. `Failed to cache snapshot for Portail (15.002s)` indicates the plugin tried to fetch a snapshot, waited 15 seconds, then timed out. This could happen if Ring is unable to fetch a snapshot from the camera (because the camera isn't responding properly, possibly, which a power cycle should help with), or Ring is simply refusing to provide a snapshot (possibly because you are on a free account as you mentioned). One easy test would be to open the real Ring app and see if snapshots are able to load properly there. Could you give that a try?
> 
> @databoy01 @MoTechnicalities as far as I can tell, the 16.2 update shouldn't be impacting snapshots. As long as you are seeing snapshot requests attempted in the homebridge logs, that means homebridge is getting the proper communication from HomeKit. I _think_ I'm on the new framework, though I'm not sure there is a good way to tell, and my snapshots are working properly.

Many thanks for taking the time to help with this.

I've tried already to power cycle multiple times and it didn't solve a thing. The snapshots are refreshing properly on the Ring app automatically.

I've tried to query directly the Ring API with NodeRed :

- `https://app-snaps.ring.com/snapshots/next/_deviceID_` --> I'm getting a snapshot 100% of the time
- `https://api.ring.com/clients_api/snapshots/image/_deviceID_` --> I get the response "`No snapshot`" 100% of the time

Is the plugin using the first one or the second one?

I'm sure it was working until recently (at least the 19th of November) as I built an automation with NodeRed to save the snapshots received by homebridge on my google drive when an event was triggered by the doorbell. Then my sd card died and I had to reinstall everything from scratch.

**Comment by dgreif** [comment]
The plugin is using the `app-snaps` endpoint: https://github.com/dgreif/ring/blob/bdb58f8d63da48319ed7c4c38fa7c85337b07c8a/packages/ring-client-api/ring-camera.ts#L568

**Comment by Kaiserben** [comment]
> The plugin is using the `app-snaps` endpoint:
> 
> https://github.com/dgreif/ring/blob/bdb58f8d63da48319ed7c4c38fa7c85337b07c8a/packages/ring-client-api/ring-camera.ts#L568

Really weird, I'm getting consistently a snapshot from this endpoint with NodeRed installed on the same raspberry as my homebridge.

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/82468476/209412286-119e500b-d627-42f1-8027-62228c6599ab.png">

Could the issue be with the new homebridge structure (including NodeJS etc...) that could not handle the snapshot? My previous homebridge installation (which worked with Snapshot) was installed the old fashion way (separate installation of Node JS, then homebridge, then the plugin). That's the only difference i can tell with my previous build.

**Comment by dgreif** [comment]
@Kaiserben that's really odd that it works from Nodered but not in the homebridge plugin. You are welcome to try adding some debug logging in the homebridge-ring code (around the line that I linked above) to see if you can tell what the status code and response body are when the snapshot requests fails. Unfortunately I'm not able to recreate this issue at all.

**Comment by MoTechnicalities** [comment]
Yep! Time to pull the plug.

**Comment by Kaiserben** [comment]
I’m not dev but I’ve started an udemy course to learn Typescript on my free time. Hopefully I’ll be able to get this done. :)

**Comment by Kaiserben** [comment]
Happy new year @dgreif !

I've spend quite a lot of time to understand how to configure a local homebridge, clone a repo on my machine and mess with the code... I've got a lot of issues in understanding how to instal/build my modified plugin into homebridge but finally succeeded \o/

It was very a very interesting process :)

Now I I think I manage to get basic additional logs from getNextSnapshot --> it seems to be a timeout error

`TimeoutError: Timeout awaiting 'request' for 20000ms`

Message I never get from nodeRed... Tested again and getting a snapshot almost instantly (< 5 seconds) every time I try
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/82468476/210260446-03b98ab9-7349-4bdc-a018-883d0e5b1ec2.png">

I've displayed the URL that is used by the plugin  to get the snapshot and it is exactly the same as the one I use in nodeRed.

Is it possible to get a detailed log of everything that is going on in node while le plugin is running? The complete request to the API with the parameters for example.

Thanks again for all the work on this plugin!

**Comment by dgreif** [comment]
@Kaiserben you can add logging in the `rest-client.ts` file, which is where the requests are passed to `got` which is the http client

**Comment by Kaiserben** [comment]
I added some logs in `requestWithRetry` function and I can see the plugin querying :

`https://app.ring.com/api/v1/mode/location/
https://api.ring.com/clients_api/ring_devices
`

but nothing from `https://app-snaps.ring.com/snapshots/next/` which is consistent with the error message I trapped in `getNextSnapshot`or `request` functions: `TimeoutError: Timeout awaiting 'request' for 20000ms`.

From `request` function, I can see the following parameters are passed when trying to fetch a snapshot:
`url : https://app-snaps.ring.com/snapshots/next/xxxxx` with xxxx being my correct device ID
`hardware ID: xxxxxxx-xxxx-xxxx-xxxx-xxxxxx` which is something i don't understand (not found from in the response from ring_devices for example.

I've tried to add this suspicious header `Hardwareid` with the value  in NodeRed and I was still successful to get a snapshot so i don't believe this is the root cause of the issue.

Hypothesis:
-I don't believe there is something to do with the network as NodeRed and the Ring plugin should use the same ports to query https://app-snaps.ring.com/snapshots/next/ ? 
- Could it be a bug in the node version I use (v19.3.0) not being able to manage jpeg buffer? :/

**Comment by Kaiserben** [comment]
@dgreif Finally... Just downgraded the node version to 16.9 on my mac... And you know what? SNAPSHOTS ARE WORKING BACK !!! 👍 

The bug was due to the latest node version 19.3 !!!!

So the issue is probably the same but nodeJS is embedded in the homebridge install for raspberry now : https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian (18.12.1)

Any way to downgrade the bundled nodeJS ? Or report a bug to homebridge team?

**Comment by Kaiserben** [comment]
@jchristianj To solve the issue until homebridge is fixed with Node 18, you need to downgrade to Node 16 --> `sudo hb-service update-node 16.18.0`

<img width="653" alt="image" src="https://user-images.githubusercontent.com/82468476/210648747-29e217c7-1199-44af-a947-96cc2596cf93.png">

**Comment by jchristianj** [comment]
@Kaiserben Yes!! Working again. Thanks for digging and providing a solution. I have been on node 18.x as I read that odd numbers of node.js are not supported by homebridge. See here: https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js
But anyhow, node.js 18.x obviously had an issue, now I am on 16.18.0 and all is fine.

**Comment by mjreddy** [comment]
@Kaiserben you genius! Yes, that seems to have worked for me as well. Snapshots now showing properly in HomeKit. Thank you!

**Comment by dgreif** [comment]
Very interesting! @Kaiserben thank you for all your digging, I'm glad you were able to get to the bottom of it! 

I'm currently running node `18.10.0` and haven't noticed any issues, but I'll update to the latest v18 and see how it goes. For now, sounds like dropping back to v16 is the best solution

**Comment by databoy01** [comment]
Actually, @dgreif (Dusty), I used the command >>sudo hb-service update-node 18.10.0. And I have to say that Node actually works better than any node I have had to date!  My snapshots load in less than 10 seconds now.  Never saw this response before. This seems like the right solution actually…

**Comment by MoTechnicalities** [comment]
@dgreif (Dusty),

**I'm on the new Apple Home architecture, and these are my observations.**

Begining Test >>> Node.js v18.12.1 => **Ring Snaps:** _NO_, **FFmpeg Snaps:** _Yes_
Downgrade >>> Node.js from v18.12.1 to v18.10.0 => **Ring Snaps:** _NO_, **FFmpeg Snaps**: _Yes_
Downgrade >>> Node.js from v18.10.0 to v16.18.0 => **Ring Snaps:** _Yes_, **FFmpeg Snaps:** _Yes_
Upgrade >>> Node.js from v16.18.0 to v18.12.1 => **Ring Snaps:** _NO_, **FFmpeg Snaps**: _Yes_
Downgrade >>> Node.js from v18.12.1 to v16.18.0 => **Ring Snaps:** _Yes_, **FFmpeg Snaps:** _Yes_

**My conclusion:** I'm not sure what FFmpeg does differently than Ring. So, either it's true that the problem is Node.js v18.10.0 and up (which must mean that  FFmpeg doesn't use Node.js in the first place) or something is wrong with the way Ring is using the newer Node.js v18.10.0.

**Question:** Is the Ring plugin doing something different than FFmpeg for snapshots? If so then what?

**Comment by MoTechnicalities** [comment]
Well, I just tried the new >>> **Node.js v18.13.0**
**Ring Snapshots still DON'T WORK** while FFmpeg is still reliable.

So, I guess everyone is stuck using **Node.js v16.18.0** until someone figures out the fault.

**Comment by MoTechnicalities** [comment]
**Node.js v16.19.0** works too.

**Comment by Darrilla** [comment]
Using 16.19.0, The snapshots work for about 45 minutes. Then, it gets back into this state "failed to refresh after 15 seconds". I am using the ring-client-api, but it is exactly the same behavior. Any other suggestions on how to keep it stable for longer periods of time? (I am requesting a snapshot every 15 seconds in my test code).

**Comment by MoTechnicalities** [comment]
!!! **ISSUE RESOLVED** after Upgrading to Node.js Version v18.14.0 & NPM 9.4.2 !!!

**Comment by jchristianj** [comment]
> !!! **ISSUE RESOLVED** after Upgrading to Node.js Version v18.14.0 & NPM 9.4.2 !!!

confirmed, working for me as well.
