### ISSUE TITLE
No audio. 

### ISSUE THREAD

**Issue by metroidmen** [dgreif/ring#113]
Just updated to the new update that should include audio and there is none, unfortunately. :/

**Comment by dgreif** [comment]
https://github.com/dgreif/ring/wiki/FFmpeg

**Comment by dgreif** [comment]
@metroidmen closing with assumption that you get up and running after following those instructions.  Let me know how it goes

**Comment by metroidmen** [comment]
Trying the steps now. One of them is taking ages.

**Comment by metroidmen** [comment]
That’s working! Thanks! Sorry to have jumped the gun. Didn’t realize there were preparation steps. Great job. 🙂

**Comment by dgreif** [comment]
No problem!  I wanted to get it released and go through all the steps on my rpi3 before making an "announcement" in #103 .  I think everything is solid at this point, but it does suck to go through that long build process.  I'm thinking about including a pre-built copy specifically for the rpi since I think that's what most users are running homebridge on.  Thanks for confirming that it works!
