### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by StefanTR96** [dgreif/ring#1140]
# Bug Report

Install of Ring-API-Client not possible

### To Reproduce
Want to install Ring-API-Client and get following warnings 
`iobroker@iobroker:/opt/iobroker/node_modules/iobroker.ring$ npm i ring-client-api`
`npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
`
After changing to `/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api` and  `node ring-auth-cli` i get following message: 

`node:internal/modules/cjs/loader:959
  throw err;
  ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.ring/node_modules/ring-client-api/ring-auth-cli'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

### Expected behavior
working installation

### Environment
 - OS: Debian11 bullseye
 - Node.js: 16.17.1
 - NPM: 8.19.2 
 - ring-client-api:

**Comment by tsightler** [comment]
It's not really clear what you are attempting to do, but I don't believe your issues are related directly to this project.  None of the dependencies listed appear to be dependencies of the current versions of ring-client-api and I can install ring-client-api with no issues.  You should likely submit this issue to ioBroker rather than to this project but a good idea would be to attempt to installation ring-client-api into a clean folder oursite of ioBroker and, if it works, then it's unlikely to be a problem with this project.

**Comment by StefanTR96** [comment]
I Hi, thanks, think it was my fail at installation
