### ISSUE TITLE
API token not expiring (as it says it should in the wiki)

### ISSUE THREAD

**Issue by devvthedev** [dgreif/ring#1141]
# Bug Report

### Describe the Bug
Not sure if this is a bug or not! 
But when I use the CLI to generate a token, I've been able to use that same token when running my code without generating a new one or utilising the _onRefreshTokenUpdated_ method.

Is this intended? Have I misread the docs?

Also, I've generated two tokens, is there a way to expire one myself? Or does generating a subsequent token expire the first?

Thanks!

### To Reproduce
Use the CLI to generate an API token and use it multiple times.

### Expected behavior
The token will still work after it's been used the first time and is used again successfully.

### Environment
 - ring-client-api : latest version

**Comment by tsightler** [comment]
This is just basic OAuth 2.0 behavior, you are acquiring an OAuth refresh token from Ring, it will be valid for whatever period of time Ring uses for refresh_tokens.  I don't remember exactly how long, but it's measured in weeks, not hours, certainly not just one-time use.  My development instance sometimes goes weeks without being used and the token is still good when I come back.  However, it will eventually expire, which is why using onRefreshTokenUpdate() is important, at least if you want to make sure the application doesn't lose access.

I'm not aware of any way to expire a specific token, as mentioned above, it's Ring the controls the lifetime of a refresh token.  I suppose you can remove the authenticated device using account control.  As far as I can tell Ring is just using basic OAuth 2.0, so you can read up on the protocol specs easily.

**Comment by tsightler** [comment]
BTW, I'm guessing the wiki entry was written back in the day when Ring was undergoing a huge change to force MFA with for all users due to all of the issues with Ring accounts being compromised and the bad news associatted with that.  Ring did some crazy things with auth back then, including having some ridiculously fast expiring refresh tokens, but that was a few years ago and the authentication tokens have been pretty stable for the last year or longer.

**Comment by devvthedev** [comment]
> BTW, I'm guessing the wiki entry was written back in the day when Ring was undergoing a huge change to force MFA with for all users due to all of the issues with Ring accounts being compromised and the bad news associatted with that.  Ring did some crazy things with auth back then, including having some ridiculously fast expiring refresh tokens, but that was a few years ago and the authentication tokens have been pretty stable for the last year or longer.

Thanks!

Yep, I initially read the wiki entry which led me to believe the token would just expire. 

I'd be happy to update the wiki if you like?

Also, for anyone else wondering about manually expiring a token, what I did find is if you change your ring account password then all refresh tokens that were in use will be expired.

**Comment by dgreif** [comment]
@devvthedev sorry for the confusion. I've updated https://github.com/dgreif/ring/wiki/Refresh-Tokens#refresh-token-expiration to hopefully be more clear.

In terms of forcing tokens to expire, the easiest method is to go into the Control Center -> Authorized Client Devices section in the Ring app. From there, you can delete the authorization for any given device, which invalidates all associated auth/refresh tokens.

**Comment by devvthedev** [comment]
Thank You! 😊
