### ISSUE TITLE
No Preview when someone is ringing

### ISSUE THREAD

**Issue by unstressable** [dgreif/ring#1143]
# Bug Report

### Describe the Bug
 No Preview when someone is ringing

### Expected behavior
 I expected a thumbnail

### Screenshots/Logs
 
![image](https://user-images.githubusercontent.com/50423935/214383833-e58abe03-545c-44f8-9de4-df2c25e7599f.png)

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
```
{
    "refreshToken": "xyz",
    "unbridgeCameras": true,
    "hideDoorbellSwitch": true,
    "hideCameraLight": true,
    "hideCameraMotionSensor": true,
    "cameraStatusPollingSeconds": 20,
    "locationModePollingSeconds": 0,
    "platform": "Ring"
}
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment
<!-- ✍️edit: -->
 - OS: Raspian
 - Node.js: 16.19.0
 - NPM: 8.19.3
 - homebridge-ring: 11.7.1
 - homebridge: 1.6.0
 - hoobs: N/A

**Comment by dgreif** [comment]
You will need to make sure that you have "Rich Notifications" turned on. Within the Ring app, go to the settings for your camera -> Device Settings -> Notification Settings -> Rich Notifications. From there you can toggle Rich Notifications on.

**Comment by unstressable** [comment]
> You will need to make sure that you have "Rich Notifications" turned on. Within the Ring app, go to the settings for your camera -> Device Settings -> Notification Settings -> Rich Notifications. From there you can toggle Rich Notifications on.

Thanks for the advice, but the App tells me that I have to buy a premium subscription for that?
Isn‘t there a way around?

**Comment by tsightler** [comment]
No, there is no workaround.  If you want reliable notification with images from Ring cameras, especially battery/low-power mode cameras, then you must have a Ring Subscription.  These cameras do not allow taking a snapshot while a recording is in progress and, since homebridge-ring doesn't know about the motion event until the notification arrives, the camera is already recording.

The only way to get a notification image for these cameras is to have a Ring subscription which enables rich notifications, which include a snapshot as part of the notification, then homebridge-ring can retrieve that image when it receives the motion notification.  This is a well documented and known limitation of Ring cameras, please read https://github.com/dgreif/ring/wiki/Snapshot-Limitations for more details.

**Comment by unstressable** [comment]
Tanks a lot!
