### ISSUE TITLE
Implement "ding" property for Ring Intercom

### ISSUE THREAD

**Issue by hesral** [dgreif/ring#1181]
# Feature Request

### Description
Imlement the "ding" skill for Ring Intercom devices. The lock/unlock property is working great with homebridge so far. it would really be cool, if the "ding" for the doorbell could also be implemented.

### Describe the solution you'd like
Maybe the work of tsightler for ring-mqtt would be helpful for implementing this feature:
https://github.com/tsightler/ring-mqtt/blob/dev/devices/intercom.js

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by tsightler** [comment]
But homebridge-ring already has a programmable switch for the doorbell.  I used a "ding" just because I have different limitations with MQTT and what Home Assistant MQTT integrations support.

**Comment by hesral** [comment]
@tsightler hm, you are right. There are two more entities in my homebridge. In "homeassistant" there is an additional "identify" property for my ring. However, nothing happens with those entities when the door rings. Should not there be a state change?

**Comment by tsightler** [comment]
I'm far from an expert in Homekit as I don't use Apple products, but in most automation plaforms buttons create "events" because, well, a button doesn't technically have state, and you can create automations that are triggered by these events.  I mean, technically, even Ring doorbells/cameras don't really have state, note that in the Ring app you don't see any state, you just get events for motion/ding.

Because Home Assistant doesn't really offer a MQTT button entity (technically there is one, but it's for sending events when buttons are pressed in the UI, not for receiving events from external buttons) I implemented the doorbell as a binary sensor instead, and I emulate some type of state by just holding on state for a period of time before reverting back to off, but it's totally a fake "state".

Homekit appears to support proper button events (HA does as well, just not via MQTT as far as I can tell), so it appears to me that homebridge-ring should be creating button press events that are somehow consumable in Homekit.  How is left to someone that knows something about Homekit I guess.

**Comment by hesral** [comment]
Just an update to this - I've just updated to the new version 5.2 of ring-mqtt and when I press the button of the ring intercom an event is being generated there.

**Comment by dgreif** [comment]
@hesral it sounds like this may be resolved? if not, maybe it should be opened as a new issue on ring-mqtt?

**Comment by hesral** [comment]
Sorry, I meant that with the latest version of ring-mqtt something happens when the intercom button is pushed, e.g. an event is being generated im HomeAssistant through ring mqtt. 

However, nothing happens with the ring implementation within homekit. I would expect some form of event here as well.

**Comment by dgreif** [comment]
There is a "programmable switch" exposed as part of the intercom accessory. This switch should be triggered when the intercom button is pressed. It won't cause a doorbell noise from HomePods, or anything along those lines, but you should be able to trigger automations with it.

**Comment by tommyguuuun** [comment]
Are you maybe using the homebridge-ring plugin via the iOBroker homebridge plugin? I had the same issue and the problem was, that there was no polling interval set in the homebridge configuration. Therefore the value kept being "0". Now the std value is "null", while it switches to "0" when the doorbell is triggered. Works perfect.

**Comment by dgreif** [comment]
Having not heard back from @hesral, I'm fairly confident that the homebridge implementation already provides the needed mechanisms for handling a press of the intercom button. Let me know if that is incorrect.
