### ISSUE TITLE
11.7.3 connection error on Motion Snapshot Fetch

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#1187]
This happens when motion is detected, live stream and normal snapshots work fine.

<img width="1235" alt="Screenshot 2023-03-27 at 11 45 53" src="https://user-images.githubusercontent.com/47482260/227920222-a93b3b8e-2b74-4afd-b125-255cb0cff532.png">

**Comment by stevehoek** [comment]
Same for me.

**Comment by tsightler** [comment]
Just for clarity, I'm pretty sure this problem is not specific to 11.7.3 as this is happening in ring-mqtt as well and it still uses the previous versions of ring-client-api.  I haven't had time to dig into it fully but, at first glance, it looks like the UUID field from the push notification may have the doorbot ID appended to it, while I don't remember that being the case previously.

> Requesting motion snapshot using notification image UUID: 027eafd9-e539-4047-9b37-9fcd8f69c134:31710226

I don't remember that being on the end of the UUID previously, but perhaps I just never noticed before.

**Comment by tsightler** [comment]
OK, hacked up a fix for ring-mqtt to strip out only the UUID and can confirm that motion snapshots start working again, so it seems that Ring definitely added this extra, unexpected data to the end of the UUID string in a recent API change.  Not sure how @dgreif wants to handle it, but I'll push out a workaround for ring-mqtt sometime soon.

**Comment by nikunp** [comment]
Is there any fix for this?

**Comment by dgreif** [comment]
I've released a fix in `11.7.4`

Thanks for the pointer on cleaning the uuid @tsightler! I added a `cleanSnapshotUuid` function, which is now automatically run when calling `getSnapshot`, `getNextSnapshot` and `getSnapshotByUuid`. Hopefully this allows you to remove your workaround in ring-mqtt
