### ISSUE TITLE
Ring Intercom not ringing

### ISSUE THREAD

**Issue by salemsayed** [dgreif/ring#1212]
# Bug Report

### Describe the Bug
The new Ring intercom is no longer ringing in Home.app. Previously, the Home.app would send a “Doorbell Rang” notification but that no longer happens at all. Also, I have an action assigned to the exposed switch that should get triggered on ringing but that also stopped working. However, the lock button is still working and I can unlock correctly with no issues.

### To Reproduce
 - Physically ring the intercom
 - Ring app would send the notification but the Home.app wouldn’t

### Expected behavior
Both Ring app and Home.app should send a notification that the doorbell rang.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Ubuntu
 - Node.js: 18.15.0
 - homebridge-ring: 11.7.5
 - homebridge: 1.6.1

**Comment by tsightler** [comment]
It seems like push notifications have mostly stopped working in the last few days.  I still get some stuff through, but only about 1-in-5 notifications seems to work.  I'm seeing other reports as well, all seemed to start around the same time (2-3 days ago).

**Comment by salemsayed** [comment]
Yup, exactly that. Some notifications come through but most aren't. Happy to give @dgreif access to my intercom if needed for debugging

**Comment by tsightler** [comment]
I'm not sure if any special access is needed as I'm seeing this across the board, cameras and doorbells too.  Anything that needs push notifications to work.  Unfortunately, I haven't had time to attempt to dig at it, and probably won't for at least a few weeks.

**Comment by salemsayed** [comment]
Oh I thought it's just the intercom as I don't have other ring cameras

**Comment by tammotheus** [comment]
Me too. (Intercom)

**Comment by MaxPower87** [comment]
I can confirm as well. i can control my Ring (intercom) from within Homekit (via Homebridge), but the other way around, from Ring to Homekit (Homebridge) i dont receive any requests/calls (notifications).

**Comment by rachedamer** [comment]
Same here. Also, in my homebridge I am getting the following error over and over again – maybe it is related? 

[12.5.2023, 15:23:48] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/41d22ead-c4ff-4642-a626-8b811bce153d.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

Have tried generating a new API key which did not seem to help.

**Comment by Milinator** [comment]
@tsightler Thanks for that. I will definitely try that. But I am not quite sure what you mean by removing all old devices from Authorized Client Devices in the Ring Control Center. How do I do that and where exactly is the Ring Control Center? I'm sure you are not talking about the mobile Ring App, right?

**Comment by tsightler** [comment]
Yes, you can access Control Center in the Ring app or via Ring.com.  It's where your account settings, shared devices, etc are managed and there is an "Authorized Client Devices" section which shows all devices that have authenticated.

https://support.ring.com/hc/en-us/articles/360038142272-Ring-Control-Center-Information

https://support.ring.com/hc/en-us/articles/15033043742740-Managing-Your-Authorized-Logged-In-Devices

You will get a screen that looks something like this:

![image](https://github.com/dgreif/ring/assets/17784731/f6158210-1e2f-4b63-b781-f409597da131)

You should at least remove any that say "ring-mqtt-addon" and "Device name not found", but I strongly recommend removing all devices, although this will require re-authenticating on any device where you use the Ring app.  The behavior that is seen is when there are a lot of devices in there, especially unused ones, notification seem to get very sporadic.

To be clear, I'm still not sure if it's the intercom issue, but I think it's worth a shot since it has fixed the complaints for ding/motion from cameras that started around the same time.

**Comment by Milinator** [comment]
@tsightler I really appreciate your effort, thanks for that! I just tried it, but I just deleted the "ring-mqtt-addon" and reconfigured it in Home Assistant. That didn't did the trick for now, but I will come back here as soon as I tried to delete all devices.

Just one more question: If I delete all the devices, do I have to completely reconfigure the Intercom or is it just like logging out and logging back in?

**Comment by dgreif** [comment]
> Just one more question: If I delete all the devices, do I have to completely reconfigure the Intercom or is it just like logging out and logging back in?

It's exactly like logging out and back in and should have no impact on your settings, with the exception of notifications. For example, if you have camera motion notifications turned off in your Ring app currently, you will need to turn those off again once you log back in.

**Comment by Milinator** [comment]
I just removed all the devices and only added "ring-mqtt-addon". Sadly the "Ding" still doesn't work :(

What can I hope for? Is it maybe a change in the Ring API and the AddOn will be updated sooner or later? Or maybe it's just an issue on Ring's API side?

I really appreciate all your help!

**Comment by tsightler** [comment]
Eventually it will probably be fixed, but as I don't own an intercom, and I don't believe @dgreif does either, it might not be soon.  I'm quite surprised that it would have changed API behavior has it previously just sent the same push action as a doorbell and, from what I can tell, doorbells are still working.  Perhaps they changed the action type?

**Comment by tsightler** [comment]
Ah, good, glad to know that it is working.  I don't understand why this happens sometimes, it seems like Ring just stops sending notifications to some accounts.  Removing devices and re-authenticating is the only fix I've seen so far.

**Comment by dgreif** [comment]
Thanks for the guidance here @tsightler! I've taken the instructions above and put them into a new [wiki page](https://github.com/dgreif/ring/wiki/Notification-Troubleshooting). Hopefully we can just point to that in the future 😄 

@salemsayed I'd love to hear if removing old devices solves this for you as well. Please give those instructions a try and let us know if your intercom starts giving you notifications again.

**Comment by tsightler** [comment]
@dgreif Thanks for writing the wiki entry, I was going to add something similar to the ring-mqtt wiki, but now I'll just reference yours!

On another note, it still does feel like there's something strange here that impact ring-client-api, but not Ring apps.  This is the first time I've had mulitple users report this issue happening at the same time and it actually impacted my account as well, even though I've never seen the behavior and I've had aboslutely no new devices added to the account.  While both my production and development instances started receiving notifications very erratically, the logged in phone devices and browser still worked fine.  It makes me think there must be something that could be done to reactivate the push notifications.

Interestingly, when the problem was happening, I was also seeing that device.data.subscribed was changing from true to false.  My code monitors this and reports this in the logs, and attempts to resubscribe, which did not seem to fail, but just a few minutes later, it would log this again.  This seemed to be common across all users that reported this behavior.  I've not seen this logged a single time since removing all devices and re-authenticating, even after days.  This seems to indicate something is happening, but it's not clear what exactly.  Maybe I need to dig into the subscribe/unsubscribe functions a little deeper, but I just don't have much time right now, maybe in a few weeks.

**Comment by pepepere** [comment]
Hi, thx for your support!
I have a wired doorbell and the ding event don't work. 
I've deleted all the devices and added only the "ring-mqtt-addon" and "missing device" (my installation is with docker), it has worked for 24 hours, then again it stopped notifying the ding event. I've deleted one more time all the devices, created a new token, and it's working again

**Comment by dgreif** [comment]
@tsightler I think you are probably on to something with the `device.data.subscribed` changing. I wonder if the native Ring apps are regularly updating the subscriptions, or maybe re-creating the push notification registration 🤔. I also don't have much free time to look into this at the moment, but will post back here if I find anything

**Comment by dgreif** [comment]
@tsightler I think you are probably on to something with the `device.data.subscribed` changing. I wonder if the native Ring apps are regularly updating the subscriptions, or maybe re-creating the push notification registration 🤔. I also don't have much free time to look into this at the moment, but will post back here if I find anything

**Comment by salemsayed** [comment]
@dgreif just tried the notification fix right now, missed the updates the days ago. Will test today and report back the intercom notifications issue.

**Comment by pepepere** [comment]
More information... The integration in HA has the same problem, after a while the ding event stops working (here the solution is delete integration and re-authenticate)
It seems as if the token will expire in a short time, just for the ding event. There is no problem in the app, it always works fine. 
As @dgreif , I think it would be necessary to reauthenticate more often...

**Comment by tammotheus** [comment]
> All good on Ring Intercom after the notifications fix, thanks @dgreif @tsightler

I'm a little confused now. The bug still exists, as it comes back after 24 hours. Or will a new case be opened for this? Sorry if I misunderstood something.

**Comment by lesgrebe** [comment]
The ding and the lock/unlock function works but batteryLevel, lastUpdate not updating anymore...

![image](https://github.com/dgreif/ring/assets/37287548/949887c4-9d6c-4897-8ff5-7a693359c227)

**Comment by tammotheus** [comment]
Hhmm. My intercom does not give a „ding“ to Homebridge after approx. 24 hours (after deleting clients and re-authenticating). Unlock/lock is working. Sorry again, just want to get it right.

**Comment by tsightler** [comment]
@lesgrebe That looks like a ring-mqtt specific issue and should be tracked there, not here.

**Comment by lesgrebe** [comment]
Hello,

sorry you´re right, thanks for pointing this out -> already done -> https://github.com/tsightler/ring-mqtt/issues/633
There is also another person who tracked it there -> https://github.com/tsightler/ring-mqtt/issues/632

Thanks a lot!!

Regards
Michi

**Comment by cartermw** [comment]
Thanks so much for sharing the notification fix with me it worked. 👍🏽
