### ISSUE TITLE
subscribe to locationMode changes

### ISSUE THREAD

**Issue by devvthedev** [dgreif/ring#1214]
# Feature Request

### Description
Is there a way to subscribe to location mode changes for Ring Alarm? I cannot seem to find one. Sorry if it's documented somewhere.

### Describe the solution you'd like
Similarly to how we can already subscribe to motion and ding events from Ring cameras. I'd like to be able to subscribe to arm, away or home events.

### Describe alternatives you've considered
Some sort of check every 5 seconds. Not the best

**Comment by devvthedev** [comment]
I've written this to subscribe to LocationMode events and _console.log(newMode)_ is never hit again after changing the alarm status from the ring app or keypad. 

`const myHome = locations[1]

        console.log(myHome.name)

        myHome.onLocationMode.subscribe((newMode) => {
            console.log(newMode)
        });`

Any ideas?

**Comment by devvthedev** [comment]
I've found the following which may help me

https://github.com/daneedk/com.amazon.ring/blob/4fca9947da608f2fe0b8e4f5dc8016d2d8bec4f8/lib/Api.js#L133

**Comment by devvthedev** [comment]
Settled on this but I'm new to typescript!

```
myHome.onDeviceDataUpdate.subscribe(({mode}) => {
            if (mode as AlarmMode) {
                console.log(mode)
            }
        });
```

Wondering why mode encompasses both AlarmMode and ThermostatMode. 

Is it nicer to make them separate in the API? Or is there something better I can do in my code?

Thanks! And sorry for all the comments on this thread!

**Comment by dgreif** [comment]
I do think `onDeviceDataUpdate` is the best option for you to use. Keep in mind this is a fairly generic observable which emits data that matched the [RingDeviceData interface](https://github.com/dgreif/ring/blob/main/packages/ring-client-api/ring-types.ts#L196). Since this is a generic type, `mode` can be for an alarm security panel _or_ a thermostat, which is why you get both of those mode types. This interface is blindly passing along the data from Ring, so there isn't any other more specific types available at the momemnt.
