### ISSUE TITLE
Homebridge-Ring and Ring Doorbell on 2 networks

### ISSUE THREAD

**Issue by lfiocco** [dgreif/ring#122]
Hello. my setup is a little different. my ring doorbell and the Homebridge server are on two different networks. I am not able to stream video, but the snap shots work.

The Homebridge server is able to access the internet.
The Ring Doorbell is able to access the internet. 
But the 2 devices are not able to see each other.

I was able to add it to HomeKit with no issues.

I am not crazy about having Amazon snoop my network, once I get the devices working and setup, I block their internet access and force everything toward the Apple TV. I understand cameras are a little different wondering if this is the issue.

btw getting audio on ubuntu is the same like raspberry pi?

**Comment by dgreif** [comment]
As long as your camera and homebridge server both have internet access, it should be possible to get a live stream.  See https://github.com/dgreif/ring/wiki/Camera-Troubleshooting for troubleshooting steps.  There is a good chance that you are having NAT issues that the plugin is unable to work around, preventing the UDP packets from Rings server from getting back into your network to the homebridge server.  You should be just fine having the cameras on a separate network since they relay the video stream through Rings servers before the stream gets to your homebridge server.

For your last question, yes, you should be able to follow the raspberry pi steps for Ubuntu.

**Comment by lfiocco** [comment]
Thank you for the quick answer and really nice plug-in. 

I am using pfSense and it by default disables uPNP-NAT. Enabling it would create a security issue. I will use it out of the box for now and look for another way to get it working. Putting this in a DMZ will fix this. A good winter project.

Thanks again!

**Comment by SeminolesFan78** [comment]
@lfiocco : Did you ever get this working? I'm also using pfSense.

**Comment by lfiocco** [comment]
No. Since ring screwed everyone with HomeKit I returned it for a full refund

Sent from my iPhone

On Nov 30, 2019, at 10:49 AM, SeminolesFan78 <notifications@github.com> wrote:

﻿

@lfiocco<https://github.com/lfiocco> : Did you ever get this working? I'm also using pfSense.
