### ISSUE TITLE
unbridged  the ring plugin and pairing code will not pair

### ISSUE THREAD

**Issue by karljplunkert** [dgreif/ring#1263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

unbridge the ring plugin.  I have four cameras.
Get the pairing code in the homebridge log.  Will not pair the device.
Upon further investigation all the cameras have the same pairing code.  Additionally it is the same code as bridge

### To Reproduce

install the ring plugin
edit the json file to unbridge the ring devices
get the device pairing code from log file
pair the device.

### Expected behavior

each device gets a valid unique pairing code

### Screenshots

![image](https://github.com/dgreif/ring/assets/41293777/e882d4ed-36a2-479d-85b2-7572f46cc32e)

### Homebridge Ring Config

```shell
"platform": "Ring",
    "_bridge": {
        "username": "0E:FA:B3:98:AB:C5",
        "port": 37901
    },
    "unbridgeCameras" : true
}
```

### OS

Linux

### Node.js Version

v14

### NPM Version

11.8.0

### Homebridge/HOOBs Version

1.4.0

### Homebridge Ring Plugin Version

1.6.1

### Operating System

Ubuntu

**Comment by toogle9** [comment]
This is what I experienced when I unbridged my 3 cameras trying to resolve the issue reported in "Live Stream never starts #1246".  I did not report the duplicate pairing codes, because I had never done that before and didn't realize that was an issue.  Could that be a factor in the streaming issue that I am experiencing?  All 3 cameras did show up when I paired individually (each with the same code), and snapshots work and update frequently enough, but streaming from any of them is essentially broken, only working once every couple of dozen attempts.

**Comment by dgreif** [comment]
This is a detail of the homebridge implementation for unbridged cameras. It will _always_ use the same setup code as your main homebridge instance. This should not cause any actual issues as you still have to manually pair each of the cameras and can provide the same code each time.

@toogle9 the streaming issues you mentioned may be related to Legacy Mode, or it could be network related. In any case, I don't have a specific fix at the moment and suggest you keep on the lookout of updates in the future. Beyond that, using the Ring App will provide the most stable streaming experience.
