### ISSUE TITLE
Ring Plugin continually live streaming Ring Doorbell

### ISSUE THREAD

**Issue by strechy2k** [dgreif/ring#1291]
### Streaming Issue

The ring plugin has started continually streaming my ring doorbell until the doorbell battery is completely drained. I have other cameras on this plugin with no issues. See the log attached. Any ideas?
![Screenshot 2023-08-14 at 21 44 09](https://github.com/dgreif/ring/assets/32655176/3d61e311-b0ac-4efd-b464-4cbfaceeae15)

### Proposed Solution

N/A

### Environment

Homebridge

### What operating system are you on?

Linux

### Honesty Time

- [X] I swear this is worth your time!

**Comment by chriswoods413** [comment]
I have also noticed this problem since 20:45 last night (15/08/2023. I have the home bridge plugin setup under a separate shared account as I have access to multiple locations on my normal account The plugin was constantly streaming the live feed until it drained the battery completely. I changed the battery at 6am this morning and it is still streaming causing the battery to die again just now (10:45 16/08/2023) I have had to disable the plugin to get it to stop. Please can you look into this? I really enjoy the plugin. Having my cameras and alarm in the home app is a godsend since this is the forefront of all my automation and SH in general. Thanks!

**Comment by tsightler** [comment]
I'll probably need @dgreif to comment here, but my initial reaction is that there's not much that can be done from the plugin side.  As far as I understand the plugin, it simply provides two functions, prepareStream() and handleStreamRequest().  These functions are not called by the plugin, they are called by Homebridge when it receives requests from a Homekit client to start a stream.  Based on the logs, these functions are being called, thus something outside of the plugin would appear to triggering them, either a client is requesting a stream (or never ended its request or Homebridge itself is somehow "stuck" and thinks it needs a stream.

At first glance through the code, I personally don't see any possibility how this could be in the plugin itself.  The fact that it just randomly started at a specific time also re-enforces this belief as the plugin itself didn't suddenly change behavior at that moment, something external almost certainly is causing the change in behavior.

But, I'm also super new to Homebridge itself, so there could be something I'm overlooking.

**Comment by dgreif** [comment]
@tsightler is spot on, there isn't anything in the plugin that should cause these methods to get called. It's likely either a bug with homebridge (which hasn't been updated in a while, so unlikely) or with HomeKit (very likely).

For those of you having issues, are you on a beta version of iOS or tvOS? I know a lot of folks are trying out v7 beta, which has caused other issues as well.

**Comment by strechy2k** [comment]
Yes, didn't think about that, have been trying tvOS 17. Hopefully, its this which is causing the issue and will be resolved when the tvOS is released. For the time being, I've set the doorbell camera to hidden and this seems to have stopped the continual battery drain. Will unhide it again in a few days and see what happens.

**Comment by chriswoods413** [comment]
Good point. I’ve been running all the new betas since June, with no issues until a few days ago. Will do the same as strechy2k and hide the doorbell and try it again in a few days.On 18 Aug 2023, at 18:29, strechy2k ***@***.***> wrote:﻿
Yes, didn't think about that, have been trying tvOS 17. Hopefully, its this which is causing the issue and will be resolved when the tvOS is released. For the time being, I've set the doorbell camera to hidden and this seems to have stopped the continual battery drain. Will unhide it again in a few days and see what happens.

**Comment by dgreif** [comment]
Great! I'm guessing the AppleTV is doing something funky causing it to continually request a live stream. I'll close this issue for now, but feel free to provide updates

**Comment by markbajaj** [comment]
I have been burning through batteries for the last week (every day!), until I got here and think it is definitely to do with Beta 6 and 7 of TVOS17. 

It seems a stream is initiated immediately, then never closes.

For now I have disabled the plugin. Do we think this is a permanent change in HomeKit that may need a plugin update or is it something APlle have done (and will fix)?

**Comment by tsightler** [comment]
I don't think anyone knows, but I'd have to assume it is a bug.  If it's a permanent change it's difficult to see how it could be fixed by any update in the plugin as there would be no way for the plugin to tell a legitimate request for a stream from any other request.

At this point I don't think it's worth conjecture.  If Homekit changes in a way that it always requests streams then that seems crazy.  Perhaps there will be some way to register a device as battery powered or on-demand, vs continuous.  Also, has anyone that has experienced this issue checked in Homekit to see if there are new options?  Perhaps a preload-stream or "live preview" option that might cause this.  This is a pretty common feature of non-Homekit platforms so I thought perhaps Homekit is implementing something similar.

**Comment by tsightler** [comment]
> I'm sure it's due to the new Home options in the control center re video.

What new options are you referring to?  I don't own an Apple TV so I have no idea.  It's difficult to see how this plugin can address this as it simply responds to request for a stream, that's it.

**Comment by tsightler** [comment]
Ring sessions generally timeout around 10-12 minutes, but if Apple TV is constantly requesting a stream, it will of course restart.  I don't know anything that can be done from the plugin side at this point.  My wifes iPad and phone are both updated to iOS 17 and Home app still seems to work as expected, so far it seems like it's just a tvOS 17 issue, but I'm not 100% sure.  There are other reports on other plugins and cameras of constant streaming as well, so I'll assume Apple will have to fix it reasonably soon as the current setup is unworkable even with completely local cameras, as you note.

**Comment by markbajaj** [comment]
> Control Center no longer has the Homekit tab.
> 
> I noticed yesterday it was no longer requesting constant streams. The feature in tvOS has disappeared from Control Center. Guess we shall see!

Still there for me - not tried the plugin again as the battery lasts about 8 hours tops. Apple need to sort this as I can't see what can be done with the plugin and battery cameras as a whole.

**Comment by chriswoods413** [comment]
For me, it’s always being requested by my doorbell. None of my other cameras do it. Although my doorbell is the only battery powered camera I haveWhat devices is everyone else seeing it on?On 3 Oct 2023, at 19:53, Tim Baur ***@***.***> wrote:﻿
@dgreif @tsightler -- Is it possible to log the source addr of the device requesting the stream? So that we can identify the device making the requests. Is that information available?

**Comment by tsightler** [comment]
You can add this line:
```
(0, util_1.logInfo)(`Received Live Stream request for ${this.ringCamera.name} from ${request.targetAddress}`);
```
Immediately after `async prepareStream(request, callback) {` in camera-source-js (at approximately line 410),  to log the IP address from the prepare stream request.

**Comment by tsightler** [comment]
If you add the line I posted above it will be in the regular log output.

**Comment by shugass** [comment]
Rebooting my apple tv seems to have stopped the constant live streaming, for now at least....
If it doesn't stick I'll try setting the Apple TV to not even show the doorbell on the TV, which isn't great as it is very helpful to see who is at the door if i'm watching TV.

**Comment by sateeshruttala** [comment]
I have the same issue
