### ISSUE TITLE
Treat motion sensors as occupancy sensors in Homekit

### ISSUE THREAD

**Issue by onegrizzle0g** [dgreif/ring#1308]
### Description

Is there a way we can force HomeKit to treat Ring Motion Sensors as occupancy sensors instead of motion sensors? 

There is an option in ZigBee z2m to treat motion sensors as occupancy and works a treat.

**Comment by dgreif** [comment]
I agree, this is something I'd prefer not to add. The sensors are truly motion sensors, not occupancy sensors, so I think we are exposing them as they should be. I also don't like making one-off config options like these since it's just more maintenance burden 😄.  Sorry we can't accommodate your request @onegrizzle0g, I hope you understand!
