### ISSUE TITLE
Probleme the install last version ring plugin

### ISSUE THREAD

**Issue by Nelson4073** [dgreif/ring#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Hello i can't install the la version

12:29:02error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-rxjs-6.6.7-90ac018acabf491bf65044235d5863c4dab804c9-integrity/node_modules/rxjs/.yarn-metadata.json: Unexpected end of JSON input".

### To Reproduce

at the installation

### Expected behavior

stop installation

### Relevant log output

```shell
12:28:54[1/4] Resolving packages...
12:29:01[2/4] Fetching packages...
12:29:02error An unexpected error occurred: "/usr/local/share/.cache/yarn/v6/npm-rxjs-6.6.7-90ac018acabf491bf65044235d5863c4dab804c9-integrity/node_modules/rxjs/.yarn-metadata.json: Unexpected end of JSON input".
12:29:02info If you think this is a bug, please
```

### Homebridge Ring Config

```shell
no config
```

### OS

4.2.8

### Node.js Version

no

### NPM Version

no

### Homebridge/HOOBs Version

HSLF-2

### Homebridge Ring Plugin Version

no

### Operating System

windows

**Comment by tsightler** [comment]
As you appear to be using HOOBS, you should reach out to HOOBS support for installation issues.  The issue above does not appear to be related to anything with the plugin, the mentioned rxjs version is something very old and not used by the plugin and it is not in the plugin path.  There are many known issues with yarn and corrupt due to failed dependency installs that are very similar to what you are reporting, but this isn't directly related to the plugin.

If I were just to offer a suggestion, as you are seeing failures with yarn, and it appears to be yarn cache, you can try something like:

`yarn cache clear`

I don't know how likely this is to work for your specific case, but again, HOOBS support is the best path to resolve such issues.
