### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#134]
Why does the HomeBridge startup log always display this?

[Homebridge] [9/18/2019, 7:38:38 PM] Front Door is running on port 34623.
[Homebridge] [9/18/2019, 7:38:38 PM] Please add [Front Door] manually in Home app. Setup Code: 031-45-154
[Homebridge] [9/18/2019, 7:38:38 PM] Deck Door is running on port 37823.
[Homebridge] [9/18/2019, 7:38:38 PM] Please add [Deck Door] manually in Home app. Setup Code: 031-45-154
[Homebridge] [9/18/2019, 7:38:38 PM] Side Door is running on port 46213.
[Homebridge] [9/18/2019, 7:38:38 PM] Please add [Side Door] manually in Home app. Setup Code: 031-45-154

It seems like it has never been added to the home app, but it has...

**Comment by dgreif** [comment]
This is just the behavior from homebridge when dealing with cameras.  Because the cameras are separate from the "bridge" accessory, you have to add them each individually to HomeKit.  Homebridge displays this info every time it starts so that if you remove a camera from HomeKit, you have the info you need to add it back.  I don't think homebridge has a good way of knowing whether or not the cameras are currently in HomeKit (or maybe it does but the developer just didn't use it)
