### ISSUE TITLE
mp4 on Windows but not on Linux

### ISSUE THREAD

**Issue by thrahlf** [dgreif/ring#1364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I used the example recoed-example.ts.

On Windows it works. I got the file with mp4. Same Script on Linux doesn't work. The example.mp4 file is created but with 0KB.

ffmeg is installed. Any Ideas? I found nothing in the logs....

### Expected behavior

That the file exist the stream...

### OS

Linux

### Node.js Version

V16.20.02

### NPM Version

V8.19.4

### ring-client-api

v11.8.1

### Operating System

Linux openhabian

**Comment by tsightler** [comment]
Certainly not enough information here to have any ideas.  I only use this code on Linux and it all works just fine, including the sample code.  I would suggest using newer node version (at least 18) and the current version of the API.

**Comment by thrahlf** [comment]
Thanks for the fast answer. I tried the sames NODE and API Version on both systems. The result is the sames.

Which libaries do i need on linux for ffmpeg. Only this oder additional?

**Comment by tsightler** [comment]
> Thanks for the fast answer. I tried the sames NODE and API Version on both systems. The result is the sames.

I'm not sure what this means, the versions you listed are older and outdated, some dependencies may need newer versions and behaviors can be unpredictable across OS versions.   You should always use the latest versions as those are the only versions currently tested.  I'm not going to go back and install old, unsupported versions of Node to test this, please use current versions to report issues.

Regarding ffmpeg, there are generally no external dependencies, ring-client-api pulls in ffmpeg-for-homebridge, which downloads a specially built ffmpeg which should generally be used in all cases where possible since the system based ffmpeg likely doesn't have libfdk-aac support, although technically this should not be required for recoding (needed mostly for homekit support).  These packages have been going through some significant updates lately, so it's possible a bug has been introduced there.

**Comment by thrahlf** [comment]
I reinstalled the project with the same NODE and API version, and... It works! ;-)
