### ISSUE TITLE
Toggle to always allow the bypass of sensors?

### ISSUE THREAD

**Issue by tiimjcb** [dgreif/ring#1366]
### Description

- This feature request concerns the ring security system 2nd gen.

Hello, my issue is simple : many times, we forget to close an inside door, where there's a sensor. This result as the alarm not arming when using a siri command. And it wouldn't be mom-validated if I tell her that she needs to arm it in night mode (it would also be confusing when we want to arm it at night, in presence mode).

So can it be possible to make a toggle that enable the possiblity to always bypass, without any night mode?

Thanks a lot!

### Proposed solution

Make a toggle that allows the user to always bypass when setting in at home or absent mode, instead of using "night" mode

### Alternatives

Not much since there's already an alternative. This is more like an enhancement request

### Device data

https://pastebin.com/VauZAY7v

**Comment by tsightler** [comment]
I'll let @dgreif comment here before I close this, but my gut says this project already has plenty of toggles for various things and night mode has worked fine for 99.9% of users requirements so I'd lean toward not changing anything.

**Comment by dgreif** [comment]
I'd really prefer not to add another option unless completely necessary. @tiimjcb have you considered using a "Scene" in the Home app as a shortcut for turning on night mode? Then you can just say the name of the scene instead of having to say some very specific Siri command. Would only help with one of the modes (home or away), but maybe that's enough for you?

**Comment by tiimjcb** [comment]
hello @dgreif  
well, that's what i've done for now. it works well, so it's ok👍🏼 guess you can close this issue
