### ISSUE TITLE
brief delay in HomePods chime when pressing intercom button

### ISSUE THREAD

**Issue by BrauCadena** [dgreif/ring#1381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When pressing intercom button in Ring Doorbell the chime has a brief delay in HomePods. (3 seconds) I put the cameraStatusPollingSeconds with 1 second but the delay persist.

Please note that in Scrypted there is no delay.

### Expected behavior

When pressing intercom button in Ring Doorbell the chime should be sound almos in,meeditily in HomePods.

### Homebridge Ring Config

```shell
{
            "refreshToken": "Token",
            "cameraStatusPollingSeconds": 1,
            "platform": "Ring"
        }
```

### Additional context

For me, the Ring plugin for Homebridge works better than Scrypted but the chime on HomePods sound faster in Scrypted.

### OS

Raspberry Pi OS

### Node.js Version

v18.13.0

### NPM Version

--

### Homebridge/HOOBs Version

v1.7

### Homebridge Ring Plugin Version

v12.1.0

### Operating System

Raspberry Pi OS

**Comment by tsightler** [comment]
This plugin uses push notifications rather than polling to receive notifications from Ring so changing cameraStatusPollingSeconds is not going to change anything and will only likely server to get your IP throttled/banned/blocked by Ring.  I would strongly suggest not changing the default unless you have a specific reason to do so.  Personally, I think we should ignore values less than 20 seconds or so anyway as there is very little benefit to polling more frequently than this as the backend Ring state doesn't even update this frequently for most values.

> Please note that in Scrypted there is no delay.

So feel free to use Scrypted as there is little reason to use both, although I'll admit I'm quite surprised as I can't really find anything in the Scrypted code that indicates it even supports intercoms, nor does the documentation indicate that intercoms are supported.  Does it just treat it like a camera with no video?  Overall Scrypted is not really different from this plugin, it's built using a slightly modified version of the same API maintained here, and it doesn't require Homebridge so none of that, but there's not much to this, push notification received, state updates, that's it.

The only practical way to troubleshoot something like this is to look at the logs and compare the time the event is received in the logs to the time the HomePods chime and see if the delay is on the Ring side or the Homebridge side, but in any case it's unlikely to be in the plugin as there are no delays in the code, but if you can provide logs showing the delay (might need a video or something to compare the two, or at least a very detailed description) then we can look at it, but really hard to see how it could be anything in the plugin.

**Comment by BrauCadena** [comment]
Thanks for the feedback @tsightler!!

I mentioned Scrypted so you wouldn't think it was a network error.

How can I get the logs of RING plugin?

**Comment by tsightler** [comment]
The same way you get any logs for Homebridge, most people just use "view logs" in the web UI.  You'll also want to go into settings on the ring plugin and select debug logging so you get more data there.  I think you should get some message there when the intercom is pressed, this is what I get for my doorbell:

> [12/29/2023, 3:41:38 PM] [Ring] Front Doorbell Doorbell Pressed. Loading snapshot before sending event to HomeKit
> [12/29/2023, 3:41:38 PM] [Ring] Loading new snapshot into cache for Front Doorbell by uuid
> [12/29/2023, 3:41:39 PM] [Ring] Snapshot cached for Front Doorbell by uuid (0.608s)

I'm not 100% sure what the intercom would show, but I checked my doorbell and the notification was about 1 second, just slightly behind the Ring app notification, my a few hundred milliseconds.  The intercom effectively works the same exact way as a doorbell, just without any method to retrieve a snapshot image, so I wouldn't expect any delay.  Now, I don't use Homepods or anything, that's just me measuring the time for Homebridge to reflect the state, from that point, the plugin has noting to do with anything as all it can do is get the notification and set the state.
