### ISSUE TITLE
ring plugin stopped working, cant lovin anymore

### ISSUE THREAD

**Issue by nak0604** [dgreif/ring#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

this is what i get everytime i try to login after refreshing my expired auth token

 TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (C:\Users\USER\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\ring-client-api\lib\rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### To Reproduce

generate a new auth token for ring plugin and try to login when asked for ring cridentials

### Expected behavior

get a 2 factor authentication prompt or be able to login

### Relevant log output

```shell
TypeError: Cannot use 'in' operator to search for 'error' in <html>
<head><title>406 Not Acceptable</title></head>
<body>
<center><h1>406 Not Acceptable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at RingRestClient.getAuth (C:\Users\user\AppData\Roaming\npm\node_modules\homebridge-ring\node_modules\ring-client-api\lib\rest-client.js:186:119)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "TOKEN",
    "hideInHomeDoorbellSwitch": true,
    "platform": "Ring"
}
```

### OS

windows

### Node.js Version

20.12.2

### NPM Version

10.8.1

### Homebridge/HOOBs Version

1.8.2

### Homebridge Ring Plugin Version

12.1.0

### Operating System

windows

**Comment by johnciprian** [comment]
My plugin also stopped working. I’m getting the following error:
```
Failed to reach Ring server at https://oauth.ring.com/oauth/token. getaddrinf EAI_AGAIN oauth.ring.com.
Trying again in 5 seconds...
```

**Comment by tsightler** [comment]
A 406 error typically means your IP address has been temporarily throttled or otherwise blocked (VPN use for example as Ring blocks many VPNs).  Temporary blocking can occur, for example, if something happens with the token where it constantly retries with a failed token, Ring will block the site and you won't be able to immediately authenticate.  You will have to disable the plugin wait some hours (not sure exactly how long, but 6-8 usually seems to be enough) and the authenticate. 

Also, if you are running on a system that has any VPN client deployed like NordVPN or any of the many others out there, 406 will likely be logged.  There are no known issues with the API at this time and no widely reported outages from users,

**Comment by tsightler** [comment]
> My plugin also stopped working. I’m getting the following error:
> 
> ```
> Failed to reach Ring server at https://oauth.ring.com/oauth/token. getaddrinf EAI_AGAIN oauth.ring.com.
> Trying again in 5 seconds...
> ```



> My plugin also stopped working. I’m getting the following error:
> 
> ```
> Failed to reach Ring server at https://oauth.ring.com/oauth/token. getaddrinf EAI_AGAIN oauth.ring.com.
> Trying again in 5 seconds...
> ```



> My plugin also stopped working. I’m getting the following error:
> 
> ```
> Failed to reach Ring server at https://oauth.ring.com/oauth/token. getaddrinf EAI_AGAIN oauth.ring.com.
> Trying again in 5 seconds...
> ```

This is a different issue and appears to be DNS/network related, if the DNS name cannot be resolved there's not much the plugin can do about it.
