### ISSUE TITLE
Latest version is hammering the Ring API

### ISSUE THREAD

**Issue by stevehoek** [dgreif/ring#145]
I upgraded from 5.70 to 5.82 and now I notice in my Pi-hole that the number of requests to API.ring.com is off the charts.  Everything is working fine, no log messages from Homebridge that any authentication is failing or anything.  
I notice that it seems to be resolving both the ipv4 and ipv6 addresses, which is strange since nothing on my network uses ipv6.

Here is what i see in the Pi-hole logs, repeating every 1-2 second!

Oct  6 16:26:43 dnsmasq[13650]: query[A] api.ring.com from 192.168.0.250
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com is <CNAME>
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com.cdn.cloudflare.net is 104.17.128.1
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com.cdn.cloudflare.net is 104.17.127.1
Oct  6 16:26:43 dnsmasq[13650]: query[AAAA] api.ring.com from 192.168.0.250
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com is <CNAME>
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com.cdn.cloudflare.net is 2606:4700::6811:8001
Oct  6 16:26:43 dnsmasq[13650]: cached api.ring.com.cdn.cloudflare.net is 2606:4700::6811:7f01

Any ideas?

**Comment by dgreif** [comment]
@stevehoek this is expected behavior.  Unfortunately Ring does not support websockets for camera events (like they do for all the new alarm/lighting), so we have to resort to polling their API for events.  By default, the plugin checks for new dings/motion events every 2 seconds.  This is configurable with the `cameraDingsPollingSeconds` option if you really don't want that many requests flying (I know, it's a lot).  The down side to making that option larger is that you have a potential of waiting that long for new events to appear in homebridge.  For example, if you set it to 30, it can take _up to_ 30 seconds before you will get a doorbell/motion notification from your cameras.

**Comment by stevehoek** [comment]
OK, I understand now.  And in fact, I found another closed issue where someone gave instructions on how to install the dns caching service on debian, so I switched my container to use that.

The strange thing is, before upgrading from 3.7.0, I swear I did not see this kind of polling activity on my DNS server (Pi-hole), and the cameras were working just fine then as well.

**Comment by dgreif** [comment]
That's definitely odd, but I don't think there were any code changes between `5.7.0` and now that would cause changes in the polling.  Maybe something on the DNS side changed for you, who knows.  Glad you found a good solution tho!
