### ISSUE TITLE
v13 does not work on HOOBS due to outdated NodeJS

### ISSUE THREAD

**Issue by caseyrichards** [dgreif/ring#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

RingERRORFailed to reach Ring server at https://oauth.ring.com/oauth/token.  fetch is not defined.  Trying again in 5 seconds...

### Expected behavior

Was working until I upgraded to 13. Now this happens in the logs and nothing works.

### Screenshots

<img width="1341" alt="Screenshot 2024-08-06 at 2 25 57 PM" src="https://github.com/user-attachments/assets/af7578c8-6a95-492f-8a70-d8b68d52e5aa">

### Homebridge Ring Config

```shell
.
```

### OS

Linux

### Node.js Version

v16.20.2

### NPM Version

?

### Homebridge/HOOBs Version

v4.3.1

### Homebridge Ring Plugin Version

v13

### Operating System

?

**Comment by WhatTheMiguel** [comment]
I also have this issue

**Comment by tsightler** [comment]
You must upgrade your NodeJS version.  NodeJS v16 has been unsupported for nearly a year (since 11 Sep 2023).  It is stated in the release notes v13 will break any users on Node v16 or older.  If you don't know how to upgrade your NodeJS version you should contact HOOBS support.

**Comment by caseyrichards** [comment]
Yes but I have performed the Hoobs node update steps and it doesn’t seem to allow installing past 16. Is there a way to manually force the install to a later version?On Aug 6, 2024, at 3:37 PM, tsightler ***@***.***> wrote:﻿
Closed #1459 as completed.

**Comment by tsightler** [comment]
This is a question for HOOBS support.

**Comment by tsightler** [comment]
In looking at the website and community forums for HOOBS, I would say that HOOBS is a dead product.  There have been effectively no commits from the two primary contributors since Mid-2003 (before that it was very active).  People have been waiting for the second block of HOOBS Pro for 18 months with no updates.  No responses to any issues on Github, no responses from anyone of the "forums" (a Facebook page).  Everywhere people are calling them scams, etc.

There are mulitple Homebridge plugins that require NodeJS v18 or newer, Ring v13 is nowhere near the first to make this switch and we have no options as upstream dependencies are dropping support for older versions (push-receiver, for example, requires fetch as well).  This makes total sense as NodeJS v18 and v20 are the supported versions.  Post about upgrades to NodeJS v18 on the HOOBS Github from earlier this year have gone answered.

Unfortunately, you will likely have to accept that HOOBS is dead.  The good thing is, it's not needed, you can install NodeJS and run Homebridge just fine without HOOBS and many posts indicate that this is what some HOOBS users have decided to do.  We can't help here, we're just plugin maintainers, but that seems to be the reality of the HOOBS situation.  If someone has information that is different than this, feel free to share it here but, IMO, and in that of dozens of other posters I was able to find, HOOBS is dead.

**Comment by caseyrichards** [comment]
Appreciate the feedback. I moved on to Homebridge. So far so good. On Aug 7, 2024, at 6:09 PM, tsightler ***@***.***> wrote:﻿
Closed #1459 as not planned.

**Comment by tsightler** [comment]
Just for a quick update here, we did reach out to HOOBS via a backchannel and there's a least a bit of life there as we did receive a response.  They do have HOOBS 5 that they claim will release "soon", although no real indication when that would be.  This has newer NodeJS and Homebridge so hopefully they can get that out.  Apparently it's possible to install this today by switching to the "bleeding" branch.  You can contact HOOBS support for instructions.

**Comment by caseyrichards** [comment]
I greatly appreciate the update. Although at this point think I am better off fully committing to Homebridge as it’s been working well since making the switch and frequently updated and supported. Thanks again!On Aug 15, 2024, at 9:42 PM, tsightler ***@***.***> wrote:﻿
Just for a quick update here, we did reach out to HOOBS via a backchannel and there's a least a bit of life there as we did receive a response.  They do have HOOBS 5 that they claim will release "soon", although no real indication when that would be.  This has newer NodeJS and Homebridge so hopefully they can get that out.  Apparently it's possible to install this today by switching to the "bleeding" branch.  You can contact HOOBS support for instructions.

**Comment by markcarroll** [comment]
I am getting this issue too.  It makes HomeBridge unusable (maxes CPU and memory) until I reboot the container. The HomeBridge docker container is running Node 20. I have logs if you want them although I don't think they will tell you anything you haven't already seen here.  
Note that rebooting doesn't actually fix the Ring plugin for long.  I can change alarm state etc briefly after a reboot, but a couple of hours later it is broken again.  Happy to help with more data as needed.

**Comment by tsightler** [comment]
@markcarroll I'm not really sure why you think the issue you are having is related to this issue when everything you describe is completely different that what is discussed here and in other HOOBS threads.  If you would like help please open a new issue and provide all requested details and full logs.
