### ISSUE TITLE
Does not seem to handle deactivated cameras

### ISSUE THREAD

**Issue by stevehoek** [dgreif/ring#1471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I'm inbetween houses and am only using 2 of my 6 cameras, so I deactivated the others within the Ring app.  Now I see this in my logs

[8/16/2024, 4:58:57 AM] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...

### To Reproduce

Deactivate a camera in the Ring app.  In my case I chose to keep the events so it still shows up in the app/web dashboard as "deactivated"

### Expected behavior

No errors, don't show the camera as a device in Homebridge

### Relevant log output

```shell
[8/16/2024, 4:58:57 AM] [homebridge-ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  fetch failed.  Trying again in 5 seconds...
```

### Homebridge Ring Config

```shell
nothing non-standard, has been working just fine up until i deactivated cameras
```

### OS

Raspbian

### Node.js Version

latest

### NPM Version

latest

### Homebridge/HOOBs Version

latest

### Homebridge Ring Plugin Version

latest

### Operating System

Raspbian

**Comment by tsightler** [comment]
Outside of the log entry, does anything else fail to work?  Overall that message doesn't seem related to cameras being deactivated, it's just a single API call used to retrieve the complete list of all Ring devices, although it is quite difficult to test since I would have to deactivate one of my own cameras.

Could you please enable debug for the plugin and provide complete logs?

**Comment by tsightler** [comment]
Closing due to no response.
