### ISSUE TITLE
Refresh Token becoming Invalid after only a few minutes

### ISSUE THREAD

**Issue by dannyb648** [dgreif/ring#1483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I'm using the recommended auth approach to get a token, storing that token in a .env. That token seems to not last very long at all. I can get one, maybe two uses out of it. 

I can see the API pulling in the valid new token from the .env file - then it uses this to make a call and is successful. I can also see the token changes, as there is a separate process subscribed to the ring.onRefreshTokenUpdated event. Any further calls using this new auth token seems to fail - I then get locked out of getting a new token for 6+ hours. I've added logging so I can see its using the newer token that was just valid. 

I can't see any events being triggered (onRefreshTokenUpdated) isn't being fired off a second time. 

Do token update on every call? I've used the exact code from the wiki to handle the onRefreshTokenUpdated event process.

Any ideas where I can look? Or next steps to debug? 

### To Reproduce

- Create an API Client
- npx -p ring-client-api ring-auth-cli
- Subscribe to ring.onRefreshTokenUpdated and listen for any events
- - if event, update persistence with new token, delete old one. 
- Use auth token to call getCameras - get success
- Use auth token to call getCameras - get Auth error

### Expected behavior

I would expect the auth token to stay valid until a new token is issued and an event fired off. 

### Relevant log output

```shell
karen@KAREN-SERVER:~ $ docker logs karen-api -f

> @karen/api@3.2.0 prod
> node dist/server.js

Ring Doorbell Enabled - Connecting
KAREN API V2 - API Listening on Port: 8080

{"name":"Doorbell Loop",  "_events":{},"_eventsCount":0,"msg":"","time":"2024-08-28T18:51:53.080Z","v":0}
{"name":"Doorbell Loop",  "msg":"Setting up RING API","time":"2024-08-28T18:51:53.083Z","v":0}
{"name":"KAREN",  ,"req":{"method":"GET","url":"/api/doorbells/token","headers":{"x-forwarded-proto":"http","postman-token":"448b447f-fc2a-4581-b4a5-1485fd06c889","accept-encoding":"gzip, deflate, br","accept":"*/*","user-agent":"PostmanRuntime/7.32.3","host":"api:8080","connection":"close"}},"msg":"","time":"2024-08-28T18:51:54.518Z","v":0}
{"name":"KAREN",  ,"msg":"INFO: Verifying token","time":"2024-08-28T18:51:54.539Z","v":0}
{"name":"KAREN",  ,"msg":"Cookies: ","time":"2024-08-28T18:51:54.540Z","v":0}
{"name":"KAREN",  ,"msg":"INFO: Attempting to get auth token from database","time":"2024-08-28T18:51:54.568Z","v":0}
{"name":"KAREN",  ,"_events":{},"_eventsCount":0,"msg":"","time":"2024-08-28T18:51:54.728Z","v":0}
{"name":"Doorbell Loop",  "msg":"EVENT LOOP: Updating Refresh Token","time":"2024-08-28T18:51:54.908Z","v":0}
{"name":"Doorbell Loop",  "msg":"SET UP: Front Door doorbell subscribed to loop","time":"2024-08-28T18:51:54.934Z","v":0}
{"name":"Doorbell Loop",  "msg":"SET UP: Dev Doorbell doorbell subscribed to loop","time":"2024-08-28T18:51:54.935Z","v":0}
{"name":"Doorbell Loop",  "msg":"SET UP: KAREN API V2 - Events Listener Listening","time":"2024-08-28T18:51:54.936Z","v":0}
{"name":"Doorbell Loop",  "msg":"EVENT LOOP: Updated Refresh Token","time":"2024-08-28T18:51:55.151Z","v":0}

{"name":"KAREN",  "level":30,"req":{"method":"GET","url":"/api/doorbells/","headers":{"x-forwarded-proto":"http", "postman-token":"9f6ee2a7-5672-4a65-b3b5-8d1a75912df9","accept-encoding":"gzip, deflate, br","accept":"*/*","user-agent":"PostmanRuntime/7.32.3","host":"api:8080","connection":"close"}  },"msg":"","time":"2024-08-28T18:53:28.087Z","v":0}
{"name":"KAREN",  "level":30,"msg":"INFO: Verifying token","time":"2024-08-28T18:53:28.093Z","v":0}
{"name":"KAREN",  "level":30,"msg":"Cookies: ","time":"2024-08-28T18:53:28.094Z","v":0}

{"name":"KAREN",  "level":30,"msg":"INFO: Attempting to get data from Ring     ","time":"2024-08-28T18:53:28.107Z","v":0}
{"name":"KAREN",  "level":30,"_events":{},"_eventsCount":0,"msg":"","time":"2024-08-28T18:53:28.183Z","v":0}
{"name":"KAREN",  "level":30,"msg":"Connecting to Ring using Auth:  ***QxhA","time":"2024-08-28T18:53:28.184Z","v":0}
{"name":"KAREN",  "level":30,"msg":"INFO: Successfully got data from Ring","time":"2024-08-28T18:53:31.101Z","v":0}


{"name":"KAREN",  ,"level":30,"msg":"INFO: Attempting to get data from Ring     ","time":"2024-08-28T18:55:05.446Z","v":0}
{"name":"KAREN",  ,"level":30,"_events":{},"_eventsCount":0,"msg":"","time":"2024-08-28T18:55:05.551Z","v":0}
{"name":"KAREN",  ,"level":30,"msg":"Connecting to Ring using Auth:  ***QxhA","time":"2024-08-28T18:55:05.552Z","v":0}
{"name":"KAREN",  ,"level":50,"err":{"message":"Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens","name":"Error","stack":"Error: Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens\n    at RingRestClient.getGrantData (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:117:15)\n    at RingRestClient.<anonymous> (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:121:36)\n    at Generator.next (<anonymous>)\n    at /usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:4:12)\n    at RingRestClient.getAuth (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:120:16)\n    at RingRestClient.<anonymous> (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:145:33)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/ring-client-api/lib/api/rest-client.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"},"msg":"Refresh token is not valid.  Unable to authenticate with Ring servers.  See https://github.com/dgreif/ring/wiki/Refresh-Tokens","time":"2024-08-28T18:55:05.836Z","v":0}
{"name":"KAREN",  ,"level":50,"msg":"Handling error for instance 3574d472b7542be2577bb422813e8517","time":"2024-08-28T18:55:05.838Z","v":0}
```

### OS

Linux

### Node.js Version

16

### NPM Version

9.8.0

### ring-client-api

9.23.0

### Operating System

Docker Arm32

**Comment by tsightler** [comment]
One step would be to use something way newer the 9.23.0, latest version is 13.1.0.  Nothing that old has been tested in a very long time and there are many updates to token handling due to changes in Ring API.

Changes to the token while the connection is active should not matter, the token is automatically updated in-memory and you don't need to care about this.  The consuming code must monitor onNewRefreshToken so that it can save these new tokens for a future new connection. 

You didn't share your code, just some random logs that only you can understand (clearly not from ring-client-api).  Attempting to interpret your logs in the absence of other information, it appears to show new connections, but it's not at all clear why you keep reconnecting to Ring.  This is not required, once the API client is connected, you can just reuse the connection without concerning about the token.

Your example was this:

- Create an API Client <-- Not sure how you are creating an API client without already having a token
- npx -p ring-client-api ring-auth-cli
- Subscribe to ring.onRefreshTokenUpdated and listen for any events
- if event, update persistence with new token, delete old one.
- Use auth token to call getCameras - get success
- Use auth token to call getCameras - get Auth error

But to me the flow is more like this:

- npx -p ring-client-api ring-auth-cli - get a token and store it in the persistent file
- Create an API Client using token from persistent file
- Subscribe to ring.onRefreshTokenUpdated and, on new event, replace the token in the persistent file
- Use API client and getCameras - get success
- Use API client and getCameras - get success

If at any point the connection is closed, create a new API Client using the last token saved in the persistent file, that is all.

A new token will be generated every time you make a new connection, but that should not matter as you should only need to make a new connection if the prior code has existed.

**Comment by dannyb648** [comment]
@tsightler Thanks for your feedback and insight

You were right, the issue was I was creating a new ring client for each request. I guess this isn't the correct pattern. I'll raise a PR with a note for the Wiki to make this more explicit. 

The fix for me was to add a now InitRing function which called the RingAPI class at start up and then a getter for whenever I actually wanted to use it. 

Didn't need to upgrade the version (although I will!) 

Appreciate the help!
