### ISSUE TITLE
Repeating Error Message in Log

### ISSUE THREAD

**Issue by MichaelMLevin** [dgreif/ring#1509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I keep seeing an "UNKNOWN MESSAGE" error followed by what appears to be a codec mismatch error in the HomeBridge log.  I'm not sure it's an actual bug, but wanted to let you know it was happening.  It seems to happen when there is a motion detected event at one of the cameras.

### To Reproduce

It seems to happen when a motion detection event is triggered.

### Expected behavior

I don't expect to see errors in the log.

### Relevant log output

```shell
[10/16/2024, 10:49:21 AM] [homebridge-ring] UNKNOWN MESSAGE
[10/16/2024, 10:49:21 AM] [homebridge-ring] {
  body: {
    doorbot_id: 562525260,
    session_id: 'eyJraWQiOiJTaWduYWxsaW5nIiwiYWxnIjoiSFMyNTYifQ.eyJkaW5nX2tpbmQiOiJvbl9kZW1hbmQiLCJkb29yYm90X2lkIjo1NjI1MjUyNjAsInBpbmdfaW50ZXJ2YWwiOjEwLCJkaW5nX2lkIjoiNzQyNjQzMjA3MDk0OTc2MjEyNCIsImlwIjoiMTAwLjIxLjE3OS4zOSIsImNyZWF0ZWRfYXQiOjE3MjkxMDA5NTkyOTUsInJtc19mcWRuIjoiMTAwLTIxLTE3OS0zOS4wNzA0MjQwMzM0NDcudXMtd2VzdC0yLnByb2Qucm1zLnJpbmcuZGV2aWNlcy5hMnouY29tIiwic2Vzc2lvbl9pZCI6ImI2ODk5OTRmLThiNGYtNDc4MC1iNzFmLTk2NjRlYmMyMDZlZiIsImV4cCI6MTcyOTE4NzM1OSwiaWF0IjoxNzI5MTAwOTU5LCJybXNfdmVyc2lvbiI6IjhhMTI1YjBmIn0.JzrG-7-bDe9uZadHV27zHcSh_dzEWNXZSTPvORKlcL8',
    transcoding: true,
    transcoding_reason: 'codec_mismatch'
  },
  dialog_id: 'a5ba748b-ac3a-4e5a-8267-8bd29e29b100',
  method: 'stream_info'
```

### Homebridge Ring Config

```shell
{
    "refreshToken": "*******************************In19fQ==",
    "platform": "Ring",
    "_bridge": {
        "username": "0E:8D:B4:3A:95:04",
        "port": 59474
    }
}
```

### OS

Linux

### Node.js Version

 v20.17.0

### NPM Version

v9.2.0

### Homebridge/HOOBs Version

v1.8.4

### Homebridge Ring Plugin Version

v13.1.0

### Operating System

Ubuntu

**Comment by tsightler** [comment]
@MichaelMLevin For future reference, there are [discussions groups](https://github.com/dgreif/ring/discussions) where you can ask questions without opening an issue.  Something like this would be appropriate there since you state 

In general, there are many messages sent on the websocket that we don't know about today, mostly because we do not need or cannot use the information (for example, the birds eye view sends coordinate data which the Ring app uses to plot the dot on the image).  The exact messages differ based on camera capabilities, etc.  We log them just because they might be useful in the future if a user experiences some kind of functional issue.  You can happily ignore these messages if you have no functional issues.

@dgreif As there seem to be a lot more of these messages these days vs in the past, maybe we should consider logging them only if debug is enabled as this is the second or third time users have opened issues about this.  Thoughts?

**Comment by dgreif** [comment]
I saw these over the weekend and was planning to add them to the list of messages we handle (but ignore). I'll add that to the current beta branch when I get a chance
