### ISSUE TITLE
Notification issue

### ISSUE THREAD

**Issue by dpamping** [dgreif/ring#1546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

I dont get notifications when the doorbell is pressed

### Expected behavior

A ring notification should appear and HomePods should make the ding sound. Ive already tried the notification issue wiki

### Relevant log output

https://api.ring.com/clients_api/doorbots/382729485/motions_subscribe
15/12/2024, 19:28:08Ring BridgeRingERRORFailed to subscribe Timbre to motion events
15/12/2024, 19:28:08Ring BridgeRingERRORError: Not found with response: {"status":404,"error":"Not Found"}

15/12/2024, 19:28:09Ring BridgeRingERROR404 from endpoint 
15/12/2024, 19:28:09Ring BridgeRingERRORFailed to subscribe Timbre to ding events
15/12/2024, 19:28:31WARNINGplugin site unavailable
```


### Screenshots

_No response_

### Homebridge Ring Config

```shell
{
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "refreshToken": "(the refresh token)",
            "hideAlarmSirenSwitch": true,
            "cameraDingsPollingSeconds": 1,
            "hideInHomeDoorbellSwitch": true,
            "hideDoorbellSwitch": true
        }
    ]
}
```

### OS

Hoobs

### Node.js Version

16.19.1

### NPM Version

-

### Homebridge/HOOBs Version

4.3.0

### Homebridge Ring Plugin Version

12.1.0

### Operating System

Hoobs

**Comment by tsightler** [comment]
You are running 12.1.0 version of the plugin which is outdated and cannot receive push notifications due to the migration to FCM v1 APis which happened this summer.  This is one of the main reasons that 13.x versions of the plugin exist.

Unfortunately, you are on outdated HOOBS, which has outdated NodeJS and can't run newer versions of the plugin.  You will need to upgrade to HOOBS 5.x, which was released in the last month.  I would highly recommend contact HOOBS support as there are a lot of issues with the HOOBS upgrade, however, if you can upgrade successfully, you will be able to run the current version of the plugin and push notifications will work again.

Closing for now as it's fully expected that 12.x will not work anymore.
