### ISSUE TITLE
Notification from Lockscreen

### ISSUE THREAD

**Issue by tr1um9h** [dgreif/ring#1548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

When holding notification from lock screen, larger version of the snapshot does not show.

### Expected behavior

Should show larger image of snapshot

### Homebridge Ring Config

```shell
{
            "refreshToken":"",
            "unbridgeCameras": true,
            "hideCameraSirenSwitch": true,
            "hideAlarmSirenSwitch": true,
            "debug": false,
            "cameraStatusPollingSeconds": 5,
            "platform": "Ring"
        }
```

### OS

Raspbian

### Node.js Version

v20.18.0

### NPM Version

v10.9.0

### Homebridge/HOOBs Version

v1.8.5

### Homebridge Ring Plugin Version

v13.2.1

### Operating System

Raspbian

**Comment by tsightler** [comment]
As far as I can tell, this is an Apple bug as it has been reported with many different cameras.  What iOS version are you running?  In the end, there's not much to it from a plugin perspective, we just send the event and snapshot, it's up to Homekit what to do with it.

**Comment by tr1um9h** [comment]
18.2

**Comment by tsightler** [comment]
I started seeing reports of this on Reddit even during 18.2 betas, but not just with Ring cameras, and now there are multiple reports of this with all different kinds of cameras since 18.2 has been out, so I feel like this must be an iOS issue.  The plugin itself doesn't do much here, camera simply generates a motion event and responds to the Homekit request for a snapshot, the plugin doesn't generate or send the notification.

**Comment by tsightler** [comment]
I'm going to close this for now as I don't believe this is related to this plugin, appears to be a Homekit bug in latest iOS releases.  Hopefully Apple will address it.  If you have proof otherwise, I'm open to it, but the fact that this seems to be happening for many users across different camera platforms would tell me it is not an issue with the plugin.  The plugin does not actually send the notification anyway.
