### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by nuketownhf** [dgreif/ring#155]
Hello,
if I run node scriptname.js
it gives me
import { RingApi } from 'ring-client-api'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

thanks

**Comment by smockle** [comment]
You have a few options:

### A. Use TypeScript

First, install dependencies:
```sh
npm install --save-dev typescript @types/node @types/socket.io-client
```

Then, create a `.ts` file, like this:
```TypeScript
// index.ts
import { RingApi } from 'ring-client-api'
console.log(RingApi)
```

Next, compile the `.ts` file to create a `.js` file:
```sh
npx tsc index.ts
# will output an index.js file
```

Lastly, run the compiled JavaScript file:
```sh
node index.js
```

### B. Use Node.js’ (experimental) module support

Note: This [requires Node.js 8.9.0](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff) or newer. Check your Node.js version with `node --version`. If you need to update, there are links with instructions [the Node.js downloads page](https://nodejs.org/en/download/).

Create an `.mjs` file, like this:
```JavaScript
// index.mjs
import Ring from 'ring-client-api'
console.log(Ring.RingApi)
```

Run the JavaScript module using [the `--experimental-modules` flag](https://nodejs.org/api/esm.html#esm_enabling):
```sh
node --experimental-modules index.mjs
```

### C. Use [`esm`](https://github.com/standard-things/esm)

First, install dependencies:
```sh
npm install --save esm
```

Then, create an `.mjs` file, like this:
```JavaScript
// index.mjs
import Ring from 'ring-client-api'
console.log(Ring.RingApi)
```

Next, create a `.js` file, like this:
```JavaScript
// index.js
require = require("esm")(module)
module.exports = require("./index.js")
```

Lastly, run the `.js` file:
```sh
node index.js
```

### D. Use [`babel`](https://babeljs.io/docs/en/babel-cli)

First, install dependencies:
```sh
npm install --save-dev @babel/core @babel/cli @babel/preset-env
```

Then, create a `.js` file, like this:
```JavaScript
// source.js
import { RingApi } from "ring-client-api";
console.log(RingApi);
```

Next, transpile the `.js` file:
```sh
npx babel source.js --out-file index.js --presets=@babel/preset-env
```

Lastly, run the transpiled JavaScript file:
```sh
node index.js
```

### E. Use `require` instead of `import`

Create a `.js` file, like this:
```JavaScript
// index.js
const Ring = require("ring-client-api")
console.log(Ring.RingApi)
```

Run the `.js` file:
```sh
node index.js
```

**Comment by nuketownhf** [comment]
Hello, thanks for your quick response
im a total noob at Typescript, what I'd like to achieve is a notification system
I have 4 Ring Devices and I'd like a print output if I press on the device button than It will print "NAME OF DEVICE has been activated"
thank you very much.

**Comment by smockle** [comment]
> I have 4 Ring Doorbell Devices and I'd like a print output if I press on the device button than It will print "NAME OF DEVICE has been activated"

@nuketownhf I’d recommend checking out [`examples/example.ts`](https://github.com/dgreif/ring/blob/master/examples/example.ts), which does something similar to that.

This is based on `example.ts` and may be a helpful start:
```TypeScript
import { RingApi } from '../api'
;(async function() {
  const ringApi = new RingApi({
    email: 'RING_EMAIL', // Replace RING_EMAIL with your email address. Keep the single quotes.
    password: 'RING_PASSWORD', // Replace RING_PASSWORD with your password. Keep the single quotes.
    refreshToken: 'RING_REFRESH_TOKEN', // If you use two-factor authentication, replace RING_REFRESH_TOKEN with a token obtained by following the instructions here: https://github.com/dgreif/ring/wiki/Two-Factor-Auth. Keep the single quotes.
    cameraDingsPollingSeconds: 2
  })
  const cameras = await ringApi.getCameras()
  if (!cameras || !cameras.length) {
    return
  }
  cameras.forEach(camera => {
    camera.onNewDing.subscribe(ding => {
      if (ding.kind !== 'ding') {
        return
      }
      console.log(`${camera.name} has been activated`)
    })
  })
})()
```

Depending on what you mean by “print output”, you may also be interested in something like [`node-notifier`](https://www.npmjs.com/package/node-notifier) in place of the `console.log`.

**Comment by dgreif** [comment]
@smockle thanks for the detailed response!  @nuketownhf do you need any additional info to get up and running?

**Comment by nuketownhf** [comment]
I'm glad you guys helped me,
thank you!
