### ISSUE TITLE
Docs need to show how to get device faulted (sensor open or closed) notification

### ISSUE THREAD

**Issue by geetee24** [dgreif/ring#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe The Bug

1. how get current value
2. do i poll or get notified?
3. Docs need to show how to get device faulted (sensor open or closed) notification

### To Reproduce

none

### Expected behavior

please document the answer

### Relevant log output

```shell
none
```

### Additional context

none

### OS

Node

### Node.js Version

20.1.1.

### NPM Version

v8.0.0

### ring-client-api

latest

### Operating System

Windows

**Comment by tsightler** [comment]
This really is not a bug and I would ask that you not open bugs to ask basic questions, the discussion forum is a more appropriate place for such questions, this exact topic is already discussed, and answered, at https://github.com/dgreif/ring/discussions/1021.

Finding and subscribing to data updates for any device is [covered in the readme](https://github.com/dgreif/ring/tree/main/packages/ring-client-api#devices) and there is an entire project in this repo that provides a nice reference if you want to see examples for individual sensor types, that is by far the best reference.  ChatGPT or other AI tools can also write a simple script if you give it this question, so that should be enough to get your started.
