### ISSUE TITLE
iOS 13 Ring Doorbell notifies, then goes straight to Live stream

### ISSUE THREAD

**Issue by rjoung** [dgreif/ring#158]
@dgreif Thanks very much for creating this plugin, working perfectly with 2Gb RaspberryPi 4 running Raspbian.  Rings installed are a Doorbell 2 and a Spotlight cam.

On iOS 13 on iPhone and iPad, motion detection and doorbell ring shows a notification preview image to the right most times (>50%), but switching to Home app by tapping the notification goes to Live view without ability to examine the triggering image.  Is this by design?  Do I need to update something?

**Comment by dgreif** [comment]
You can force touch (or maybe long hold depending on the device) on the notification to open a larger view of the image.  This behavior is all driven by HomeKit and iOS and there is no customization possible from the plugin side. iOS 13 added a lot of changes to HomeKit and how it behaves, so that may be cause it to behave differently if you are coming from iOS 12.
