### ISSUE TITLE
Thank you and quick question

### ISSUE THREAD

**Issue by privatesam** [dgreif/ring#160]
Thanks for this amazing work I've been playing with it today with a view to including some of your code for my own internal camera monitoring purposes.  At the moment I'm using one of the examples .ts files to run a node express web server and stream the video to elsewhere on my network.  I note that in the code there's a timeout built in and in the example its set to 5mins.  Can you foresee an issue with changing this timeout and running the video stream indefinitely - specifically do you think Ring's servers will pick this up and block anything?  I don't want to ruin this amazing solution for homebridge by smashing Ring's api and having them turn something off.

Thanks again.

**Comment by dgreif** [comment]
I do think there is a good chance Ring will catch on to that situation.  I can't say for sure, but I think I recall someone else mentioning they got blocked for something similar several months ago.  There is also a good chance the video will get disrupted at some point and might not recover gracefully.  In general, Ring's streaming setup is really designed for short clips rather than indefinite streaming.  Hopefully some day we can stream everything on-premise, but for now everything has to go through Ring's servers 😞
