### ISSUE TITLE
No notifications. 

### ISSUE THREAD

**Issue by black01gt** [dgreif/ring#166]
Not sure what happened, but out of the blue I no longer get notifications. All settings are set to on and I get them through the ring app. Did something change? Snapshots populate and I get live video with audio.

**Comment by jasonhnz** [comment]
I have the same issue. all devices running iOS 13.2 (although I'm sure the notifications were working for a few days after upgrade) . I had notifications just stop from yesterday.

**Comment by black01gt** [comment]
Thats about the time mine started acting up. I have been on the developers Betas since they came out. Everything has worked fine. Looks like it is random. Last night I ended up getting 2 notifications out of the 20+ visits from kids.

**Comment by dgreif** [comment]
I can confirm that my doorbell isn't giving me homekit notifications, but all my other cameras are (floodlight, stickup cam).  I looked into it a bit and it seems like Ring is no longer giving us the motion events via the `dings/active` endpoint that we use to grab events, but only for doorbells.  I have no idea why they would have changed that functionality, but hopefully it's just a bug and they get it fixed soon.  I don't think there is anything I can do on my end to fix it, but I'll keep this issue open for others to see who are having issues.  Please just give a thumbs up if you are having this issue, rather than posting tons of messages on this thread 🙇

**Comment by dgreif** [comment]
I just received a motion event from my doorbell, so maybe it's working again 😕 .  Let me know if yours start working as well

**Comment by odenisenko** [comment]
hello from python devs  :)
on;y ring events here.

**Comment by jasonhnz** [comment]
I noticed just over a week ago, the ring app allowed for a new feature to link devices together so you could trigger events across some or all of your ring devices..maybe the protocol has changed to allow for this?

**Comment by black01gt** [comment]
Not working for motion or ring on any of my devices.

**Comment by black01gt** [comment]
Loooks like I may be back up and running. Notifications working for everyone else to?

**Comment by jasonhnz** [comment]
I had a notification today for the ring door bell but no motion alerts at all for any spotlight cams for about 3, 4 days now

**Comment by dgreif** [comment]
@jasonhnz try restarting you HomeKit home hub (Apple TV or iPad). All my notifications seem to be working again

**Comment by odenisenko** [comment]
can close.  Ring played enough! :)
all events have returned

**Comment by jasonhnz** [comment]
@dgreif It was a few hours after your post but yes, all my notifications are back.!

**Comment by dgreif** [comment]
Thanks for the input everyone, I'm glad Ring got it straightened out!! 🎉

**Comment by codahq** [comment]
Has anybody noticed issues with this again yesterday and today?  I really hope that Ring is not testing an optimization to not create call events until they are needed/opened/clicked-thru from a notification.  All night long I have been noticing for several of my devices no motion events being created under the "dings/active" endpoint.

**Comment by jasonhnz** [comment]
I experienced this behaviour 2 weeks where I lost events and device status (battery life etc..) for about 4-5 days. And then it all just came back.... It has been fine since. Hopefully it comes back to you soon.

**Comment by codahq** [comment]
Device status, battery life, etc. don't come from the "dings/active" endpoint.  The only thing that comes from there is call event information that we use for ring and motion notifications.  The response is just coming back empty.  Everything else works fine.  @dgreif, are you seeing issues again?

**Comment by dgreif** [comment]
@codahq all of my active dings appear to be working as expected.  It was definitely an issue on the Ring side when this popped up two weeks ago, but I'm not seeing the same issue now.  Are you having issues with the homebridge plugin, or in your Hubitat setup?  If it's on the Hubitat side, make sure you are including a unique `hardware_id` header in your `dings/active` request that ties to a session.  If you don't supply the `hardware_id`, then dings come from some shared pool that can be emptied by any request for active dings.

**Comment by codahq** [comment]
In Hubitat or Postman with `hardware_id` or not.  Tried moving `hardware_id` to the header of the session request just in case it mattered.  It's always been in the body of the session request.  Neither place changes the result.

`hardware_id` is part of the headers in the `dings/active` request.  Motion events for doorbells are there.  Missing for at least a couple of Stick Up Cams and probably more.  I've only looked/tested the indoor Stick Up Cams because they're easiest to get to and trigger motion events.

**Comment by dgreif** [comment]
Yeah, that's really odd.  From what I remember, your setup sounds correct.  `hardware_id` in session body, and in headers for all other requests.  Motion events seem to be working for all my cameras including a battery stick up cam

**Comment by codahq** [comment]
I have a feeling that my hardware is partially migrated across a testing initiative and maybe all of the servers aren't playing together nicely.  I have that feeling because my shared user can't see half of our devices right now either.

**Comment by b5rt** [comment]
Well, I just took my out and got my first motion notification from my Doorbell Pro. So, something changed since last night. 

Just for some discussion - somebody mentioned the possibility that Ring is testing an optimization to not pass the events through the dings/active endpoint and only serve them up when requested after a notification. I assume that the Ring app gets notifications through the Apple push notification service, so I think that would be feasible. However, I’m wondering how notifications work with the chime. I don’t know if they happen locally over WiFi, or if they come through on the dings/active endpoint. If it’s the latter, they wouldn’t be able to do that optimization for anyone using the chime. Maybe that explains why some people seem to get neither motion nor rings and others get only rings.  I assume most people who have the chime only have them setup to alert on rings and not motion like I do, so only rings would need to be sent. 

I could be way off, but it was something I was thinking about in bed last night. I was going to try to test it this morning, but then I realized it fixed itself for the time being. So, I guess my question is - do any of you have chimes?

**Comment by codahq** [comment]
@b5rt I have chimes but I've never put a MITM in between one and the internet.  I doubt that they poll this endpoint though unless they are absolutely hammering it.  More than likely they subscribe for callbacks similar to our phones' notifications services.

The one thing that we can rely on is that no matter what the cameras always create the call to upload the video to the cloud.  They can't get rid of that unless they change the firmwares drastically and move away from SIP calling.  Because of that it's likely that the call information gets put in the active dings endpoint because the call already exists and they can't optimize the call away.  The only thing they could optimize would be not putting the call information on the end point.  To me that doesn't seem like it would be worth it so hopefully what we're seeing is just bugs or, in my case, a testing scenario.  

I tried resetting my hardware ID and it helped.  I haven't checked if I'm still getting notifications but after I reset my hardware ID I did at least start getting them from the end point.

**Comment by dgreif** [comment]
@codahq I agree it's unlikely that they are polling the endpoint.  I'm guessing they are either registering a local ip/port for callbacks or using long-polling (which would work great in this scenario).  Either way, getting an idea of what endpoints they are hitting would be a huge help.  I ordered a chime this morning and will try out a MITM when it gets here tomorrow.

Good idea on resetting the hardware id.  With the homebridge plugin, I currently have the hardware id locked based on the machine id of the computer.  I did this specifically because too many new sessions (aka hardware ids) were causing Ring to log out other sessions (for example those of the app on your phone).  It might be worth it to let a new session to be created occasionally, say once a weeks or so.  I have no idea what their thresholds are so I'm just guessing here

**Comment by b5rt** [comment]
Great discussion. I was thinking along the same lines as you two. Even if they aren't using the same mechanisms you are, the chime must be using *something* to receive events and it isn't the Apple notification service, so maybe observing what they're doing would result in something that could be used by the plugin.

I wish I could be of more help, but this stuff is a bit outside my wheelhouse. I write code for a living, but I'm at the bare-metal firmware level in micro controllers so I have a very rudimentary understanding of server communications. If there's any testing to be done or any data you think I might be able to provide, please let me know and I'll do my best to contribute.
