### ISSUE TITLE
Supporting Amazon Key Locks

### ISSUE THREAD

**Issue by issues-guy** [dgreif/ring#178]
I have added a lock to Ring which can only be added via Amazon Key. When using the ring homebridge plugin the Lock did not appear in the list of devices. Is this the expected behavior currently?

Running on homebridge-ring v5.9.1

If it is not currently supported, I do hope it can be added. I am available to assist with testing as well.

Thanks!

**Comment by dgreif** [comment]
I _might_ be able to support it with the plugin, but it's going to be difficult to add it without having one to test with.  The first step to see if it's possible would be to see if Ring shows the lock in the web app.  Go to ring.com then log in to your account.  Hover over your name in the top right and click on "Devices" in the drop down.  Do you see the lock listed in that list of devices?  If you have an alarm, you may need to click into the alarm device and see if it's listed in there.

**Comment by issues-guy** [comment]
Nope, the lock is not listed anywhere.   : (

**Comment by dgreif** [comment]
K...unfortunately that makes it really hard for me to implement it.  If it shows up in the web app, then I can look at the code and reverse engineer it.  Without that, I would have to have one on hand to test with.  What model of lock is it?

**Comment by issues-guy** [comment]
Schlage Encode

**Comment by enriquecaballero** [comment]
I just added my August Lock and it does show up on the webapp. Any chance this one might work?

**Comment by enriquecaballero** [comment]
Nevermind, it just worked. Awesome.

**Comment by dgreif** [comment]
Interesting, how did you connect your August lock to ring?

**Comment by enriquecaballero** [comment]
I tried pairing it like any other z-wave device and it just worked: it found the device, prompted for the code, and it added it successfully. Figured I’d give it a shot since I was also able to successfully pair my HomeSeer light switches and dimmers. No official support but hey, it works.

**Comment by dgreif** [comment]
@enriquecaballero that's awesome, I may have to give that a try!  I've been using the native HomeKit support for my August locks, but it seems slow to respond most of the time.  Might work better with a straight z-wave connection 🤔.  @issues-guy sorry this doesn't fix your Amazon Key issue.  I haven't seen anything in the web app source code that would help me get that working with HomeKit yet.

**Comment by enriquecaballero** [comment]
@dgreif I used to use the straight up HomeKit connection but I also ran into a bunch of connectivity issues. Turns out it’s because it relies on a direct Bluetooth connection from your hub (Apple TV, iPad, etc.) to the lock. Even using the August Connect, it still used Bluetooth...so dumb. So I shut off HomeKit and enabled z-wave and it’s been solid since. I used to run Hass for controlling my lights and lock, and now I’ve moved everything over to Ring — everything’s been rock solid and much more responsive since.

**Comment by dgreif** [comment]
I still have not purchased (and don't intend to purchase) an Amazon Key compatible lock.  Since Ring handles these locks in a completely different way than the z-wave locks, I don't think I will be able to implement this feature myself.  If anyone happens to have a compatible lock and is able to figure out how the API works for them, I would be happy to take a PR!

**Comment by dxdc** [comment]
@enriquecaballero I have had similar issues with August and trying Zwave. Do you have DoorSense? I'm curious if DoorSense is exposed through the ring platform. If so, I might be convinced to take a crack at this :)

**Comment by dgreif** [comment]
I'm going to close this issue for now.  I don't really want to buy an Amazon Key lock to build this feature and from what I have seen of the API, it would require more polling to keep the lock state up to date.  If anyone has an Amazon Key lock and is able to open a pull request with at least an API setup, I would definitely consider adding this in the future.
