### ISSUE TITLE
Ring flood sensor notification

### ISSUE THREAD

**Issue by techoin** [dgreif/ring#180]
Thanks @dgreif for this awesome plug-in. It has come long way.

I am the one who requested #83 if you recall. I have similar request. I recently added Aqara water leak sensors as they were homekit compatible and cheap. I am looking to see if it's possible to expose Ring Alarm flood sensor notification. So I can trigger Ring notification whenever my Aqara water leak sensor is triggered.

Below is what Ring sensor triggering does from Ring website FAQ

**Flood & Freeze Sensor:**Your primary contact will receive an automated call from the monitoring center. If the primary contact doesn't answer the phone, the second emergency contact will receive an automated call.

**Comment by dgreif** [comment]
@techoin it's great that you are expanding your devices, but unfortunately I won't be able to add the feature you are requesting.  If the flood sensor isn't compatible with Ring, then I don't think I can trigger their flood sensor alarm.  Fire/Burglary are already supported, but those are features that are specifically exposed through the Ring app and could be reverse engineered.  Since there is no way to trigger the flood alarm from the app, I can't reverse engineer it.  I'd suggest buying a Ring compatible sensor since this plugin will allow it to show up in HomeKit.  Good luck!
