### ISSUE TITLE
Stickup Cam Siren switch not working (no sound)

### ISSUE THREAD

**Issue by jasonhnz** [dgreif/ring#185]
I'm pretty sure this used to work when I first added my ring devices to homebridge.
Tried again now as part of a scene to activate on other motion trigger events but the siren does not make any sound. 

Toggling the switch on the home app manually does not trigger the siren either. (Within the ring app, the only way I can get the siren to work is if I activate it when live mode is active as well) 

Is this expected behaviour? and does this happen to everyone else?  Has something changed ?

**Comment by jasonhnz** [comment]
Ill add, that the switch for the light works OK.
battery status however is always stuck on 100%. Not sure if this is indicative of some wider problem.

**Comment by dgreif** [comment]
Thanks for reporting @jasonhnz.  Looks like Ring may have changed the API for the siren a bit.  I'll look into a fix when I get a chance.

**Comment by jasonhnz** [comment]
Thanks @dgreif Will look forward to it as wanting to use the sirens as an action for other motion sensors as well.

**Comment by dgreif** [comment]
@jasonhnz can you try the siren again?  It seems to be working fine for me now, which indicates it may have been a bug on Ring's end.

**Comment by jasonhnz** [comment]
No luck I’m afraid.

Although I’ll wait a day or so as the last time the notifications stoped (and then resumed) I noticed there was some lag before mine started to work again.

Will update in a day or so.

On 17/12/2019, at 12:46 PM, Dusty Greif <notifications@github.com> wrote:

﻿

@jasonhnz<https://github.com/jasonhnz> can you try the siren again? It seems to be working fine for me now, which indicates it may have been a bug on Ring's end.

**Comment by dgreif** [comment]
@jasonhnz I did some more testing and confirmed that this is an issue from Ring.  Specifically, it seems that _battery_ powered cameras only allow you to turn the siren on while live streaming.  Wired cameras (like the floodlight cam, which is what I used to test before my last comment) allow you to turn on the siren any time, regardless of whether or not you are live streaming.  I confirmed that this behavior is identical between the Ring app and HomeKit, so unfortunately there is nothing else that I can do at this point.  Just wish Ring would stop breaking their own stuff 😞

**Comment by jasonhnz** [comment]
Hi @dgreif Thought id open this again as today in the Ring app, I noticed it has an individual Siren button in the settings screen (or by the settings menu popup) which allows you to set the siren off without having to go into live view. 

I wonder if this means it would now be possible to have this is an individual switch state within the home app?  Thoughts?

**Comment by dgreif** [comment]
@jasonhnz the cameras _do currently_ have a siren switch.  If you are unable to find it, it's most likely because the siren switch is grouped with the camera, and you have to go into the accessories within the camera (this is a Home App feature.  You can ungroup the switch from the camera if you choose).  As I stated before, battery cameras appear to only activate the siren if a live feed is currently active.  I just tested it from the Ring app and confirmed that my stickup cam (battery) does not actually turn on  the siren if I hit the siren button on the settings page without an active live view. There is nothing else I can do to fix this on my end.

**Comment by jasonhnz** [comment]
@dgreif I understand the old constraint. My comments was if this had changed as the ring app had updated for me in the last week where the Siren button is an actual seperate button (not sure if this has always been the case for you) in the ring app (not HomeKit - which it is listed there too as a seperate tile) but next to the live view button on the main device page there is a red siren button. For me anyway, tapping this button (while not being or have been in live view) turns the siren on. Because the siren can then be activated while not in live view is while I thought they may have changed the functionality in the backend under a new api or change to existing one. (NOTE that pressing the seperate tile button in HomeKit still does not work but maybe thats because there is a new way of doing this?) - Just thought id check to see if worth investigating.

**Comment by dgreif** [comment]
@jasonhnz I see the button you are talking about on the settings page for my stickup cam.  Oddly enough, pressing that button does not actually activate my stickup cam alarm.  I'm guessing nothing has changed on the backend, unless you have some newer firmware on your stickup cam compared to mine.  I'll keep an eye on it and see if mine starts working without a live stream

**Comment by Sistaveley** [comment]
@dgreif Hi Dusty, just been looking for an existing issue and this one from a while back seems to be pretty close. I have got Ring and Homekit working great and even managed to set up a schedule to automatically turn off the chimes for any motion past 7pm as otherwise in Ring app, you have to do them all one by one!! Painful, especially when you have young children going to bed and then the chime goes off!! 

So to this thread, I have a stickup cam and on the settings page I have the Siren button as Jason and you noted back in 2020. Similarly when you go to Live View, you also get the Siren button. However in both cases there is a further step to activate it - basically a button choice to confirm that yes you want the siren to go off. Is this what is blocking a simple trigger for this to be coded, like the switch to turn chime on/off?

**Comment by tsightler** [comment]
@Sistaveley I'm not clear on what you mean, the switch is already coded and is available in Homekit.  It's just that, for battery cameras, the siren will not sound unless there is an active live view.  The confirmation you are speaking to is just a popup in the Ring app and comes up for all cameras, even line powered Stickup Cams and Floodlights, but that has nothing to do with the API, it just pops up any time the siren is activated.

**Comment by Sistaveley** [comment]
Thanks @tsightler for your response. I have three switches visible in HomeKit, one for chime, one for motion and one for ring. So I am able to set a schedule e.g. to turn off the chimes at 7pm in the evening so the children don’t get woken up. However what I am trying to work out is whether I can trigger the stickup cam to play the siren if there is movement during the night. We have a fox that has started coming into our outhouse and the siren seems to scare him. Currently I need to be awake and catch the movement notification and then go in and press to activate the siren. 
Could you confirm if that is at all possible to do? Sorry if I wasn’t clear in my explanation. Hope that helps thanks!

**Comment by tsightler** [comment]
If you click the camera to bring up live view and then click settings, you should see at least two accessories associated with the camera, one will be a siren switch.  You can select them and choose to have them appear on the main Home page (this is all basic Home app stuff).  I'm just not sure if this switch will work on battery cameras when there is not a live stream active as that's what this thread is about, but it is old.  For my stickup cams, it works, but I have all line powered devices.
