### ISSUE TITLE
Timer for Floodlight Camera Lights

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#196]
I don’t know if I am the only one of if anyone else has experienced this. But my lights will come on from a HomeKit automation, on the floodlight camera,and will not turn off. This could potentially be a iOS 13 bug, but it’s the only light that does it. So wondering if it is possible to add a configuration like you have for smart lights that would work on the Smart Camera Lights?

**Comment by dgreif** [comment]
The difference is that the Smart Lights are designed by Ring to work on a timer.  I think it's because most of them are battery powered so they don't want you to forget that they are on.  The Floodlight Cams, however, are wired and don't need that same restriction.  I think the Eve HomeKit app gives you some more in-depth automation options, including turning a light on for x amount of time.  Give that a try and let me know how it goes.

**Comment by d0n4v4nb3ck3r** [comment]
still staying on.

**Comment by d0n4v4nb3ck3r** [comment]
even though the smart lights are designed to work on timer. Is there anyway to implement a timer into the plugin that would restrict them from being on longer then so may minutes?

**Comment by d0n4v4nb3ck3r** [comment]
Set a automation so that if Motion isn’t detected it turns the light off... and it is actually working!!
