### ISSUE TITLE
Video Stream Pauses every 2-3 seconds

### ISSUE THREAD

**Issue by JazzerAlto** [dgreif/ring#201]
I have 3 Ring flood light cams and a Ring Pro.  RPI 3B running HOOBS.  Video quality on the home app looks identical to the Ring app however, I get a slight pause or hesitation of the video stream every 2-3 seconds inside the home app.  I don't see it all on in the Ring app, completely smooth.  Is this a SW issue or the 3B?  My CPU never goes above 20% on the RPI.

**Comment by dgreif** [comment]
The RPI's job in video streaming is pretty simple.  It just passes incoming stream packets from the ring servers along to your Home hub (Apple TV, iPad, HomePod) and then Apple does the rest.  If you are having issues with stream quality, it is _most likely_ a network issue, rather than a HW issue.  I run mine on a 3B+ and have no issues at all.  You should think through the network links between your router -> rpi -> router -> home hub -> router -> iphone and eliminate any of those links that may be slowing down the stream.

**Comment by JazzerAlto** [comment]
What is curious is if I look at a stream with the ring app on the same device, I don’t see any of the pausing.  If it was a network issue, wouldn’t that show there too?

**Comment by JazzerAlto** [comment]
Also, to add.  My Circle cam doesn’t show this either.
