### ISSUE TITLE
Video stream from Ring Elite only working occasionally

### ISSUE THREAD

**Issue by attermann** [dgreif/ring#212]
First off, kudos to dgreif for the great module. Really impressive what it can do.  I am using the homebridge-ring module and have my doorbell setup and am receiving snapshots just fine.  When I click the snapshot to bring up live video however, most of the time I get the spinning wheel followed by "No response. This camera is not responding".  Looking at the RTP from a pcap, the stream from Ring to homebridge looked fine but the stream from homebridge to the device would sometimes go to my homekit hub (AppleTV), and other times directly to my device (iPhone 8).  When the stream is sent to my hub it works and i can view it on my iPhone, but when it is sent directly to my iPhone it does not work and the aforementioned error occurs.  I plan to dive into the code and see what I can find, but figured I'd mention it here first in case there's something I'm missing, or perhaps someone can point me in the right direction.

Thanks.

**Comment by dgreif** [comment]
@attermann thanks for the detailed report.  Unfortunately it sound like the issue is on the HomeKit side.  Streaming to the AppleTV vs directly to the iPhone should behave exactly the same, as the plugin simply receives an IP address which it should send the stream to.  The only issue I can think of is that we don't convert the video stream into the exact resolution that is requested by the phone, but I've never seen that cause issues before.  Please double check that all of your apple devices are on similar iOS versions as this can sometimes cause issue.  For example, if you are running a beta version on your phone, that could cause the issue you are seeing.  Let me know if you find anything on my end that you think is causing the issue, but I don't think there is anything I can do.
