### ISSUE TITLE
Nat punch static ports not working

### ISSUE THREAD

**Issue by thadrumr** [dgreif/ring#231]
I have homebridge setup behind a Mikrotik router which unfortunately doesn't support NatPMP it only supports UPNP.  I have added the static external ports config and the port forward in my router, but I don't see any hits on the rule in my router.  Below is the config in Homebridge for ring.

  "platform": "Ring",
     "refreshToken": "secrettoken",
     "externalPorts": {
        "start": 21000,
        "end": 21050
        }
   },

**Comment by dgreif** [comment]
Usually UPnP is all that is needed.  Please make sure that is turned on.  If that doesn't help, then there is unfortunately not anything else that I can do.  Port forwarding is the final step, but it sounds like you tried that already.  If you are able to debug the network traffic and can help point me in the right direction, then I would be happy to hear what you think the problem is.  Otherwise, this falls into the category of "unfixable live streams".  Sorry I can't do more!
