### ISSUE TITLE
Status call for Ring sensors?

### ISSUE THREAD

**Issue by JasonB2018** [dgreif/ring#236]
I'm new to the MagicMirror community and new to modern coding. I greatly enjoy the MMM-Ring module that uses your API to show a video clip when the doorbell is rung. 

Is there a way to pull the sensor data on a regular basis to determine if the sensor is open or closed? Or, in the case of the 3rd party garage tilt sensor, to tell if it's tilted or not? 

The closest solution I could think of would be to pull the latest history event for each device on a periodic basis. Thoughts?

Cheers,
Jason

**Comment by dgreif** [comment]
I haven't dealt with any tilt sensors on this plugin yet, but I am assuming it connected with z-wave to the alarm base station?  If so, you should be able to use `api.getLocations()`, then `location.getDevices()` to get the list of devices.  Once you find the tilt sensor in that array of devices, you can do `device.onData.subscribe(data => { handle changes to the data here })`.  You will have to take a look at `data` and see how it is structured to know if it is titled or not,  `onData` is connected to the alarm hub via websockets, so no polling is necessary.  

Since tilt sensors are a new type of device that I don't have data on yet, would you mind following the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and posting the results here?  Thanks in advance if you do!

**Comment by JasonB2018** [comment]
Thanks! I'll tinker with it and be sure to share any findings I discover and/or successes & failures along the way.
