### ISSUE TITLE
No sound even with FFmpeg 

### ISSUE THREAD

**Issue by phis5533** [dgreif/ring#251]
# Live Streaming Issue

### Describe the live streaming issue

Hi, when I request Live streaming, it does work fine but not for the sound, I've got a "Streaming video only - ffmpeg was not found".
But FFmpeg is installed in my PATH...
I'll try to enable debug mode, but I don't know where to find the logging :(

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Recommended solution
 Please describe what you think is causing this issue, and how you recommend it be fixed

### Environment

 - Ring Camera: [DoorBell v1 (Battery)]
 - OS: [macOS 13]
 - Node.js: [v9.5.0] 
 - NPM: [5.6.0] 
 - homebridge-ring (if applicable): [last one]
 - homebridge (if applicable): [last one]

### Network Environment
 
Time capsule for WiFi
TV and HomePod as hub

**Comment by dgreif** [comment]
@phis5533 thanks for filling out the issue template!  In this case, my guess is that you have homebridge running as a different user account on your mac than the user you are setting the path for.  I won't be able to guide you through the process of fixing it because there are so many different ways to set up homebridge, but that's where I recommend you look.  If you have homebridge running as a service, there is probably a different PATH env variable for that service account.  As far as the logs go, it all depends on how you are running homebridge.  Wherever your homebridge logs go, that's where the homebridge-ring output would go.

**Comment by phis5533** [comment]
ok, thx for the answer, I'll investigate my side.. :-) 
And thx for your work !
