### ISSUE TITLE
Monitor connection for cameras

### ISSUE THREAD

**Issue by tsightler** [dgreif/ring#254]
# Feature Request

### Description
I can't seem to work out a way to monitor the connection to cameras.  I'm continuing to enhance the ring-mqtt code which allows Ring alarm and cameras to be monitored and controlled via MQTT, primarily via Home Assistant, but also with other MQTT tools like Code Red.  One common request is to support availability status in Home Assistant which I already did for the alarm components by monitoring the websocket state, but for cameras, even if I completely block the connection, there doesn't appear to be any indication that the connection/polling is not working.

### Describe the solution you'd like
Some indication that backend polling is not working would probably be good enough.  One thought is to include a timestamp of last successful poll or something to that effect, or perhaps a flag if 3 polling sessions fails, but I can certainly see other ways such as an online indicator, etc.

### Describe alternatives you've considered
I thought just doing something like calling deviceHealth() or requestUpdate() might fail and I could just catch the error, but they appear to fail silently.  I also attempted to monitor data.subscribed and data.subscribed_motions but they appear to continue to show active subscriptions even after the link is down for 5+ minutes.

If there's is some way to do this I'm happy to hear it.

**Comment by tsightler** [comment]
After poking at this a little more it seems like calls to getHealth() doesn't really fail per-se, it seems it just hangs and retries over and over if the connection isn't available so I guess the answer here is maybe to just call this function with a timeout value and assume the connection/service for the device is down if the result does not return in reasonable time.  I'll play with this later today.

I still think it would be nice to have some type of connection state monitor in the API, please let me know if it's there and I'm just unable to find it.

**Comment by dgreif** [comment]
@tsightler glad to see you back at it on the MQTT library.  Unfortunately the cameras don't have a persistent connection like the alarm/lighting do, so we are forced to use polling against the REST api.  Since this is the only "connection" to monitor, it's really a matter of whether or not the user has internet connection (and the Ring servers are online :smile:).   As you found, I continually retry the request if it fails to due to a network error, so it won't return an error if the request fails.  I'm not sure that it makes sense for me to build a monitor for this situation into this library since I can't think of another consumer that would benefit from it.  Your idea of checking for a response within a "reasonable" amount of time is probably your best bet.

**Comment by tsightler** [comment]
Fair enough.  I knew there was no websocket but I thought some indication that the polling was not actually happening would be nice.  Now it's just silent.

Regardless, I've already worked around this in my code by calling GetHealth() on an interval and timing out if it doesn't respond in a reasonable time.  It's hackish, but seems to work just fine in practice.  Thanks!
