### ISSUE TITLE
Hide Home Mode Alarm Device in HomeKit

### ISSUE THREAD

**Issue by Sunoo** [dgreif/ring#260]
# Feature Request

### Description
There is currently no way to hide the “Home Mode” alarm device.

### Describe the solution you'd like
Ideally a config.json object to hide the home mode device added in 7.1.0

### Describe alternatives you've considered
I can’t think of any alternative solutions.

### Device data
N/A

**Comment by donavanbecker** [comment]
If you turn modes off in your ring app then it will turn off the modes alarm.

**Comment by Sunoo** [comment]
Maybe I’m just missing something, but I looked through my Ring app before posting, both on iPad and iPhone, and didn’t see an option for Modes anywhere.

**Comment by dxdc** [comment]
The problem might be that non-Ring Alarm users don't have `Modes` as an option within the Ring app. I think the simpler solution is to just remove this as a HomeKit control if the user doesn't have any alarm related products.

It's described by Ring here, but I don't see any 'Modes' in my controls either: https://community.ring.com/t5/News-and-Announcements/Introducing-Modes/td-p/2484

**Comment by donavanbecker** [comment]
@sunoo and @dxdc have you tried logging out of your ring app and logging back in? And see if modes there. If you look at @dgreifs notes on this feature, it only looks at your ring account if you have modes enabled.

**Comment by Sunoo** [comment]
As far as I can tell, logging out and back in made no difference on the Ring app.

**Comment by donavanbecker** [comment]
![76F1E30D-BB3C-4787-8843-D25C46CD9820](https://user-images.githubusercontent.com/9875439/75172814-7cdb2600-56f3-11ea-9607-8d5d4143009c.jpeg)

**Comment by dxdc** [comment]
@donavanbecker which devices do you have associated with your Ring? I just have doorbell/chime. I'm wondering if you need other accessories to have that appear.

**Comment by donavanbecker** [comment]
I would call ring and see why you aren’t able to see modes in your ring app. Because I just turned off modes in my app and it took the modes alarm off and is not visible to me.

**Comment by donavanbecker** [comment]
@dxdc I have a ring doorbell pro, and floodlight cam, Smart lights, and stickup cams. I really think that you and @sunoo need to both call ring and ask them why it’s not showing up in your app.

**Comment by Sunoo** [comment]
I don’t see anything like that. And I just have the doorbell.

**Comment by donavanbecker** [comment]
Call ring and report back.

**Comment by donavanbecker** [comment]
I just renabled modes and my arlarm shows up again. Definitely a ring issue.

**Comment by dxdc** [comment]
This is the problem @donavanbecker :

https://community.ring.com/t5/News-and-Announcements/Introducing-Modes/td-p/2484/page/13

This feature is being "slow rolled out" over the next 12 months.

**Comment by donavanbecker** [comment]
I would still try calling?

**Comment by onefish2** [comment]
If I do not have a Ring alarm why would I see the Mode settings?

**Comment by donavanbecker** [comment]
Because it is a setting that ring came out with that allows your to change modes in your cameras to control them. You have 3 different modes as my picture above disarmed, Home, and away. My disarmed is set to turn my cameras totally off if I choose to set it to disarmed. Home and away can be set differently, example of use would be having an inside camera and not wanting it to record when you are at home, But have it record when you are not home.

**Comment by dxdc** [comment]
Ring does phased rollouts of their features. There's nothing to be done (as far as I know) to speed this up.

Interestingly, the Modes feature *does* work within HomeKit even for those who can't see/edit it within the Ring app. When I toggle the setting in the Home app, the Ring app gives me a notification that the setting was changed.

So, the API is live, it's just that Ring hasn't enabled in-app access to it.

**Comment by donavanbecker** [comment]
That’s what they said when you called them?

**Comment by dxdc** [comment]
> That’s what they said when you called them?

Yes. It's on the link I shared as well. They release updates in "randomized" phased trials and there is no way to accelerate the process.

**Comment by dgreif** [comment]
Sorry for chiming in late here, but @dxdc is correct that Modes is still being rolled out to users.  As with most of their features, the API is technically accessible to all users, but the feature may be hidden in the Ring app.  When I built out the new switch, I set it up so that it won't be shown if the `mode` is set to `disabled`, which I assumed would be the case for users who have not yet received the feature in the ring app.  It seems, however, that Ring is returning some other value for the current `mode` for locations that have not yet received the feature.  I'll do some more digging and see if I can find a solution that hides the switch in the "unreleased" case.

**Comment by Sunoo** [comment]
If you need me to do any testing or give your any information that comes back from my account, let me know. I’m more than happy to help if I can. For now, I’ve just rolled back to 7.0.0 to remove it.

**Comment by dgreif** [comment]
@Sunoo would you be able to try v`7.2.0-alpha.1`?  If you set `"debug": true` in your config for the ring platform, it should log out a line like `Location Mode: {"mode":"disarmed", ....}`.  If you can paste that line here, it would help me nail this down for sure.  There is a good chance that the location mode switch will go away when you update to that alpha version, but the log would help me make sure I'm doing it for the right reasons

**Comment by dxdc** [comment]
@dgreif Here is what I see. Note certain elements have been masked. The "Mode" accessory is still there, but maybe due to the cached accessory?

```
[2/25/2020, 4:31:11 PM] Registering platform 'homebridge-ring.Ring'
[2/25/2020, 4:31:16 PM] [Ring] Initializing Ring platform...
[2/25/2020, 4:31:17 PM] [Ring] Configuring cached accessory xxxxxxx xxxx Mode
[2/25/2020, 4:31:21 PM] [Ring] Location Mode: {"mode":"disarmed","lastUpdateTimeMS":1582568618312,"securityStatus":{},"readOnly":false,"notYetParticipatingInMode":[],"responseTimestamp":1582669881000}
[2/25/2020, 4:31:21 PM] [Ring] Configuring 2 cameras and 3 devices for location "xxxx" - locationId: xxxxx
```

**Comment by Sunoo** [comment]
Just had a chance to updated to that version and turned on debugging. Here is what I get:
`Feb 25 20:02:37 livingroomclock homebridge[4581]: [2/25/2020, 8:02:37 PM] [Ring] Location Mode: {"mode":"unset","securityStatus":{},"readOnly":true,"notYetParticipatingInMode":[],"responseTimestamp":1582678957000} `
And I am no longer seeing the Mode accessory. I upgraded from 7.0.0 so it wouldn’t have been in my cache, if that’s what happened to dxdc.

**Comment by dgreif** [comment]
@Sunoo thank you for those logs, the `unset` mode is exactly what I was looking for!  I've added a check for it in v`7.2.0`, but it will also check for `readOnly: true`, which is why it was able to hide that switch for you without knowing about `unset`.

@dxdc your log shows that the mode is currently `disarmed`, which indicates to me that you actually have the Modes feature already.  If you look in your Ring app, then go under Settings, then Modes, you should be able to turn them off.  If you _do not_ see anything in the Ring app about Modes, then I'm at a loss for how your account got into the state it is currently in. 

Closing this issue since @Sunoo has successfully gotten rid of the Modes switch

**Comment by onefish2** [comment]
@dgreif I am still seeing the mode switch after updating to 7.2.0. Am I missing something to get rid of the Modes switch? I am not seeing Modes in the Ring app.

**Comment by Sunoo** [comment]
7.2.0 works for me, I don’t see the Mode accessory still.

I wonder if the people who it didn’t work for tried changing the mode when that was shown in Home. I never touched it, so it makes sense mine stayed “unset”.

**Comment by dxdc** [comment]
> your log shows that the mode is currently disarmed, which indicates to me that you actually have the Modes feature already.

@dgreif I don't have the Modes feature.

Using `unset` is only a half-solution. The API is responsive regardless of whether or not the feature is available within the app. So, using the HK accessory *can* in fact change the status even if a user has no access to the feature itself.

This could also arise in a multi-user situation where users 1 and 2 have access to the feature within the Ring app, but user 3 does not.

At this point, because the HK accessory "works" this doesn't bother me. Probably there is some way to revert it back to 'unset' though. There must be an API request that tells which features a user has access to... this is the only reliable way to tell.

**Comment by dgreif** [comment]
@dxdc @onefish2 unfortunately I think you guys are in a weird state on the Ring side.  I think the best solution would be to wait until Modes is fully rolled out and then you can disable the feature from the Ring app if it's not something you care to use.  I really don't want to add _yet another_ `hide` flag to the config options, as these can confuse new users as to what options they want/need to use

**Comment by dgreif** [comment]
@dxdc @onefish2 not sure why I didn't think of this sooner, but I just released v`7.2.1` which allows you to set `"locationModePollingSeconds": 0` in your homebridge config.  If you set that option to `0`, it will now hide the location mode switch.  I didn't want to add a new config option just for this corner case, but `locationModePollingSeconds` was already there, so no harm in using it 😄

**Comment by onefish2** [comment]
@dgreif thanks for taking care of this. And a huge thank you for all the work you have put into this plugin!!

**Comment by dxdc** [comment]
thanks @dgreif - echo @onefish2 's comments!!

**Comment by Karrypto** [comment]
I just stumbled upon this post and wanted to share my thoughts on it.
I already use a simple rule that prevents me from arming the security system when any window is open. It works quite well. Unfortunately without notification ("hey!! window is open !"), but I think one can expect a certain intelligence and conclusion from the user. 😄 

So here is my simple rule for that:

Starting with Eve App:

Trigger: other value -> select **"Security System Arming"** Sensor -> Enable it an set to ON

Condition: select a window or door sensor and set it to IS OPEN

Action: select any scene (unfortunately the Eve App only allows Scenes...so select any scene...it will be deleted in next step)

Go to Home App and edit the rule:

Now remove the scene selected in Eve App before and then select the **"Mode Off"** switch of the security system and set it to ON (Mode Off switch must be enabled in config)

Ready. Now if you try to set the security system to "away" and the window is open, it will not be enabled and the switch moves immediately back to off position. 👍 

Unfortunately the Eve App don't allow to select multiple window sensors for the condition part. You can select them, but then unfortunately ALL conditions (window sensors) must be true for the rule to be executed. Therefore you have to add a rule for every window which should be checked.

A workaround would be variable/switch, which is true/activated if any window is open...like a "Not Ready to Arm" Switch. Then you can use this switch as condition instead of all the window sensors. You can create a rule in Eve App 

Trigger: select every window sensor and set it to IS OPEN
(every trigger will execute the rule)

Action: set "Not Ready to Arm" switch to ON

Now we can use the first rule with this "not Ready to Arm" switch as condition and it should work like a charm 😃 

I know...this is one more virtual switch to implement *arrrg* 🙅 , but this would be an easy solution. Of course, you can also use a light bulb or something else you already have for this variable...but that's kind of bad too 🤔 

I know it's not as complex as the original idea in this post, but it certainly helps to use the basic idea first. What you think.

**Comment by dxdc** [comment]
@Karrypto my 2 cents...

HomeKit (native automation), Eve, IFTTT, and others have a lot of limitations. There are a lot of possible sophisticated rule sets that one can implement.

For instance:
- Between sunset-sunrise, but only in winter months
- If A&B or B&C but not A&B&C
- If Event 1 happens within 30 seconds of Event 2

I migrated all of my rules to NodeRED using NorthernMan54's excellent plugin:
https://github.com/NorthernMan54/node-red-contrib-homebridge-automation

The amount of control is exponential. You can implement all these rules, and more. No more limitations.

I have now implemented:
- Blinds that go up and down based on projected sun glare in a window
- Temperature control that works based on algorithmic calculations of current humidity, moisture, comfort, and current outdoor temperature (A/C should not be running when outdoor temps < 60 F)
- Sonos notifications based on events using speech to text. E.g., I can trigger your "Bedroom window is open" notification if desired.

It's really worth learning for a more powerful ruleset.
