### ISSUE TITLE
Ring & tiles not Showing in Homebridge Accessories List

### ISSUE THREAD

**Issue by Nate872711** [dgreif/ring#261]
I'm not sure if this is a bug really, but having an accessory in Homebridge should make it show up under the listed accessories when you tap on the Bridges -> Homebridge -> Accessories.

Any idea why it's not?

# Bug Report

### Describe the Bug
 Ring isn't listed among Accessories under Homebridge on the Home App.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50]

**Comment by dgreif** [comment]
Assuming you are referring to a Ring camera, and not some other Ring device, then it is because of a limitation in the current version of Homebridge.  Cameras behave different from all other homebridge devices, and must be added to HomeKit individually, instead of being added through the homebridge "Bridge" accessory.  I can't say for certain, but I believe a newer version of HAP-Node supports bridging for cameras, but this feature has not made its way into homebridge yet.  Unfortunately the main homebridge project has become quite stale 😞
