### ISSUE TITLE
Support Person Detection

### ISSUE THREAD

**Issue by Sunoo** [dgreif/ring#263]
# Feature Request

### Description
Support Person Detection

### Describe the solution you'd like
Ring started supporting a subcategory of motion alerts that show “person detected”. It would be nice for this plugin to possibly support limiting alerts to those, instead of all motion, to drastically reduce fall alerts.

### Describe alternatives you've considered
Disabling motion alerts in HomeKit and going back to the Ring app I guess?

### Device data
`[{"name":"Home","cameras":[{"description":"Front Door","subscribed":true,"subscribed_motions":true,"battery_life":"100","external_connection":true,"firmware_version":"Up to Date","kind":"doorbell_v3","settings":{"offline_motion_event_settings":{"subscribed":true,"enabled":false,"max_upload_kb":5000,"resolution_p":360,"frequency_after_secs":1,"period_after_secs":30},"lite_24x7":{"subscribed":true,"enabled":false,"frequency_secs":840,"resolution_p":360},"enable_vod":1,"exposure_control":2,"motion_zones":[1,1,1,1,1],"motion_snooze_preset_profile":"low","motion_snooze_presets":["none","low","medium","high"],"live_view_preset_profile":"high","live_view_presets":["low","middle","high","highest"],"pir_sensitivity_1":3,"vod_suspended":0,"doorbell_volume":8,"vod_status":"enabled","chime_settings":{"type":0,"enable":true,"duration":10},"advanced_motion_detection_enabled":false,"advanced_motion_zones":{"zone1":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone2":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}},"zone3":{"name":"","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0},"vertex3":{"x":0,"y":0},"vertex4":{"x":0,"y":0},"vertex5":{"x":0,"y":0},"vertex6":{"x":0,"y":0},"vertex7":{"x":0,"y":0},"vertex8":{"x":0,"y":0}}},"advanced_motion_detection_human_only_mode":true,"enable_audio_recording":true,"people_detection_eligible":true,"ignore_zones":{"zone1":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone2":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone3":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}},"zone4":{"name":"undefined","state":0,"vertex1":{"x":0,"y":0},"vertex2":{"x":0,"y":0}}},"enable_rich_notifications":null,"rich_notifications_billing_eligible":true,"loitering_threshold":10,"advanced_motion_detection_types":["human"],"motion_detection_enabled":true,"rich_notifications_scene_source":"cloud","advanced_motion_zones_enabled":false,"advanced_motion_zones_type":"6pir","advanced_pir_motion_zones":{"zone1_sensitivity":5,"zone2_sensitivity":5,"zone3_sensitivity":5,"zone4_sensitivity":5,"zone5_sensitivity":5,"zone6_sensitivity":5},"rich_notifica-uuid":null},"features":{"motions_enabled":true,"show_recordings":true,"show_vod_settings":true,"rich_notifications_eligible":false,"show_24x7_lite":false,"show_offline_motion_events":false},"owned":true,"alerts":{"connection":"online"},"motion_snooze":null,"stolen":false}],"devices":[]}] `

**Comment by ifeign** [comment]
This would be very helpful. I still use the native Ring notifications instead of the ones from the Home app due to reduced notifications.

**Comment by dgreif** [comment]
Makes sense. I have been totally focused on 2-way audio, but may have some time to work on new features like this one over the coming weeks

**Comment by dxdc** [comment]
+1

What about just creating different motion sensors for this purpose? E.g., there could be a motion sensor for people only.

**Comment by Cardo1** [comment]
Other cameras I have have two different sensor services. “Motion sensors” report all motion, whilst “Occupancy sensors” only report more substantial movement. I use the latter for auto lights, etc. Could use a similar idea here?

**Comment by dgreif** [comment]
I started looking into using an Occupancy Sensor this morning and have a rough version working.  The biggest downside is that the HomeKit occupancy notifications don't include a snapshot like the motion notifications do.  Instead of "Camera X detected motion", it says "Occupancy detected in room x".  I'm really not sure how everyone wants to use this feature, whether it is mainly to trim down the motion alerts, or to automate motion vs person occupancy.  If the main focus is just trimming alerts, then I think it would be best to keep a single motion sensor and have an option to switch between person only and all motion.  Alternatively, I could add a second motion sensor (not occupancy sensor), but I don't think you can control the notification settings at the motion sensor level, just the camera level, so it probably wouldn't help trim down alerts.  Occupancy sensors _do_ have their own notification settings.  Happy to hear thoughts on what matters and which approach you think would be best.

**Comment by dxdc** [comment]
> I think it would be best to keep a single motion sensor and have an option to switch between person only and all motion.

This feature to switch between person/all motion already exists with Ring on a per-camera basis. What about just an On/Off switch that mirrors the API behavior? Either that, or an On/Off switch that limits HK notifications to ones that have Person only (despite what the Ring setting is). I can see that as beneficial for trimming the alerts.

Without the snapshot feature, I might still vote for the motion sensor feature since it could be used indirectly, even with the built-in HomeKit automations. For example, suppose I have an automation that whenever motion is detected at the front door between 8PM-12AM to turn on the lights. Now, I can use your secondary "person motion" sensor to do the same thing and it will be no longer triggered by neighborhood cats. :)

And, similarly, I could have an automation to use the On/Off switches for People Only during the day, and everything at night.

**Comment by Sunoo** [comment]
My use case for it is to reduce nuisance notifications, since my camera faces a street, and the 'normal' motion detector gets tripped fairly often. Having it as an occupancy sensor really wouldn't help me at all.

**Comment by dgreif** [comment]
Thanks for the input @dxdc @Sunoo.  I did a fair amount of testing this morning and from what I can tell, the "Person Only Mode" setting is a per-camera setting, not per client device like a lot of the other settings.  That means that if I turn on person only motion, then it should never trigger motion events from the Ring app _or_ from homebridge if a person isn't detected.  Would either of you mind turning on notifications from _both_ the Ring app and homebridge to test this theory?  If I'm right, you should always receive motion alerts from both.  If I'm wrong, you would sometimes receive notifications from just homebridge when motion is detected without a person.  If my theory is correct, then there isn't really anything that needs to be done, other than maybe adding a switch so that you can automate turning person only mode on/off

**Comment by Sunoo** [comment]
I can confirm that I get motion alerts without a person detected from Homebridge currently, but not from Ring.

**Comment by dxdc** [comment]
I don't think my experience is the same. With person-detection mode enabled (via Ring) I don't get notifications either on Ring or HK.

@Sunoo what kind of Ring devices do you have, and, do you have person only mode enabled?

**Comment by dxdc** [comment]
![image](https://user-images.githubusercontent.com/7200365/88482826-5e3ebc80-cf29-11ea-8800-3f7e02ba343f.png)

**Comment by Sunoo** [comment]
I have a Doorbell, and person mode is enabled. I can't change any settings right now, because the Ring app seems to not work on iOS 14 beta 3.

**Comment by dgreif** [comment]
After extensive testing and discussion with @Sunoo and @dxdc, the conclusion is that Ring is already filtering the `ding`s based on Person Only mode on the camera/server side.  If you enable Person Only mode in the Ring app, it will directly impact the motion alerts that you receive from `homebridge-ring`.  As a result, `homebridge-ring` does not need to do any sort of filtering to trim down alerts

**Comment by DMBlakeley** [comment]
I have a Ring subscription and recently noticed that if Live View is initiated from the Home app that this session is recorded by Ring and can be viewed in the Ring App. Was this always the case?

**Comment by Sunoo** [comment]
@DMBlakeley Yes.

**Comment by ifeign** [comment]
Yes. This plugin simply pulls video from the Ring server. It doesn’t make
Ring cameras behave like actual HomeKit cameras that are locally networked
and private.

**Comment by DMBlakeley** [comment]
@Sunoo and @ifeign, thanks for the quick response. I realized that the app was pulling from the Ring server just didn’t realize that the Live View was also being recorded.

**Comment by ifeign** [comment]
If this plugin found a way to bypass the Ring server, it would probably get
shut down by Ring.

**Comment by rwgunther** [comment]
Thanks for your (prior) research on this. I'll enable this in Ring to take advantage of it in Homebridge.

**Comment by sjonez** [comment]
Ring have now added a new "Smart Notifications" feature that allow you to separate out "person" and "other motion" events so that both types of motion are now recorded but you only get notified in the ring app of the ones you are interested in (see screenshot)
![Screenshot_20210522-064141](https://user-images.githubusercontent.com/12478937/119216094-76d81e80-bac9-11eb-89bb-13514bc313aa.jpg)

When this feature is turned on, even if notifications are disabled for the "other motion" category we still seem to trigger an active ding via this API and I can't see any way to differentiate between person/other motion (I noticed that when looking at historic dings there is a "person_detected" property on the CameraEvent interface that returns true/false but there's no such property on an active ding)

It would be great if this feature was supported so person detection events could be identified on an active ding (just over the last few days since enabling it seems to do a great job separating out actual people from car headlights etc..)

**Comment by alardierejr** [comment]
Can we have this reopened?
