### ISSUE TITLE
Placeholder image when no snapshots available

### ISSUE THREAD

**Issue by Rubenfer** [dgreif/ring#318]
# Feature Request

### Description
According to https://github.com/dgreif/ring/issues/311#issuecomment-623507369 Ring cameras doesn't retrieves snapshots if motion_detection_enabled flag is off. An option to show this status to the users is show a placeholder image instead a snapshot if Ring cannot capture snapshots and the last snapshot is expired (more than 10 minutes).

### Describe the solution you'd like
The homebridge plugin for Nest cameras homebridge-nest-cam2 recently introduced this feature, the behavior in this plugin could be similar.

Reference: https://github.com/Brandawg93/homebridge-nest-cam2/blob/09ffd2705cda7b7d58b753149d091e8d9e97ac3e/src/streamingDelegate.ts#L102

**Comment by dgreif** [comment]
@Rubenfer I think this is a great idea.  Added a couple different placeholders in v`9.1.0` depending on the state of the camera

**Comment by durosity** [comment]
Brilliant idea.. can I suggest an extension to this of having a field in the config for a custom URL for an external image.. also with the ability to always use it rather than the Ring one?  The use case in my situation would be I have a tiny camera mounted under my doorbell that uploads a jpg to a web server every 2 seconds... this would be much more reliable for me than my old battery powered ring doorbells functionality.

**Comment by dgreif** [comment]
@durosity I can see where that would be a neat feature given your setup, but I can't imagine many other users have a setup like this.  The snapshots code is getting more complicated by the day and I'm not inclined to add more complication for a feature that will likely only be used by a single user.  Sorry to have to say no, but I need to start managing features to keep this plugin maintainable

**Comment by durosity** [comment]
That’s fair!  To be honest I thought it was a long shot but shy bairns get nowt as they say!  I might look at just replacing the doorbell with a mains powered pro then!
