### ISSUE TITLE
Error: HAP CameraController not found.  Please make sure you are on homebridge version 1.0.0 or newer

### ISSUE THREAD

**Issue by arossmt** [dgreif/ring#320]
# Bug Report

### Describe the Bug
Ring Doorbell Camera doesn't update in HomeKit.
Removed camera and then unable to add again.
Removed home bridge-ring and reinstalled, logged into Ring account.
Again camera doesn't show and unable to add.

### To Reproduce
 - Start Homebridge

### Expected behavior
Ring Doorbell Camera should show up in HomeKit.
### Screenshots/Logs
[5/12/2020, 2:41:09 PM] [Ring] HAP CameraController not found.  Please make sure you are on homebridge version 1.0.0 or newer
[5/12/2020, 2:41:09 PM] [Ring] Error connecting to API
[5/12/2020, 2:41:09 PM] [Ring] Error: HAP CameraController not found.  Please make sure you are on homebridge version 1.0.0 or newer
    at new Camera (/homebridge/node_modules/homebridge-ring/lib/homebridge/camera.js:26:19)
    at /homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:192:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:170:28)
    at Generator.next (<anonymous>)
    at fulfilled (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### Homebridge Ring Config

Enabled debugging just in case to see if any addl output

        {
            "refreshToken": "xxx",
            "debug": true,
            "platform": "Ring"
        }

### Environment
DOCKER OS | Alpine Linux (3.11.5)
Node v12.16.2
NPM v6.14.4
Homebridge Version 1.0.4
homebridge-ring v8.1.0

**Comment by dgreif** [comment]
@arossmt it looks like the version of homebridge that is actually used is < 1.0.0.  There have been a few users that had multiple version of homebridge installed, which lead them to believe that they were using 1+ when in practice a different version was running.  See #315.  Looks like you are running homebridge from your `/homebridge` directory, which is where you need to have homebridge 1+ installed.  My guess is you have it installed globally as well.

**Comment by arossmt** [comment]
Yes, the logs show notes on multiple versions of homebridge :(
It did before and was working fine so I did not relate it to this issue.

**Comment by floshion** [comment]
Hello, i've the same problem with hombridge on jeedom. Unable to resolve it. All my configuration it's ok but i've the same error. 
I confirm that i've only one version of hombridge installed.
dgreif, can u see if a solution is possible please?

**Comment by dgreif** [comment]
@floshion I've never heard of jeedom, but I'm 100% certain that this is an issue in your environment if you are see the error in this issues name.  If homebridge 1+ is used to run this plugin, there is no way you would see this error.  Sorry I can't do more to help, you have to figure it out on your end.

**Comment by floshion** [comment]
look these captures :
https://imgshare.io/image/NNsX5w
https://imgshare.io/image/NNssXe

my homebridge and plugin versions is up to date

**Comment by dgreif** [comment]
That does confirm that you have _an_ instance of homebridge that is version 1.0.4, but you could still have another instance of homebridge installed either globally or in the directory that you run homebridge from

**Comment by floshion** [comment]
I can confirm to you 200% that homebridge is running well from this instance. No other instance is installed and running. For the moment, we are only two people to relay the problem but I am sure that other people will come forward.

**Comment by dgreif** [comment]
@floshion I should clarify, it is not required that other homebridge instances be _running_, just that they are present.  Homebridge is installed as a node module, which can be done locally in a folder, or globally.  If you run homebridge from a folder and have it installed both there and globally, you can run into issues like the one you are seeing. Try running `npm ls -g homebridge` and `npm ls homebridge` from the directory you run homebridge from and see what each prints out

**Comment by floshion** [comment]
the firts command say it "empty" but he secondly say : "
jeedom_homebridge@0.0.1 /var/www/html/plugins/homebridge/resources
└── homebridge@0.4.53  (github:NebzHB/homebridge-stable#6645cbead6b9f89f615098619bc41d4bc0bb1143)"
sorry i think thant my version of hombridge jeedom is not up to date.. :/ so, how can update it manually?

**Comment by dgreif** [comment]
No idea, like I said I've never heard of jeedom.  Please post back here if you figure it out so that others can find it.  Good luck!

**Comment by floshion** [comment]
It's ok using your command "npm ls homebridge"
I executed it then I reconnected to my homebridge interface and there he told me that I was not up to date. I did the update and BINGO
thank you very much for your help.

**Comment by Hornett69** [comment]
Hello I have a same issue since upgrade with homebridge 1.1.0 : 
Raspberry PI 3 up to date
Node : v12.16.1
Npm : 6.14.5
Homebrige : 1.1.0

Msg : mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] HAP CameraController not found.  Please make sure you are on homebridge version 1.0.0 or newer
mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] Error connecting to API
mai 25 17:59:20 raspberrypi homebridge[1856]: [2020-5-25 17:59:20] [Ring] Error: HAP CameraController not found.  Please make sure you are on homebridge version 1.0.0 or newer
mai 25 17:59:20 raspberrypi homebridge[1856]:     at new Camera (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/camera.js:27:19)
mai 25 17:59:20 raspberrypi homebridge[1856]:     at /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:193:123
mai 25 17:59:20 raspberrypi homebridge[1856]:     at Array.forEach (<anonymous>)
mai 25 17:59:20 raspberrypi homebridge[1856]:     at RingPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:171:28)
mai 25 17:59:20 raspberrypi homebridge[1856]:     at Generator.next (<anonymous>)
mai 25 17:59:20 raspberrypi homebridge[1856]:     at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
mai 25 17:59:20 raspberrypi homebridge[1856]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)

pi@raspberrypi:~ $ npm ls homebridge
/home/pi
└── (empty)

pi@raspberrypi:~ $ npm ls -g homebridge
/usr/local/lib
└── homebridge@1.1.0 

Any idea ??
