### ISSUE TITLE
Live streaming bugs with v8

### ISSUE THREAD

**Issue by dxdc** [dgreif/ring#325]
# Live Streaming Issue

### Describe the live streaming issue

Have two different bugs, but all surrounding live streaming. Something broke in homebridge-ring v8 for me as far as live streaming goes.

1. Snapshots work fine. But, if I try to live stream, I see the circle "loader" spinning in the video. Is this expected? I'm not sure it's working at all. It was working fine on an earlier version of homebridge-ring (7.X). The logs indicate it should be working just fine, but I don't see any streaming happening. If it is expected, then it's a bit confusing behavior, though not sure if it can be turned off.

2. If I live stream, and then force quit the home app while viewing the live stream itself, homebridge-ring has a very difficult time recovering. Basically prevents viewing of the live stream at all, even after reopening the home app. There is an overlay on the video that says "No Response. Wait until someone else in this home stops viewing this camera and try again".

This is akin to #157 that I reported earlier, but seems now it's no longer recoverable. Seems I have to restart homebridge to fix it now.

#### For issue 1, above:
```
[5/18/2020, 6:38:08 AM] [Ring] Snapshot for Front Door is still within its life time (19.475s old)
[5/18/2020, 6:38:10 AM] [Ring] Preparing Live Stream for Front Door
[5/18/2020, 6:38:12 AM] [Ring] Waiting for stream data from Front Door (1.682s)
[5/18/2020, 6:38:12 AM] [Ring] Received stream data from Front Door (2.128s)
[5/18/2020, 6:38:14 AM] [Ring] Streaming active for Front Door
[5/18/2020, 6:38:28 AM] [Ring] Stopped Live Stream for Front Door
```

#### For issue 2, above:
```
1|homebridge  | [5/18/2020, 6:40:30 AM] [Ring] Preparing Live Stream for Garage
1|homebridge  | [5/18/2020, 6:40:31 AM] [Ring] sip INVITE request failed with status 401
1|homebridge  | [5/18/2020, 6:40:31 AM] [Ring] Failed to prepare stream for Garage (0.487s)
1|homebridge  | [5/18/2020, 6:40:31 AM] [Ring] Error: sip INVITE request failed with status 401
1|homebridge  |     at sipClient.send (/usr/lib/node_modules/homebridge-ring/lib/api/sip-call.js:117:28)
1|homebridge  |     at searching (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1316:5)
1|homebridge  |     at /usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1297:41
1|homebridge  |     at Object.message (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1103:7)
1|homebridge  |     at Object.signal (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:982:55)
1|homebridge  |     at /usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:1344:24
1|homebridge  |     at onMessage (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:558:9)
1|homebridge  |     at content (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:493:7)
1|homebridge  |     at headers (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:480:9)
1|homebridge  |     at TLSSocket.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/sip/sip.js:504:27)
1|homebridge  |     at TLSSocket.emit (events.js:198:13)
1|homebridge  |     at addChunk (_stream_readable.js:288:12)
1|homebridge  |     at readableAddChunk (_stream_readable.js:265:13)
1|homebridge  |     at TLSSocket.Readable.push (_stream_readable.js:224:10)
1|homebridge  |     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Recommended solution
Not clear what the issue is.

### Environment
 - Ring Camera: [e.g. Stickup Cam Battery]
 - OS: Raspbian GNU/Linux 10 (buster)
 - Node.js: v10.20.1
 - NPM: v6.14.5
 - homebridge-ring v8.2.0 (but, was working fine before the 8.X upgrade)
 - homebridge v1.1.0

### Network Environment
Everything is on the same mesh Wifi network. I can provide more details here if it would be helpful, but it doesn't seem like this is an issue given that 1) it was working fine before in v7.X (last release before v8), and 2) snapshots, etc. are being pulled just fine.

**Comment by dxdc** [comment]
Also, not sure if it's helpful, but the only two unusual aspects of my config would be:

```js
      "hideDoorbellSwitch": true, 
      "hideInHomeDoorbellSwitch": true, 
```

**Comment by rcoletti116** [comment]
I am having the same issue after updating to the latest version today, v8.2.0

**Comment by DatBoiRo** [comment]
Same issue. Before the update, I had no issues viewing my Ring Pro Doorbell. Now, all I get is spinning wheel, then "the camera stopped responding."

**Comment by floshion** [comment]
Hello, i'v the same issue since the update, i can't have the live stream but it's ok on the ring application

**Comment by benfysh** [comment]
I am seeing the same issue on v8.20 with all of my cameras, snapshots are updating fine however trying to stream doesn't work. The logs show the following:
```
[5/20/2020, 16:17:54] [Ring] Waiting for stream data from Garage (0.789s)
[5/20/2020, 16:18:03] [Ring] Stopped Live Stream for Garage
[5/20/2020, 16:18:03] [Ring] Received stream data from Garage (10.484s)
```
The "No Response" overlay comes up when the `[Ring] Stopped Live Stream for Garage` message is printed in the logs.

**Comment by sybrendotinga** [comment]
Same here: 

```
[5/20/2020, 5:34:56 PM] [Ring] Preparing Live Stream for Voordeur
[5/20/2020, 5:34:57 PM] [Ring] Waiting for stream data from Voordeur (0.79s)
[5/20/2020, 5:34:58 PM] [Ring] Received stream data from Voordeur (1.759s)
[5/20/2020, 5:34:58 PM] [Ring] Streaming active for Voordeur
[5/20/2020, 5:35:26 PM] [Ring] Stopped Live Stream for Voordeur
```

No visual, and got a "No response"-overlay aswell.

**Comment by dgreif** [comment]
I just wanted to confirm that I have seen this issues some as well.  I haven't pinned down the exact problem yet, but will hopefully get an update out this weekend.

**Comment by dgreif** [comment]
Ok, quick question.  Are you trying to view the cameras on the _same computer_ that is running homebridge?  As in a mac that is also your homebridge server?  I think I introduced a bug that causes issues in that exact scenario, but looking at the cameras on your phone would work just fine.  Can anyone confirm?

**Comment by rcoletti116** [comment]
Not me. HB running on a raspberry pi. Viewing in the home app on iPhone.

**Comment by benfysh** [comment]
Same for me. Homebridge on a Pi and using and iPhone to view.

**Comment by divemasterjm** [comment]
> Ok, quick question. Are you trying to view the cameras on the _same computer_ that is running homebridge? As in a mac that is also your homebridge server? I think I introduced a bug that causes issues in that exact scenario, but looking at the cameras on your phone would work just fine. Can anyone confirm?

im in this situation

**Comment by dxdc** [comment]
I discovered something really strange that fixes this problem.

1 (Optional): Restart homebridge (only needed if your cameras are showing "No Response. Wait until someone else in this home stops viewing this camera and try again".)
2. Toggle OFF Wifi on iPhone, and use LTE connection
3. Go into *each* camera and initiate live view. It will take 15-20 seconds or so, but it will work!
4. After all cameras are working in LTE, switch back to Wifi.

Now, this behavior persists across restarts and live view seems totally fixed! I really have no explanation for this, but curious if this fixes it for others.

**Comment by DatBoiRo** [comment]
This worked. Toggled WiFi off, opened home app, livestream popped up instantly. Weirdo back on, close and reopen home app, livestream persists.

**Comment by dxdc** [comment]
I looked over the logs, didn't see anything unusual, except maybe this:

`Ding XXXXXXXX is expired (480).  Fetching a new ding and trying video stream again`

@dgreif Wondering if there is a cached `Ding` from before the update that never gets properly reset? Or, maybe it's some kind of HomeKit bug?

Anyway, happy it's working. Also it fixes both issues I raised (1 & 2).

**Comment by rcoletti116** [comment]
> I discovered something really strange that fixes this problem.
> 
> 1. Optional: Restart homebridge (only needed if your cameras are showing "No Response. Wait until someone else in this home stops viewing this camera and try again".)
> 2. Toggle OFF Wifi on iPhone, and use LTE connection
> 3. Go into _each_ camera and initiate live view. It will take 15-20 seconds or so, but it will work!
> 4. After all cameras are working in LTE, switch back to Wifi.
> 
> Now, this behavior persists across restarts and live view seems totally fixed! I really have no explanation for this, but curious if this fixes it for others.

No joy for me...

**Comment by benfysh** [comment]
> 
> No joy for me...

Same here, "No Response" on 4g and wifi

**Comment by dxdc** [comment]
> No joy for me...

Did you try restarting homebridge first to reinitialize everything? I found that if I had previously initiated a live view session this technique would not work.

**Comment by rcoletti116** [comment]
> > No joy for me...
> 
> Did you try restarting homebridge first to reinitialize everything? I found that if I had previously initiated a live view session this technique would not work.

Yes, I did. I tried a few times actually. Closed out all apps on my iPhone, restarted homebridge, switched off WiFi, go into each camera, after about 10-12 seconds I get the same error as before "No Response. Wait until someone else in this home stops viewing this camera and try again."

**Comment by rcoletti116** [comment]
What's interesting here is the logs don't really show a problem, and you might think it was working.

[5/21/2020, 12:52:44 PM] [Ring] Preparing Live Stream for Front Door
[5/21/2020, 12:52:44 PM] [Ring] Ding 6829279316725042599 is expired (480).  Fetching a new ding and trying video stream again
[5/21/2020, 12:52:45 PM] [Ring] Waiting for stream data from Front Door (0.815s)
< [5/21/2020, 12:52:54 PM] [Ring] Stopped Live Stream for Front Door > At this point is when the message shows up.
<[5/21/2020, 12:52:54 PM] [Ring] Received stream data from Front Door (10.448s)> No stream actually, very misleading.
![IMG_768A29F655F9-1](https://user-images.githubusercontent.com/8211291/82561071-b7146200-9b40-11ea-974f-9ed0d5c08f9f.jpeg)

**Comment by dxdc** [comment]
@rcoletti116 Strange. I saw similar messages in the logs indicating it was working, so I'm not really sure either, and now that mine *is* working, I don't see any different indications in the logs as to why. But after multiple rounds of tests mine is still working.

Also, I'm now seeing this behavior, but not sure it's related:

1. Force quit HomeKit app
2. Launch HomeKit app several hours later. Snapshot is stale, but it shows "0s, 1s, on it"
3. If I enter "Live View" I can pull a live feed, and after exiting, the snapshot is refreshed and again says "0s, 1s..." on it.

**Comment by rcoletti116** [comment]
I don't know exactly how, but it's working now. I tried to troubleshoot and isolate any potential fixes or new issues. After various attempts to reinstall the plugin and roll back to old versions did not work, I started focusing on my network. Gave my main router a restart and now I'm good to go. Let's see if it sticks.

**Comment by durosity** [comment]
Outta interest if you revert back to v8.1 or earlier does the video feed start working for you folks again?  I was having this exact issue and while trying to work out what was going on (of course not checking here first which in hindsight i should have) I tried going back to versions 8.1, 8.0, 7.2 but none would give me a video feed which makes me wonder if my issue is different to this one somehow?  I’ve even tried setting up a brand new installation of homebridge on a MacBook never used for it before, and even added that to a brand new home location in HomeKit but alas no joy... just keep getting the same behaviour as listed here.

**Comment by rcoletti116** [comment]
@durosity I also rolled back versions of the plugin to 8.0 & 7.2 but didn’t get it working again. I completely removed it and reinstalled but that also didn’t work. I even did A clean reinstall of FFMPEG for sake of the new two-way audio feature. 
It wasn’t until moving to my network that I fixed it. Try restarting your modem and router. If it helps, I have an AirPort Extreme + express in bridge mode. My homebridge up with an assigned static IP, but otherwise no specific ports or custom settings. Restarted everything and got video working.

**Comment by durosity** [comment]
Interesting.. well at least it’s not just me.  I’ve already tried moving it to a different AP.  Can’t restart the gateway at the moment as other things are running on it but it’s scheduled to reboot at 3am tonight so mebbe that’ll help clear things up.

**Comment by jsrivatsan** [comment]
I have the same bug. The logs do not show any issue but live streaming does not start. If you keep waiting too long, the camera becomes unresponsive. The only way to recover then is to restart homebridge. 

The situation gets slightly better if I use my homepod as hub instead of Apple TV. I will keep digging to see if I can quantify this. Thanks.

**Comment by LordZork** [comment]
Similar issue...

**Raspberry Pi 4** (Model B) 4GB

**HOOBS** 3.2.4 and 3.2.6 (via update)
**Homebridge** 1.1.0

Note: Tried both – HOOBS first, then Homebridge.

**Homebridge-ring** 8.2.0

**Router(s):** ZyXEL (EMG3425-Q10A) [newer] and Apple AirPort Extreme [older]

Note: First attempt: Pi connected to a [2nd] ethernet switch, which was connected to a [main] ethernet switch, which was connected to the router.  Second attempt: Pi connected directly to router.  Tried this with both routers (separately).  

Also tried some port forwarding, in case that mattered.

**Apple TV** 4K (tvOS 13.4.5) + **iPhone SE** 2nd Gen/2020 (iOS 13.4.1)

I just got my first **Raspberry Pi** and, for the first time, tried **HOOBS** and **Homebridge** – spent all day yesterday and today trying to get the **homebridge-ring** live stream to work...

Note: Snapshots work fine. It is only live streaming that is not working.  

I get the circle "loader" spinning in the video, and then it either – typically – tells me "No Response" and "This camera is not responding" or – occasionally – "Wait until someone else in this home stops viewing this camera and try again."

I've tried different terminal commands and whatnot, based on various suggestions from github and elsewhere, and have reformatted and re-flashed the MicroSD card numerous times... and started over...

Also, I followed the [Camera Troubleshooting](https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#cannot-add-camera-from-home) and – based on the logs – figured it was most likely an issue with my network...

[Ring] Configuring 1 cameras and 1 devices for location "XXXX" - locationId: XXXX
[Ring] Snapshot for Front Door is still within its life time (21.086s old)
[Ring] Preparing Live Stream for Front Door
[Ring] Waiting for stream data from Front Door (0.581s)
[Ring] Stopped Live Stream for Front Door
[Ring] Received stream data from Front Door (10.718s)

For this to be a network issue seems really odd, though, as I tried two different routers – one supports UPnP (enabled), and the other NAT-PMP (enabled).  One of them should have worked.  I don't think I have strict NAT settings (haven't had issues with any other smart devices or hubs or online video gaming, etc.)... maybe someone could advise me regarding this (or maybe let me know what routers work with this plugin)!? Also, I am pretty certain it's not my ISP.

Note: From what I've seen and read, so far, it appears that "cameras cannot be added through a bridge and must be added as individual devices"... yet, it does not let me add them individually.  First, I setup the bridge OS (tried HOOBS and Homebridge this way) and added the ring plugin.  Then I added the bridge to HomeKit and it automatically added the cameras.  Then I started over and – without the ring plugin installed – I added the bride to HomeKit.  Then, I installed the ring plugin within the bride OS, and restarted the bridge OS.  Then, I opened the Home app on my phone and it auto-detected and auto-loaded the cameras.  I cannot seem to find a way to manually, individually, add the ring camera as I've seen in videos and read about.  Once the plugin is in the bride OS, it is in HomeKit.  Or, if I connect the bride to HomeKit with the plugin already installed, the camera is added with the bridge.  Not sure if this is a problem or not, but wanted to note it just in case.

Anyway, I was about to give up until I ran across this recent posting, here, regarding live stream issues related to the latest plugin... as reported by some who have experience with previous versions of the plugin, actually working with live streaming.

Note: I've only installed the Homebridge-ring plugin from within the HOOBS and Homebridge GUI.  I've not done any sort of "manual" or other type of install, or Optional Parameters, or other configuration, other than following the provided steps for getting the refresh token, from within the OS GUI (except for HOOBS, which requires a minor use of terminal for getting the refresh token).

Like I said, I am very new to this... only just started.  I have no problem resetting everything, or trying whatever, or buying a new router!  If someone could help me get this working, I'd try just about anything.  I'm desperate at this point... it's the only reason I got the Raspberry Pi.  Otherwise, I may just give up on the whole "Homebridge+HomeKit" thing.

Thanks in advance for any help!

**Comment by dgreif** [comment]
Just wanted to give a quick update since this thread seems to be getting hit hard lately. I have been spending all of my free time over the last two weeks working on more reliable live streaming. Since Ring has no documentation, it requires a lot of trial and error, but I think I’m very close and have figured out how Ring avoids NAT issues on any network. I’m hoping to release an alpha version in the next couple days that all of you can test out. The only downside is it will be dependent on ffmpeg. Ffmpeg is automatically included in the plugin unless you are on a really old os, so this shouldn’t be a problem for the majority of users. For now, please hold tight until I am able to release my changes.

**Comment by LordZork** [comment]
> Just wanted to give a quick update since this thread seems to be getting hit hard lately. I have been spending all of my free time over the last two weeks working on more reliable live streaming. Since Ring has no documentation, it requires a lot of trial and error, but I think I’m very close and have figured out how Ring avoids NAT issues on any network. I’m hoping to release an alpha version in the next couple days that all of you can test out. The only downside is it will be dependent on ffmpeg. Ffmpeg is automatically included in the plugin unless you are on a really old os, so this shouldn’t be a problem for the majority of users. For now, please hold tight until I am able to release my changes.

Awesome, thanks for the update, dgreif! Count me in – I'm happy to test!  I'll be watching this thread and keeping on eye out for a new/alpha version (though, I may need guidance installing an alpha version, unless it will install as normal via [homebridge-config-ui-x](https://www.npmjs.com/package/homebridge-config-ui-x)).

**Comment by paqpaqpaq** [comment]
Same problem here too. Sometimes it returns ding expired, sometimes just stream stopped.
Sometimes it works flawelessly, sometimes I can try 20 times in an hour without any stream. 

I do have the feeling that it doesn't function more often opposed to then it does.

**Comment by paqpaqpaq** [comment]
@dgreif I found another issue:
When opening the app, I see an old snapshot. If I hit live stream, and will actually work, I close the stream and see the last frame as the new snapshot. Briefly exiting the home app and returning again, it will then revert back to the old out of date snapshot.  
This makes no sense(?)

**Comment by durosity** [comment]
@dgreif I've installed the alpha2 release and that's got the video working for me, well done!  However just FYI the snapshots are still not updating.  Just wanted to report it in case it was relevant to what you're working on!

**Comment by LordZork** [comment]
Do you have to install the alpha2 release manually?  It doesn't show up as an update with the installed plugin or when searching plugins.

**Comment by DMBlakeley** [comment]
To install open terminal window and enter:
   `npm i -g homebridge-ring@v8.3.0-alpha.2`
Restart Homebridge manually.

**Comment by paqpaqpaq** [comment]
I have the same as @durosity . Streams seem to be working correctly at first sight and couple of tries. Snapshots however are not updated upon the last stream.

**Comment by LordZork** [comment]
@DMBlakeley 

I opened terminal, copied/pasted the provided code, and got this...

`npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-ring/node_modules/@sindresorhus/is'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-05-26T19_06_40_186Z-debug.log`

I then restarted Homebridge anyway and it still says the plugin I'm running is v8.2.0.

**Comment by paqpaqpaq** [comment]
@LordZork "sudo" is the magic word ;)

**Comment by LordZork** [comment]
@paqpaqpaq 

Thank you!  I added "sudo" at the beginning...

`sudo npm i -g homebridge-ring@v8.3.0-alpha.2`

I'm new to this, sorry, but did I possibly hurt anything by running the command without "sudo"?

**Comment by paqpaqpaq** [comment]
Nope, you are fine.

It just refused to execute your command, that's all.

**Comment by LordZork** [comment]
@dgreif 

I am now running homebridge-ring **v8.3.0-alpha.2** and live stream/video is working!!

Thanks for your work on this plugin!! :)

**Comment by paqpaqpaq** [comment]
It's amazing actually how much faster it is now @dgreif 👍

**Comment by paqpaqpaq** [comment]
hmmm... problem seems to re-occur again:
```
[2020-5-28 11:14:29] [Ring] Preparing Live Stream for Office
[2020-5-28 11:14:34] [Ring] Ding 6831820859333998671 is expired (480).  Fetching a new ding and trying video stream again
[2020-5-28 11:14:40] [Ring] Stopped Live Stream for Office
```

**Comment by durosity** [comment]
> hmmm... problem seems to re-occur again:
> 
> ```
> 
> [2020-5-28 11:14:29] [Ring] Preparing Live Stream for Office
> 
> [2020-5-28 11:14:34] [Ring] Ding 6831820859333998671 is expired (480).  Fetching a new ding and trying video stream again
> 
> [2020-5-28 11:14:40] [Ring] Stopped Live Stream for Office
> 
> ```

Interestingly I had the same issue this morning.  Opening the ring app and live viewing (to see if it worked, in case the doorbell had lost wifi or something) seems to have fixed it.  Might be worth a try?

**Comment by paqpaqpaq** [comment]
> > hmmm... problem seems to re-occur again:
> > ```
> > 
> > [2020-5-28 11:14:29] [Ring] Preparing Live Stream for Office
> > 
> > [2020-5-28 11:14:34] [Ring] Ding 6831820859333998671 is expired (480).  Fetching a new ding and trying video stream again
> > 
> > [2020-5-28 11:14:40] [Ring] Stopped Live Stream for Office
> > ```
> 
> Interestingly I had the same issue this morning. Opening the ring app and live viewing (to see if it worked, in case the doorbell had lost wifi or something) seems to have fixed it. Might be worth a try?

I tried that just now.  ting app didn't seem to get it to stream either.  took me a couple of tries to get a stream going. That however didn't fix it in homebridge. 
wifi strength varies between -62 and -69.  But I normally have perfect streams and little dropouts when it is -77 for whetever reason.

**Comment by durosity** [comment]
I didn’t try a ding, this was just me live streaming in the home app but I did notice the other day if I had push notifications on in the ring app when pressing the button the stream couldn’t be opened in Home.. I’m guessing Ring captures it in some way?

**Comment by DMBlakeley** [comment]
I am now getting.a strange error. When upgrade to either alpha.2 or alpha.3 I get this error when accessing the camera in the HomeKit app:

`[5/29/2020, 6:56:08 PM] [Ring] Preparing Live Stream for Front Door
[5/29/2020, 6:56:08 PM] [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
[5/29/2020, 6:56:09 PM] [Ring] Failed to prepare stream for Front Door (1.366s)
[5/29/2020, 6:56:09 PM] [Ring] Error: Ffmpeg is not installed.  See https://github.com/dgreif/ring/wiki/FFmpeg for directions.
    at RingCamera.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:353:23)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-ring/lib/api/ring-camera.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
`

When I roll back to @latest I get:
`[5/29/2020, 7:02:20 PM] [Ring] Preparing Live Stream for Front Door
[5/29/2020, 7:02:20 PM] [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.
`

I need to fully remove and reinstall homebridge-ring for things to work correctly. Thoughts?

**Comment by DMBlakeley** [comment]
Ok, installed ffmpeg manually per `https://github.com/dgreif/ring/wiki/FFmpeg`. Now working, not sure how I lost ffmpeg ...

**Comment by dxdc** [comment]
@DMBlakeley Did you try installing with the `--unsafe-perm` flag? I found out that in my case, ffmpeg wouldn't install without it.

**Comment by DMBlakeley** [comment]
Thanks for the tip. Will remember for next update.

**Comment by durosity** [comment]
Has anyone had any luck with the snapshots updating at all, even with the new v9 betas?  I’m perpetually having them coming up with images from hours before which means when someone does press the button the snapshot I get is of something out of date.  As best I can tell everything at rings end is setup correctly - it’s currently set to snapshot every 5 mins.

**Comment by sybrendotinga** [comment]
> Has anyone had any luck with the snapshots updating at all, even with the new v9 betas? I’m perpetually having them coming up with images from hours before which means when someone does press the button the snapshot I get is of something out of date. As best I can tell everything at rings end is setup correctly - it’s currently set to snapshot every 5 mins.

In my case when the doorbell rings or motion is detected the snapshots are hardly ever (= never) accurate.

**Comment by DMBlakeley** [comment]
No luck. If you are within the "snapshot lifetime", snapshots are not updated. Watching the homebridge log it looks like "snapshot lifetime" is 600 seconds (10 minutes). Would think that a motion or doorbell event would initiate a new snapshot independent of "snapshot lifetime".

**Comment by dgreif** [comment]
If you are seeing stale snapshots, it's likely because you have a batter powered camera.  See https://github.com/dgreif/ring/wiki/Snapshot-Limitations for a full description of why this is the case.

**Comment by sybrendotinga** [comment]
> If you are seeing stale snapshots, it's likely because you have a batter powered camera. See https://github.com/dgreif/ring/wiki/Snapshot-Limitations for a full description of why this is the case.

I have a the doorbell wired, but it will techically count as "battery powered", right?

**Comment by sybrendotinga** [comment]
> If it has a battery but can optionally be wired, then it always acts like it is on battery. This is a limitation imposed by Ring and not something I can work around with my current knowledge of the API. I'm hopeful that snapshots will get better in the future, but for now this is the best I can do with the tools I have.

Thanks, and no problem, stream setup is speciaal quick that it is quicker to watch the stream anyway. Thanks for the hard work!

**Comment by durosity** [comment]
Aha that makes sense, mines a 1st gen powered by doorbell but does have a battery too!  At least it’s not something wrong at my end!  
Thanks for all the work on this, you’ve done a great job!

**Comment by paqpaqpaq** [comment]
Then again, it is a bit weird though, because in previous versions it would certainly update at request. On battery versions.

**Comment by dgreif** [comment]
@paqpaqpaq the behavior definitely changed when I switched from external to bridged cameras.  The reasons are well documented in the wiki: https://github.com/dgreif/ring/wiki/Snapshot-Limitations

I've made major improvements to live streaming in v`9.0.0` and am going to lock this thread to prevent a continuous trickle of random live streaming comments, as usually happens on any live streaming issue that is still open
