### ISSUE TITLE
Camera freshness overlay text can be incorrect initially within Home app

### ISSUE THREAD

**Issue by gondalez** [dgreif/ring#327]
# Bug Report

Thank you for the excellent plugin 🙏 

This bug gets me every now and again. I have a feeling it is a limitation of the home app / homekit api but I figure - don't ask, don't know :)

### Describe the Bug
When viewing the snapshot within the homekit home app, the time stamped on the image is incorrect. It says `now` or `3s` (etc) when the thumbnail is often hours old. 
After a while it updates, but it can be confusing to see now and the mailman is not there, but really he is 📫 

![image](https://user-images.githubusercontent.com/1468141/82287123-08eaaa00-99d2-11ea-86d4-d6d55d07aebb.png)

### To Reproduce
 - Configure a battery camera (mine is a ring video doorbell 2 with battery)
 - Open the Home app in iOS
 - Thumbnail shows and is of a long time ago
 - Overlay time in the Home app says now: 

 - Homebridge log says `[5/19/2020, 1:05:38 PM] [Ring] Snapshot for Front Door is still within its life time (356.361s old)` (for example)

### Expected behavior
- Overlay shows `n minutes ago` based on the cached snapshot age initially
- Then `now` if/when the refreshed thumbnail is shown

**Comment by tronny87** [comment]
I am having the same issue with a wired Ring Pro. Not sure when it started. Might've been a recent update. Opening the Home app shows "now" as the timestamp but the snapshot is from hours ago. Log does not show request for new snapshot and just has that " Snapshot for Front Door is still within its life time" over and over again.

I've been using this plug-in for over a year and I've never seen this happen before.

**Comment by gondalez** [comment]
I have a feeling it was introduced in https://github.com/dgreif/ring/commit/2482788 perhaps? 
Just a hunch though.

I do like that it shows the stale version more quickly now (I think it used to pause for quite a while before showing anything).

Having the correct time-ago would be 👌 ✨

**Comment by tronny87** [comment]
> I have a feeling it was introduced in [2482788](https://github.com/dgreif/ring/commit/2482788) perhaps?
> Just a hunch though.
> 
> I do like that it shows the stale version more quickly now (I think it used to pause for quite a while before showing anything).
> 
> Having the correct time-ago would be 👌 ✨

Having the correct "time-ago" is irrelevant if the snapshot would normally be updated within 2 seconds of opening the Home app. The issue here is you open the Home app, it says "now", then starts to count up seconds, while showing a snapshot from 8 hours ago. The snapshot will eventually refresh to an actual current one within 10-15 seconds. Not a normal behavior

**Comment by dgreif** [comment]
@gondalez you are completely correct that this recently changed.  When I set up cameras to be bridged instead of external accessories, it quickly became apparent that the _entire bridge_ is blocked while one of the cameras is waiting for a snapshot.  As a result, I implemented snapshot caching so that I can always return a snapshot _immediately_ rather than waiting for a new one from the server.  The end result is that you receive a stale snapshot at first (sometimes hours/days old, whenever you last got a notification or opened the home app), and then ~10-30 seconds later you will receive a new one that is up-to-date.  You can read more on my logic here: https://github.com/dgreif/ring/issues/311#issuecomment-626793633

**Comment by tronny87** [comment]
There are some (like me) that only use Homebridge for the Ring Doorbell. You should at least make it an option to have the previous functionality toggled. It is very misleading to open up the Home app and see a snapshot from 8 hours ago for up to 30 seconds.

**Comment by gondalez** [comment]
Thanks @dgreif for the reply and the detailed comments. That makes sense. 

Also thank you for that fix around bridge mode / blocking. I do appreciate the more immediate thumbnail response when using the home app. It feels snappy now.

Could a solution be to return a placeholder image to serve instead of the stale snapshot? Something with wording similar to "Waiting for fresh snapshot..." 🤔 

That text overlaid on the stale snapshot might be nice also, but I feel like image processing would complicate matters..?
