### ISSUE TITLE
Feature request - Add “hideChimes” option

### ISSUE THREAD

**Issue by Cardo1** [dgreif/ring#363]
# Feature Request

### Description
Just updated to 9.2.0 and have noticed all my Chimes have appeared in HK.  I appreciate some people might appreciate this, but I find this messy and would rather I could disable these.

### Describe the solution you'd like
Add a “hideChimes” option in the config, so these can be ignored in HK.

### Describe alternatives you've considered
Stuck them in the back of a room.  Not very elegant, though!

### Device data
N/A

**Comment by dgreif** [comment]
I decided to go a different route and added a new `hideDeviceIds` option in v`9.3.0`.  This allows you to hide _any_ device, instead of me needing to add a new `hideX` flag every time a new device is released.  See https://github.com/dgreif/ring/tree/master/homebridge#optional-parameters for details.  Hopefully that works for you!

**Comment by Cardo1** [comment]
Perfect, thank you.
