### ISSUE TITLE
Filtering/Caching specific Ring devices

### ISSUE THREAD

**Issue by chrisbarneslennar** [dgreif/ring#394]
# Feature Request

### Description
 I have a Ring account which manages upwards of 30 locations at any given time. These locations include both cameras and Alarms. Im only interested in managing the Alarms through Homebridge in order to automate arm/disarm scenes. is there a way to select location ID's and ONLY the specifically Alarm panels? Currently I load all locations (which immediately errors on max # of devices), grab the location ID's and then load only one location at a time and then hide all devices before re-adding other Loacions. I would think not caching unwanted/hidden devices would save resources. Theres probably some config Im not reading somewhere.

## Describe the solution you'd like
 selective managed devices 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

### Device data
  If you are requesting a new device be added to homebridge-ring, please follow the instructions in https://github.com/dgreif/ring/wiki/Data-Discovery and include the output here

**Comment by djm181** [comment]
Where is the limit on the number of devices coming from? As far as I am aware the ring client api doesn’t enforce any limit

**Comment by dgreif** [comment]
@chrisbarneslennar that sounds like an extremely unique setup. Is this for a business of some sort?  This is definitely outside the normal use case so I'm not extremely eager to add more configuration to support it.  I had a lot of requests early on to hide certain _types_ of devices, but that list kept growing and so did the config options.  Finally I put in a catch-all `hideDeviceIds` so that users could be specific about which ones they want to remove, and I wouldn't need to add any more one-off config options.  My best advice for your scenario would be to have your main homebridge with `locationIds` set to only the locations you have already configured `hideDeviceIds` for.  I would then create a _second_ homebridge setup to use specifically for fetching new location/device ids.  That way you don't interrupt your main instance every time you add a new location.

Alternatively, you could clone the `dgreif/ring` repo from github and run `npm install` followed by `npm run example`, which is does not tie into homebridge at all.  The example lists out all of your locations and devices with their ids, so you could find your new location/alarm ids in the output.

@djm181 the device limit comes from HomeKit, which enforces a max number of devices per bridge.  The limit is either 100 or 150 devices. See https://github.com/homebridge/homebridge#limitations

**Comment by chrisbarneslennar** [comment]
@dgreif Yea my company is the largest partner for Ring and I use all Ring products for security in my division. Ring says Im the single largest subscriber LOL And I know im the only one in the country using their product for this purpose. Its just nice to have all of my 50 sales areas alarms arm/disarm on schedule since alot of our sales people cant be bothered with arming their alarm when they leave for the night....
Is there any way I can hide a room from Homekit through Homebridge? I think by the time im done I will probably be bumping the limit again even with devices hidden...

**Comment by dgreif** [comment]
@chrisbarneslennar that's great info.  Do you mind if I ask which company it is?  Might be helpful with convincing Ring to give my homebridge plugin some official support.

I'll need a little clarification on what you mean by "hide a room from HomeKit".  Do you mean hiding the HomeKit room in the Home app? If so, I don't think that's possible from homebridge.

As far as device limit, your best bet is going to be having multiple homebridge instances.  Each "bridge" has a limit of 100 or 150 (not actually sure which it is) devices.  _Eventually_ homebridge may support a feature where you could split platforms into their own bridge automatically with a config option, but the main homebridge contributors aren't sure when that will actually be worked on.  For now you could run full homebridge instances with separate config files on your server.

**Comment by chrisbarneslennar** [comment]
The company is Lennar, which is the largest home builder in the US. We partner with Ring/Amazon to provide products to our homeowners and as such its an easy and affordable avenue for using the same products in our sales centers/model homes. I have about 140 models between about 45 communities. Each model had 2 cameras (ring pro, ring stick up elite), plus security station with applicable sensors/zones. So one community may have upwards of 22 cameras, with a security station with 40 zones attached. Thats my largest community of models with 12 models. The problem is really the cameras. Each one is listed as 3 distinct devices in homebridge. The camera, motion, and button or siren depending on model. Honestly I could care less about viewing cameras using homebridge/homekit. Im only in it to make my life easier by automating the security panels. Ring is one of the only companies that doesnt offer this natively in the app. If there was a way for HB to not poll Ring for cameras id be set! lol

**Comment by pogostickcowboy** [comment]
Sorry, I'm not understanding something. I face the issue on a smaller scale. I just addedthe plugin to Hoobs and it is pulling Ring devices from three houses and am across the family. I'd like trying to streamline all the devices. and remove locations/devices. Is there a tutorial for that?

**Comment by dgreif** [comment]
@chrisbarneslennar again, I appreciate the additional details.  After thinking about it some more, I think it would be useful to add another config option like `"onlyDeviceTypes": ["security-panel"]`.  This would be useful for me while testing so that I don't have my own long list of Ring devices in my test homebridge setup.  For your case, the example I gave would _only_ add the Ring alarms for each location.  Does that sound like what you need?  If so, I should be able to get this added some time in the next few days.

Beyond that, I'd suggest you set the following config options to trim down on polling and additional accessories within the alarm:

```json
{
  "hideAlarmSirenSwitch": true,
  "cameraStatusPollingSeconds": 0,
  "cameraDingsPollingSeconds": 0,
  "locationModePollingSeconds": 0
}
```

@pogostickcowboy the config options are all detailed in the readme: https://github.com/dgreif/ring/tree/master/homebridge#optional-parameters.  If you need additional help, I suggest you reach out in the #ring discord channel or open another issue on GitHub.

**Comment by chrisbarneslennar** [comment]
@dgreif "onlyDeviceTypes": ["security-panel"] would be fantastic. Would completely streamline the roll out and automation of security equipment. No more 'Location' specific equipment to deal with if a security-panel is not present. I would assume a location would just list zero devices if a security-panel was not present?

I am also speaking with one of our corporate technology development people. Since I am the only division in the country using this equipment they are very interested in how I make it work to streamline and automate the process. Eliminating everything but the panel from the process would be much cleaner and an easier sell. The idea would be to potentially roll out a preconfigured HOOBS kit to each division who uses this system in the future.

**Comment by dgreif** [comment]
`onlyDeviceTypes` add in v`9.5.0`.  Let me know how it works for you!  I'd still recommend setting the other config values I mentioned to prevent polling

**Comment by chrisbarneslennar** [comment]
Done and Done my friend! So good! Thank you so much! Now I dont have to show only locations. Tomorrow I will be installing 2 new alarms so im looking forward to watching the panels pop up without all the other accessory devices!!!
Now if I can sell the entire preconfigured package to our national corporate team we'll be in business. :)

**Comment by dgreif** [comment]
Glad to hear it’s working well! Good luck with the rollout

**Comment by mzuniga51** [comment]
I know this is an old thread but where can I get the generic device names for each Ring devices type so as to use them with "onlyDeviceTypes"?  So for instance I know if I want to include security panels it would be ["security-panel"] but I have no idea on naming conventions for other devices. Thanks!

**Comment by tsightler** [comment]
@mzuniga51 Probably the easiest thing to do is review the RingDevicesTypes which is the various first exported property in [ring-types.ts](https://github.com/dgreif/ring/blob/main/packages/ring-client-api/ring-types.ts).
