### ISSUE TITLE
Help with homekit notifications

### ISSUE THREAD

**Issue by sergoo-lbt** [dgreif/ring#404]
Guys, help! I can't understand. There is a ring of the first generation, with a battery, connected by a wire. When someone clicks a button from outside, I used to get a notification with an image. If you made a long tap on it, it opened a live broadcast. Now something has happened and the notification comes without a picture and I can not get it to appear again. If I disable the record motion function in the Ring app, the image in the notification appears again, but with the inscription snapshot is blocked. How do I get normal notifications with an image and without the label snapshot is blocked? Thank you all in advance! Do not judge strictly, I write through a translator, because I do not know English well🥺

**Comment by dgreif** [comment]
@sergoo-lbt I already covered this at length in #392, but I'll try to explain it again for you.  Since that camera has a battery, a new snapshot cannot be taken while it is recording.  It records when someone clicks the button, so no snapshot can be taken until that recording ends, which is ~30 seconds later.  When you disable motion recording, the plugin will always return a "placeholder" snapshot that says "Snapshots Blocked".  In previous versions, I would return a snapshot that said "Fetching Snapshot", but I had a ton of users who hated it and wanted it to be removed.  If you want the "Fetching Snapshot" placeholder back, you can downgrade to version `9.3.3` and just stay on that version.

**Comment by sergoo-lbt** [comment]
> @sergoo-lbt I already covered this at length in #392, but I'll try to explain it again for you. Since that camera has a battery, a new snapshot cannot be taken while it is recording. It records when someone clicks the button, so no snapshot can be taken until that recording ends, which is ~30 seconds later. When you disable motion recording, the plugin will always return a "placeholder" snapshot that says "Snapshots Blocked". In previous versions, I would return a snapshot that said "Fetching Snapshot", but I had a ton of users who hated it and wanted it to be removed. If you want the "Fetching Snapshot" placeholder back, you can downgrade to version `9.3.3` and just stay on that version.

Thank you very much! Now I understand everything! Is there no way to replace the snapshots blocked image with your own image?

**Comment by dgreif** [comment]
Nope, there is not currently an option to do that
