### ISSUE TITLE
Local recording

### ISSUE THREAD

**Issue by crashtestoz** [dgreif/ring#422]
# Feature Request

### Description

This more on an enquiry about local recording using this api
### Describe the solution you'd like
Is it possible to capture the video and record it on a QNAP by setting up the camera as a RTSP

**Comment by dgreif** [comment]
I don't have experience with the QNAP, but some other users have done a little research into RTSP.  Please take a look at https://github.com/dgreif/ring/issues/136#issuecomment-634516280.  This isn't a feature that I am looking to official support or give advice on, so that's the extent of what I can tell you on the matter.
