### ISSUE TITLE
Hi mate any chance you can get this to home assistant  please

### ISSUE THREAD

**Issue by terrafirma2021** [dgreif/ring#423]
# Feature Request
Hi mate sadly there is no support for android with home bridge so I kindly ask is there any way you can help to get this over to home assistant please.

Thank you very much

**Comment by dgreif** [comment]
My main focus with this project has been `homebridge-ring` and create a node api for other developers to use on platforms such as Home Assistant.  There is a MQTT addon that should get you most of the functionality in Home Assistant: https://github.com/tsightler/ring-mqtt-hassio-addon.  I haven't tried it out myself, but that's your best bet at this point as far as I know

**Comment by terrafirma2021** [comment]
Cheers for reply mate, is there any way of the ring alarm, alarm_triggered
being used by node red, ? Because i can only see a way using email
triggering.

Cheers

**Comment by tsightler** [comment]
I'm the author of the ring-mqtt bits mentioned above and that project is heavily used in the Home Assistant community as well as with Node Red and other MQTT based tools (honestly more than I ever imagined as the Docker build just reach 100K pulls and that's not even the primary deployment method).  Today it's not possible to get alarm state from the MQTT addon but it's on my feature list and I'm hoping to add it soon now that I finally seem to have a little time to work on the project again, please feel free visit the project at https://github.com/tsightler/ring-mqtt and provide feedback.

There are limitations to what can be done due to using MQTT vs a native Home Assistant component, but overall feedback indicates it's very reliable and I have quite a few enhancements planned over the coming weeks.

**Comment by dgreif** [comment]
Thanks for weighing in @tsightler!  Sounds like ring-mqtt would be the best place for this request.
