### ISSUE TITLE
Error: Unable to detect your ip address

### ISSUE THREAD

**Issue by Jborn4christ** [dgreif/ring#424]
# Live Streaming Issue

### Describe the live streaming issue
 Snapshota are coming through, but whenever i pull up live feed it immediately goes unavailable, and the logs report an issue with detecting Ip. No major changes to my setup since two days ago when all was well. Did have one ring location go offline for 12 hours which wreaked havoc, but it’s restored and everything else ring related is working fine in homebridge.

### Screenshots/Logs
 
![1F744429-0966-4743-921A-D693A5A4872F](https://user-images.githubusercontent.com/3494551/89594686-86c79000-d820-11ea-8695-411cd139c6aa.png)

### Recommended solution
 Worked through the wiki on this issue. Removed and re-added to the hubs (atv), rebooted server, removed ring plugin and reinstalled.

### Environment

 - Ring Camera: spotlight flood cam & ring video doorbell 
 - OS: windows server 2012 (config-ui)
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring (if applicable): latest
 - homebridge (if applicable): latest
 - hoobs (if applicable): [e.g. 0.4.50 or N/A]

**Comment by Tesla-P100FX** [comment]
Do you have a vpn turned on on your phone.   Snapshots work fine for me but if I have my von turned in it won't connect to the server to get the live stream.   Works fine with the vpn off.

**Comment by Jborn4christ** [comment]
Nope. No vpn on the home network, pc, or phone.

**Comment by Tesla-P100FX** [comment]
Hmmm.   Different issue

**Comment by dgreif** [comment]
@Jborn4christ This error is probably showing up because of some changes that I made in v`9.7.0`.  If you revert back down to v`9.6.0` do live streams work for you?  Is there anything unique about your setup on this computer, such as running homebridge in docker, or multiple network cards?  Anything that may prevent the plugin from determining the correct ip address?

**Comment by Jborn4christ** [comment]
@dgreif How would i best go about rolling back to the previous? Everything worked prior to updating the plug-in this week. Nothing weird about setup, no docket, no multiple cards, etc.

**Comment by Tesla-P100FX** [comment]
How do I revert back , that completely broke mine . No snapshots or video

**Comment by dgreif** [comment]
To roll back, you can run `npm i -g --unsafe-perm homebridge-ring@9.6.0`.  I'm working with a few of the other homebridge camera plugin developers to find the best way to get your current ip address, and apparently we aren't quite there yet 😅 . I'll try to look into it some this weekend and get another update out.

@Tesla-P100FX the changes in 9.7.0 should not have broken snapshots.  If you still have issues after reverting back to 9.6.0, consider opening a new issue and include some of your logs if you are seeing errors.

**Comment by Jborn4christ** [comment]
@dgreif @Tesla-P100FX That did it for me!! Thanks so much for all the work on this plugin!

**Comment by Tesla-P100FX** [comment]
Reinstalled and working now.   Still no video on VPN.

**Comment by Tesla-P100FX** [comment]
This is what happens when i try to initiate access to video

8/7/2020, 2:29:04 PM [Ring] ffmpeg stderr From Ring: Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
8/7/2020, 2:29:04 PM [Ring] ffmpeg stderr From Ring:   Metadata:
    title           : Talk
  Duration: N/A, start: 0.000000, bitrate: 64 kb/s
    Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
8/7/2020, 2:29:04 PM [Ring] ffmpeg stderr From Ring: Stream mapping:
  Stream #0:0 -> #0:0 (pcm_mulaw (native) -> aac (libfdk_aac))
8/7/2020, 2:29:04 PM [Ring] ffmpeg stderr From Ring: Output #0, rtp, to 'srtp://10.137.193.140:51086?localrtcpport=39683&pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.29.100
    Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.54.100 libfdk_aac
8/7/2020, 2:29:04 PM [Ring] Received stream data from Landcruiser (0.868s)
8/7/2020, 2:29:04 PM [Ring] Streaming active for Landcruiser
8/7/2020, 2:29:04 PM [Ring] ffmpeg stderr From Ring: size=       2kB time=00:00:00.52 bitrate=  32.0kbits/s speed=1.02x    
8/7/2020, 2:29:04 PM [Ring] Snapshot cached for Front Door (5.086s)
8/7/2020, 2:29:05 PM [Ring] ffmpeg stderr From Ring: size=       4kB time=00:00:01.03 bitrate=  30.2kbits/s speed=1.01x    
8/7/2020, 2:29:05 PM [Ring] ffmpeg stderr From Ring: size=       5kB time=00:00:01.48 bitrate=  29.6kbits/s speed=0.968x    
8/7/2020, 2:29:06 PM [Ring] ffmpeg stderr From Ring: size=       7kB time=00:00:02.05 bitrate=  28.3kbits/s speed=   1x    
8/7/2020, 2:29:06 PM [Ring] ffmpeg stderr From Ring: size=       9kB time=00:00:02.57 bitrate=  28.3kbits/s speed=   1x    
8/7/2020, 2:29:07 PM [Ring] ffmpeg stderr From Ring: size=      11kB time=00:00:03.11 bitrate=  28.2kbits/s speed=1.01x    
8/7/2020, 2:29:08 PM [Ring] ffmpeg stderr From Ring: size=      11kB time=00:00:03.27 bitrate=  28.2kbits/s speed=0.859x    
8/7/2020, 2:29:08 PM [Ring] ffmpeg stderr From Ring: size=      15kB time=00:00:04.33 bitrate=  27.9kbits/s speed=   1x    
8/7/2020, 2:29:09 PM [Ring] ffmpeg stderr From Ring: size=      16kB time=00:00:04.85 bitrate=  27.9kbits/s speed=   1x    
8/7/2020, 2:29:09 PM [Ring] ffmpeg stderr From Ring: size=      18kB time=00:00:05.39 bitrate=  28.0kbits/s speed=   1x    
8/7/2020, 2:29:10 PM [Ring] ffmpeg stderr From Ring: size=      20kB time=00:00:05.90 bitrate=  28.0kbits/s speed=   1x    
8/7/2020, 2:29:10 PM [Ring] ffmpeg stderr From Ring: size=      22kB time=00:00:06.39 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:11 PM [Ring] ffmpeg stderr From Ring: size=      24kB time=00:00:06.93 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:11 PM [Ring] ffmpeg stderr From Ring: size=      25kB time=00:00:07.41 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:12 PM [Ring] ffmpeg stderr From Ring: size=      27kB time=00:00:07.93 bitrate=  27.9kbits/s speed=   1x    
8/7/2020, 2:29:12 PM [Ring] ffmpeg stderr From Ring: size=      29kB time=00:00:08.47 bitrate=  27.9kbits/s speed=   1x    
8/7/2020, 2:29:13 PM [Ring] ffmpeg stderr From Ring: size=      30kB time=00:00:08.99 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:13 PM [Ring] ffmpeg stderr From Ring: size=      32kB time=00:00:09.47 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:14 PM [Ring] ffmpeg stderr From Ring: size=      34kB time=00:00:10.01 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:14 PM [Ring] ffmpeg stderr HomeKit Return Audio: Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:':
8/7/2020, 2:29:14 PM [Ring] ffmpeg stderr HomeKit Return Audio:   Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16
8/7/2020, 2:29:14 PM [Ring] ffmpeg stderr HomeKit Return Audio: Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> pcm_mulaw (native))
8/7/2020, 2:29:14 PM [Ring] ffmpeg  exited with code 0
8/7/2020, 2:29:14 PM [Ring] ffmpeg stderr From Ring: size=      36kB time=00:00:10.53 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:15 PM [Ring] ffmpeg stderr From Ring: size=      37kB time=00:00:10.94 bitrate=  27.7kbits/s speed=0.994x    
8/7/2020, 2:29:15 PM [Ring] ffmpeg stderr From Ring: size=      39kB time=00:00:11.55 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:16 PM [Ring] ffmpeg stderr From Ring: size=      41kB time=00:00:12.03 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:16 PM [Ring] ffmpeg stderr From Ring: size=      42kB time=00:00:12.57 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:17 PM [Ring] ffmpeg stderr From Ring: size=      44kB time=00:00:13.08 bitrate=  27.8kbits/s speed=   1x    
8/7/2020, 2:29:17 PM [Ring] ffmpeg stderr From Ring: size=      46kB time=00:00:13.57 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:18 PM [Ring] ffmpeg stderr From Ring: size=      47kB time=00:00:14.11 bitrate=  27.6kbits/s speed=   1x    
8/7/2020, 2:29:18 PM [Ring] ffmpeg stderr From Ring: size=      49kB time=00:00:14.59 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:19 PM [Ring] ffmpeg stderr From Ring: size=      51kB time=00:00:15.11 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:19 PM [Ring] Used cached snapshot for Landcruiser
8/7/2020, 2:29:19 PM [Ring] Loading new snapshot into cache for Landcruiser
8/7/2020, 2:29:19 PM [Ring] Used cached snapshot for Living Room
8/7/2020, 2:29:19 PM [Ring] Loading new snapshot into cache for Living Room
8/7/2020, 2:29:19 PM [Ring] Used cached snapshot for Side
8/7/2020, 2:29:19 PM [Ring] Loading new snapshot into cache for Side
8/7/2020, 2:29:19 PM [Ring] Used cached snapshot for Front Door
8/7/2020, 2:29:19 PM [Ring] Loading new snapshot into cache for Front Door
8/7/2020, 2:29:19 PM [Ring] Used cached snapshot for Garage Street
8/7/2020, 2:29:19 PM [Ring] Loading new snapshot into cache for Garage Street
8/7/2020, 2:29:19 PM [Ring] ffmpeg stderr From Ring: size=      53kB time=00:00:15.65 bitrate=  27.7kbits/s speed=   1x    
8/7/2020, 2:29:20 PM [Ring] Stopped Live Stream for Landcruiser
8/7/2020, 2:29:21 PM [Ring] Snapshot cached for Living Room (1.558s)
8/7/2020, 2:29:21 PM [Ring] Snapshot cached for Landcruiser (1.647s)
8/7/2020, 2:29:21 PM [Ring] Snapshot cached for Garage Street (1.546s)
8/7/2020, 2:29:21 PM [Ring] Snapshot cached for Side (1.972s)
8/7/2020, 2:29:23 PM [Ring] Snapshot cached for Front Door (3.985s)
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: pipe:: Connection timed out
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: Finishing stream 0:0 without any data written to it.
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: Output #0, rtp, to 'srtp://127.0.0.1:34917?pkt_size=188':
  Metadata:
    title           : Talk
    encoder         : Lavf58.29.100
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio:     Stream #0:0: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
    Metadata:
      encoder         : Lavc58.54.100 pcm_mulaw
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: (check -ss / -t / -frames parameters if used)
8/7/2020, 2:29:24 PM [Ring] ffmpeg stderr HomeKit Return Audio: Exiting normally, received signal 15.
8/7/2020, 2:29:24 PM [Ring] ffmpeg HomeKit Return Audio exited with code 255
8/7/2020, 2:29:29 PM [Ring] Used cached snapshot for Landcruiser
8/7/2020, 2:29:29 PM [Ring] Used cached snapshot for Living Room
8/7/2020, 2:29:29 PM [Ring] Used cached snapshot for Side
8/7/2020, 2:29:29 PM [Ring] Used cached snapshot for Front Door
8/7/2020, 2:29:29 PM [Ring] Used cached snapshot for Garage Street
8/7/2020, 2:29:30 PM [Ring] ffmpeg stderr From Ring: pipe:: Connection timed out
8/7/2020, 2:29:30 PM [Ring] ffmpeg stderr From Ring: size=      54kB time=00:00:15.98 bitrate=  27.7kbits/s speed=0.615x    
video:0kB audio:46kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 17.187666%
8/7/2020, 2:29:30 PM [Ring] ffmpeg stderr From Ring: Exiting normally, received signal 15.
8/7/2020, 2:29:30 PM [Ring] ffmpeg From Ring exited with code 255
8/7/2020, 2:29:39 PM [Ring] Used cached snapshot for Landcruiser
8/7/2020, 2:29:39 PM [Ring] Loading new snapshot into cache for Landcruiser
8/7/2020, 2:29:39 PM [Ring] Used cached snapshot for Living Room
8/7/2020, 2:29:39 PM [Ring] Loading new snapshot into cache for Living Room
8/7/2020, 2:29:39 PM [Ring] Used cached snapshot for Side
8/7/2020, 2:29:39 PM [Ring] Loading new snapshot into cache for Side
8/7/2020, 2:29:39 PM [Ring] Used cached snapshot for Front Door
8/7/2020, 2:29:39 PM [Ring] Loading new snapshot into cache for Front Door
8/7/2020, 2:29:40 PM [Ring] Used cached snapshot for Garage Street
8/7/2020, 2:29:40 PM [Ring] Loading new snapshot into cache for Garage Street
8/7/2020, 2:29:41 PM [Ring] Snapshot cached for Garage Street (1.438s)
8/7/2020, 2:29:41 PM [Ring] Snapshot cached for Side (1.531s)
8/7/2020, 2:29:41 PM [Ring] Snapshot cached for Living Room (1.62s)
8/7/2020, 2:29:41 PM [Ring] Snapshot cached for Landcruiser (2.096s)
8/7/2020, 2:29:44 PM [Ring] Snapshot cached for Front Door (4.576s)
8/7/2020, 2:29:49 PM [Ring] Used cached snapshot for Landcruiser
8/7/2020, 2:29:49 PM [Ring] Used cached snapshot for Living Room
8/7/2020, 2:29:50 PM [Ring] Used cached snapshot for Side
8/7/2020, 2:29:50 PM [Ring] Used cached snapshot for Front Door
8/7/2020, 2:29:50 PM [Ring] Used cached snapshot for Garage Street

**Comment by dgreif** [comment]
@Jborn4christ can you try version `9.7.2`? If streaming works on that version, you should be good to go

**Comment by Tesla-P100FX** [comment]
I was so excited that maybe you found it.  But alas no.   I tried both the different vpn's I use, Encrypt.me and NordVPN they still don't seem to allow the plugin to initiate a video stream.

**Comment by dgreif** [comment]
@Tesla-P100FX I was not trying to address your issue with this change.  Is there a particular reason you are trying to get this to work with a VPN?  Running your homebridge server on a computer that uses a VPN is definitely an odd setup.  Your homebridge server should be on the same network as the apple device that is trying to stream video, or the same network as your home hub (AppleTV/HomePod/iPad) if you want to stream remotely.  If you are running homebridge on a computer that you frequently use with a VPN, I suggest you try running homebridge on a different device, such as a Raspberry Pi, that can be kept on all the time and has local network access without VPN restrictions.

**Comment by Tesla-P100FX** [comment]
Oh sorry maybe I have not been clear the VPN is not on my homebridge it's on my iOS client.   Just using to stay secure online on my phone only.    Homebridge is a Raspberry Pi.

**Comment by dgreif** [comment]
That definitely adds some clarity @Tesla-P100FX.  Do you have a home hub (AppleTV/HomePod/iPad)? Technically, the stream should go from homebridge to the home hub in your case, and then Apple is responsible for figuring out how to get the video from your home hub to your phone.  I don't think there is anything I can do from the plugin to make it work if you have a home hub already.  I would note, the video stream is a secure encrypted video stream, so turning the VPN off when you stream won't make you any less secure from a streaming perspective.

**Comment by Tesla-P100FX** [comment]
Thanks, Yes have my Apple TV set up as a home hub ,   Maybe I will mess with my Apple TV configuration and see if there is something to do there.  I will let you know.

**Comment by Jborn4christ** [comment]
@dgreif 9.7.2 works perfectly. Most impressive.

**Comment by dgreif** [comment]
Awesome, glad to hear it!
