### ISSUE TITLE
forcing status update possible?

### ISSUE THREAD

**Issue by nuketownhf** [dgreif/ring#452]
Hello,
I'd like to manually start a refresh/status update to get the current battery level.
And it looks like that every of my 4 Ring Doorbells have different status update times. is this correct?
I hope this was clear.
Thank you very much

**Comment by dgreif** [comment]
Sorry, not extremely clear on what you are asking for here.  Are you using homebridge-ring, or interacting through code?

If you are referring to homebridge-ring, the status for all cameras is fetched every 20 seconds by default, as well as any time you open the Home app.  The battery level will be updated each time the status is fetched.

**Comment by nuketownhf** [comment]
I am working here with interacting through code.
Is cameraStatusPollingSeconds how I get fresh data?
The problem is that even after 5hours of camera usage the battery level is the same as previous, its not wired it's literally powered with batteries and I want to make a notification system that tells me every hour the battery level of all of my 4 ring doorbells.

Sorry if I wasnt clear enough.
Thanks

**Comment by dgreif** [comment]
If you want to trigger a fetch manually, you can call `camera.requestUpdate()` on any of the cameras, and it will update _all_ of the cameras.  This is because the endpoint that gives the status for a camera actually returns data for all of the cameras at once.  Unfortunately, I don't have a call you can make that returns a promise, so you would basically want to call `camera.requestUpdate()` and then wait a few seconds before grabbing the new value.  

Alternatively, you can set `cameraStatusPollingSeconds`, which will cause the status to be fetched periodically.   You could set this to a few minutes, or to an hour if you don't mind the battery levels possibly lagging behind a bit.

**Comment by nuketownhf** [comment]
Hi, basically im doing onData.subscribe now with cameraStatusPollingSeconds and it seems to work but the battery level still hasnt changed on the ring mobile app and api
From the start of this thread until now the battery level is still the same.
its been literally about 12+ hours showing same battery level and with that i mean 
Ring Doorbell A: 27%
Ring Doorbell B: 66%
Ring Doorbell C: 82%
Ring Doorbsll D: 86%
for literally 12+ hours now.

**Comment by dgreif** [comment]
That's not entirely surprising. If the batteries are meant to last a month or two, they would only drop a percentage or two per day. If you run the same process again in a separate terminal, do you get different results? If not, then the percentage simply hasn't changed

**Comment by nuketownhf** [comment]
Yes you are completely right.
I let my code running over night and i received the newest battery levels, seems like Ring Doorbell has a great Battery usage 👍 
Have a great day sir and thanks for this fantastic project!
