### ISSUE TITLE
Ring on Homepod not working

### ISSUE THREAD

**Issue by solbadguy2010** [dgreif/ring#453]
# Bug Report

### Describe the Bug
I get the error Message „process couldn‘t be completed“ when i enable or disable the new „ring on homepod“ feature on iOS14. 

### To Reproduce
 - Start Home App
 - Open Ring Camera Settings
 - Open Notifications
 - Activate „Ring on Homepod“

### Expected behavior
Homepod rings when doorbell button os pressed

### Screenshots/Logs
![A8CD834B-C201-437F-BE01-64781142CA08](https://user-images.githubusercontent.com/30244171/93571990-811fa700-f995-11ea-8384-3889e97319f8.png)

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
        {
            "refreshToken": "xxx",
            "hideDoorbellSwitch": false,
            "platform": "Ring"
        }
```

### Environment
![6194F740-ADE1-4F7D-89DB-B2A15BDD0E41](https://user-images.githubusercontent.com/30244171/93571972-79f89900-f995-11ea-89b4-5d7424f0d4ee.jpeg)

**Comment by dgreif** [comment]
This is an issue in the Home app, not with the plugin. Version 14 of the HomePod firmware has not been released yet, which seems to be breaking this feature, along with streams outside your network. Not sure why Apple hasn't released the update yet, but hopefully they do soon because a lot of HomeKit users are receiving these errors.

**Comment by solbadguy2010** [comment]
Thank you for clarification. I will wait for the update then.
