### ISSUE TITLE
Add option to rotate video from ring doorbell pro in homebridge-ring plugin

### ISSUE THREAD

**Issue by waywit** [dgreif/ring#504]
# Feature Request
Hi everybody, first of all I want to thank you for this great software and possibility to add my Rind Doorbell into HomeKit :-)

### Description
I newly own a Ring Doorbell Pro and I would like to mount the doorbell 90 degrees rotated to the left, because otherwise there will be no place for it. Inside the ring app the video is fixed, so I can use my iPhone in portrait mode and everything looks fine there. but in the home app the orientation of the video is always switched depending on my iPhone. Maybe an option can be added to support such rotated Ring Doorbells?

### Describe the solution you'd like
An option inside the home bridge-ring plugin to rotate the video coming from ring doorbell. Therefore maybe a ffmpeg option can be used:
Rotate 90 clockwise:
 - ffmpeg -i in.mov -vf "transpose=1" out.mov
For the transpose parameter you can pass:
0 = 90CounterCLockwise and Vertical Flip (default)
1 = 90Clockwise
2 = 90CounterClockwise
3 = 90Clockwise and Vertical Flip

But I have no idea how much performance such an option needs for a stream...

### Describe alternatives you've considered
Use the Ring App for the video?!?! I know that is not suggested to use the Rind Doorbell 90 degrees rotated, but in my case the doorbell is outside, but is not reached by any rain, so I will take the risk.

### Device data
My home bridge is on a Raspberry Pi 4 with 4GB RAM and I am using the Ring Doorbell Pro EU version.

**Comment by dgreif** [comment]
While this is definitely _possible_, it's a bit more complex because the _video_ portion of the stream for HomeKit does not currently pass through ffmpeg. Only the _audio_ portion goes through ffmpeg.  The setup for video streaming is already extremely complex, and I'd prefer to not make it even more confusing for this particular feature.  So far I have had one other user that had to mount their doorbell upside down (not exactly sure why), but I don't think this is a common issue.  I'm going to close this for now since I don't think there is a wide use case, but others are welcome to comment here if they also need this feature.

**Comment by woccam** [comment]
Hi thanks for the polite answer to my feature request, wich was basically the same ask. So if you count the requests:
+1 👍 
thanks for your fabulous work!
