### ISSUE TITLE
Upon motion at the door I receive repeated 4-5 times a picture refresh on my apple watch

### ISSUE THREAD

**Issue by arossmt** [dgreif/ring#546]
Hello,

thanks for the great work on this plugin.

1)
I am facing an issue that my Apple Watch receives always like 3-4-5 notifications with a camera picture in a row upon motion.

I would prefer to only get 1 notification with 1 picture instead of repeated ones. Is this configurable?

2)
I used to use doorbell motion to Apple TV which was great until I started to use Homepods. Can it be configured that Apple TV receives notification but Homepods not?

Many thanks
Thomas

Ring snippet from my config:
{
            "refreshToken": xxx,
            "hideLightGroups": true,
            "hideUnsupportedServices": true,
            "sendDoorbellMotionNotificationsToTv": false,
            "debug": false,
            "platform": "Ring"
        },

**Comment by dgreif** [comment]
1. Homebridge sends a single motion event to HomeKit, and then it is HomeKits job to distribute that event via notifications.  If you are seeing multiple pop up close together, it's likely a bug with iOS or WatchOS.  You can double check your logs to make sure there aren't multiple `Detected Motion` lines right in a row, but this is something I haven't tweaked in a while and it's been working reliably.
2. Homebridge has no way to specify which devices get notifications. That is all controlled on the HomeKit side.  I suggest you make a feature request to Apple for TvOS to start live stream on motion notifications since that's really what is missing.
