### ISSUE TITLE
Only a few cameras works after IOS 14.4 Beta 2

### ISSUE THREAD

**Issue by eliammarrero** [dgreif/ring#554]
Everything was fine on Hoobs until latest Apple Beta Update. Only a few cameras works after you kill the App. On Ring works fine but I have 15 cameras only five refresh on a random order.

**Comment by dgreif** [comment]
iOS betas often have bugs that cannot be accounted for from the homebridge side. Because this is so common, I can't address them unless you are seeing issues in a fully released version of iOS. Otherwise, I would constantly be chasing issues that I can't fix. You can always downgrade back to iOS 14.3 if you need reliable streams.

**Comment by eliammarrero** [comment]
Official iOS 14.4 has been released. Same behavior from the beta. It not able to handle multiple cameras. It's froze all after the third. On Ring app works fine.
