### ISSUE TITLE
Motion events not sent to HomeKit while motion scheduling turned on

### ISSUE THREAD

**Issue by fentonmatt** [dgreif/ring#555]
# Bug Report

### Describe the Bug
I seem to be only getting motion events in HK and them showing in my logs when motion scheduling is not enabled in Ring settings. When it is enabled, motion events do not show up and do not appear to be sent to HK either. But sometimes when motion scheduling is enabled, motion events _do_ show but only sometimes and it is not for every event. Is this normal behavior? Does it have to do with motion scheduling or is it something else? I want to say it is motion scheduling being on that disables them from being sent to HK and not appear in logs but seeing the occasional motion event during motion scheduling hours makes me think otherwise. Maybe somehow some events get past motion scheduling in the Ring API and are still sent to HK? When motion scheduling is not enabled, all events seem to be being sent to HK and appear in logs as expected. Automations linked to Ring motion events when they are not sent to HK or shown in logs seem to be affected as if HK is not receiving the event at all.

### To Reproduce
 - Trigger motion event with motion scheduling turned on and will not appear in logs or HK status.
 - Turn off motion scheduling and event appears as expected.

### Expected behavior
I expected all events to be sent to HK no matter the motion scheduling settings set in the Ring app. I then expected with motion scheduling enabled, no events would be sent at all during set times but some events get sent occasionally but not all of them. Most do not get sent when enabled it seems. 

### Homebridge Ring Config
{
            "refreshToken": "xxx",
            "alarmOnEntryDelay": true,
            "hideLightGroups": true,
            "hideDoorbellSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "nightModeBypassFor": "all",
            "beamDurationSeconds": 900,
            "platform": "Ring"
        }

### Environment
 - OS: [Raspbian GNU/Linux Buster (10)]
 - Node.js: [v14.15.4]
 - NPM: [v6.14.10]
 - homebridge-ring: [9.14.1]
 - homebridge: [v1.1.7]
 - hoobs: [N/A]

**Comment by dgreif** [comment]
@fentonmatt Sorry for the extremely delayed response. Are you still experiencing this issue? Are you by chance running a beta version of iOS or tvOS? I've heard that some of the latest Apple beta versions had issues with motion events

**Comment by fentonmatt** [comment]
@dgreif No worries at all. I know we all have our own lives and other things to attend to. So, I get it! But yes, I am still experiencing this issue. Only way to resolve it was to disable motion scheduling on the Ring app and now all events are being sent to HK as they should be. It seems that when that is turned on, those device's events with it turned on during their set timeframes are not sent to HK at all during the set times. I notice occasionally though for whatever reason one or two events do get sent but for the most part no events from Ring are sent to HK when those devices are set under a motion schedule during the scheduled time. I am not beta testing and have the latest software on my ATVs and iOS and Ring app. This is an issue for me because I have delay switches for my locks and lights that do not trigger correctly because of this but work perfectly during times the motion scheduling is not set to on.

**Comment by sjonez** [comment]
I'd like to add that I also see this issue but I think it's a limitation of the ring API.

I automate the the motion scheduling setting on each camera from OpenHAB in order to conditionally control when our phones receive motion notifications, however regardless of whether notifications are snoozed I'd still like to receive notifications via this API, but as mentioned it seems to prevent those as well. Only by looking at the ding history can you see that motion recently happened, you never see an active ding if scheduling is disabling notifications.

My workaround is to use IFTTT. I have no idea how that integrates with Ring but that appears to trigger motion regardless of the notification snooze schedule.

With IFTTT being event based rather than polling, I was wondering if @dgreif has ever looked into how they do that and if event-driven motion is something that would ever be possible with this API?
