### ISSUE TITLE
Odd behaviour with new Ring Door View

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring#56]
The snapshot provided in homekit is atleast 5-10 min old even though it says it was updated one second ago. 

It's also very slow to update when looking in the homekit app, takes aboout 30 second but it varies.

If i have not opened the app for an hour it says it was updated an hour ago when i last opened the home app, but that might be expexted behaviour

Just want to know if this is normal or something can be done to improve the homekit experience :)

Thanks for the great work on the plugin 👍

**Comment by dgreif** [comment]
@malmentm thanks for the info. It sounds like it’s behaving very similar to the standard Doorbell (doorbots_v3). It is possible that all of their battery powered cameras have the same behavior. It would be very helpful if you could help prove this theory. What I need to know is how quickly the Ring app can update snapshots. Just close and reopen the Ring app to see if you can get a new snapshot after a few seconds. Wired cameras seem to be able to get a new snapshot after about 30 seconds. Doorbot_v3 takes 10 minutes to get a new snapshot. How long does the delay appear to be for yours?

The hour-old image you mentioned is expected behavior. If Home isn’t open, the image won’t update until you open it again or get a notification.

**Comment by malmentm** [comment]
Yes, it seems like you're correct.  It takes 10 minutes for a new snapshot to appear in the ring app. A sidenot though is when i have motion sensor disabled in the ring app it never updaes.

**Comment by dgreif** [comment]
@malmentm give v`4.0.2` a try.  I added the same functionality that we use for `doorbot_v3`, which is to hand back a stale snapshot after a few seconds of trying to get a new one on this particular model.  Heads up, I renamed the npm package from `homebridge-ring-alarm` to `homebridge-ring` so you will need to uninstall the old one and install the new.  You config should update automatically on the first startup.

**Comment by nzbullet** [comment]
Hey @dgreif firstly nice work on this. Glad to see you're active in developing and supporting this, Thanks. Regarding the 10 min timeout and snapshots...whilst I understand that the image is stale when looking at the Home app, is it expected that the image would get a refresh when there is motion or a doorbell press? (this is on the doorbell_v3). I ask as the snapshot in the notifications is still the 'stale' image and not a snapshot taken when there is motion or a ring.

All good if not, just wondering what to expect. 
Cheers

**Comment by dgreif** [comment]
@nzbullet I made some updates to the logic for when to use stale vs fetch a new snapshot.  Give v`4.0.7` a try.  If there has been a snapshot in the last 10 minutes, then it will use the stale snapshot even if there is motion/ding.  If it has been more than 10 minutes since your last snapshot, motion/ding should pull a new snapshot.

**Comment by dgreif** [comment]
@malmentm can you confirm that v`4.0.7` is working better with the Door View Cam?

**Comment by malmentm** [comment]
@dgreif Yes, it seems much more resposive now! Thanks!
