### ISSUE TITLE
Unhide hidden accessories 

### ISSUE THREAD

**Issue by Peterjohnwood** [dgreif/ring#608]
I’ve added the new outdoor siren to my ring alarm installation. When my homebridge alarm instance starts I can see that the siren is a hidden accessory. Is there a way to unhide hidden accessories?

Thanks

pete

![PNG image](https://user-images.githubusercontent.com/56692030/114269406-c9201d00-99fe-11eb-8532-3e110ffc23f1.png)

**Comment by dgreif** [comment]
It's hidden because it is a new accessory that isn't currently supported.  I'd be happy to add it if you can follow the directions in https://github.com/dgreif/ring/wiki/Data-Discovery.  The downside with the siren, though, is that there may not be much that you can do with it.  HomeKit supports Speakers, but the Home app itself does not.  What functionality would you expect if the siren did show up?

**Comment by dgreif** [comment]
@Peterjohnwood are you still interested in getting the siren added?

**Comment by Peterjohnwood** [comment]
Hello mate, sorry, I thought I’d responded to this thread. I’m happy to close this... after thinking about it I could think of anything that went ahead available. Thanks for getting back to me
