### ISSUE TITLE
Snapshot as Live View so Camera doesn’t say Not Responding

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [dgreif/ring#63]
Have you thought about this any further? Anyway you could implement this? Until live view is figured out, unless you are close to getting live view to work?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dgreif** [comment]
@d0n4v4nb3ck3r I think this is a good idea, but I have not put any time toward it yet.  I've been focused on 2fa and getting my Ring debug environment set up a little better.  I'm getting close to done with both of those and then I can do a little investigation toward snapshots for live view.

Real live view is completely possible, but requires a ton of work unless someone can recommend a good library that has done most of the heavy lifting.  I'm not currently planning to work on it any time soon.

**Comment by d0n4v4nb3ck3r** [comment]
@dgreif I totally understand, wish I knew how to code so that I could help you! Thanks for everything you have done!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ifeign** [comment]
@dgreif does something like jssip not offer the functionality you need?

**Comment by dgreif** [comment]
@ifeign just started digging into jssip and found this gem... https://github.com/versatica/JsSIP/issues/571.  Looks like that one is off the table. There are still a few others I can try

**Comment by ifeign** [comment]
Haha wow, people got heated over that.

**Comment by omerdn1** [comment]
@dgreif how about [sip.js](https://github.com/onsip/sip.js)?

**Comment by dgreif** [comment]
@omerdn1 unfortunately that one uses websockets as the transport (instead of UDP), which does not work with the Ring SIP servers.  There are some threads/forks by people who have tried to add UDP but it all looks pretty stale.

I'm currently playing around with the [sip](https://github.com/kirm/sip.js) module and having some limited success 😶.  I actually got a successful connection between the Blink client for windows and my Ring camera today (audio only), so that is a huge step in the right direction.  I'm trying to recreate that scenario with the sip module and running into a weird response from the ring server.  I can talk to it, it's just telling me it doesn't like my request.  The sip module is actually making the whole process more complicated, so I might just start throwing straight UDP messages at the server and not use any sip library.

Once sip is figured out, it's a matter of getting RTP to connect to homebridge/HomeKit.  That part _looks_ easy, but could be a whole separate hurtle.  I don't want to get everyone's hopes up, but it is looking _possible_ at this point. 🤞No promises...but for now I'm going to close this issue in favor of #35 since that's where I'm focusing my effort.  I will post there if I have any more updates.
