### ISSUE TITLE
"Virtual" Doorbell for Ring Doorbell Motion Events

### ISSUE THREAD

**Issue by hipstersmoothie** [dgreif/ring#678]
# Feature Request

Would it be possible to create an option that create a second "virtual" doorbell for tvOS automation?

### Description

Create an option that creates a second "virtual" doorbell for tvOS automation.

### Describe the solution you'd like

I like seeing the motion events on my Apple TV, but the chime is pretty annoying. A "virtual" doorbell that's only used for tvOS would solve this:

- normal doorbell - shows up on TV, trigger chime
- virtual doorbell (motion) - shows up on TV, doesn't trigger chime

### Describe alternatives you've considered

Playing around with notification setting in the various apps, but nothing is really what I want

**Comment by dgreif** [comment]
@hipstersmoothie I can understand where you are coming from with this request, but this feature isn't something I want to invest any more time in. The simple fact is that Apple should be adding this feature to TvOS, rather than homebridge plugins hacking around their current limitations. I think it's a good feature for them to add, and I recommend you submit that feedback to them.

**Comment by hipstersmoothie** [comment]
That's a void I'd rather not shout into 😅 Would you accept a PR for this?

**Comment by hipstersmoothie** [comment]
Actually look like this should be added in the next release

https://www.reddit.com/r/HomeKit/comments/nx53te/you_can_turn_on_camera_motion_notifications_in/
