### ISSUE TITLE
Flood/Freeze Sensor as two separate virtual devices

### ISSUE THREAD

**Issue by YPyltiai** [dgreif/ring#684]
Hi,

I am not sure it is possible but it would make sense to create Ring Flood/Freeze sensor in Homekit as 2 virtual devices instead of grouped sensor as it is done now.

There are multiple reasons for that:
1. Freeze sensor is not supported and it displays as occupancy sensor. If you have actual occupancy sensors, this displays alongside actual occupancy sensors and doesn’t look good.
2. There is no way to kick freeze sensor out of Homekit without removing flood one.
3. Ideally we should be able to use “hide device” setting to hide one of two sensors as needed.

I also think the setting “Hide unsupported devices” should be hiding Freeze sensor too. It is in fact unsupported device that is presented as something else.

Hope the reasons are valid enough to separate those if that is technically possible.

Thanks!

**Comment by dgreif** [comment]
Hey @YPyltiai, thanks for providing good detail in your issue.  The only thing I don't really understand is why this is worth changing.  Is it simply because it "doesn't look good" with the other occupancy sensors?  You are correct that a "Freeze sensor" is not a supported service, which is why I chose to use a different option (Occupancy sensor in this case).  I don't think this should be hidden with the "hide unsupported" option because that is intended for accessories that have an existing service, but literally don't work with the Home app, and this sensor does _work_, it's just not technically the right service being used.

**Comment by YPyltiai** [comment]
Hi @dgreif , the main reason why I don't like "occupancy" sensor for this type of functionality is that if you have actual occupancy sensors, those will be active most of the time if you are home. In this case Freeze sensor just gets lost among those. I would much more prefer having it as "contact" sensor type, as those are "off" most of the time and do not interfere as much with "freeze" sensor.

Good example - if you have Ecobee with temp/movement/occupancy sensors around the house, you will have at least one of those triggered at all times. Contact sensors on the other hand are less often active (on).

Saying that, for any safety/security features I think it is always better to have the sensor type that is less likely to be "active" at all times, as it just prevent visibility for the one that may be indicating hazard.

Hope that helps.

**Comment by dgreif** [comment]
I guess "visibility" doesn't strike me as a critical feature for sensors.  Are you often looking at the Home app to see what sensors are active?  What makes more sense to me is triggering alerts and automations when the freeze sensor is activated.  Is there a reason that wouldn't suit your needs?

**Comment by YPyltiai** [comment]
@dgreif it does but having it as "contact sensor" solves both use cases, so I still find it a bit more optimal than current state with "occupancy sensors". Having occupancy sensors as "on" is more of a normal state of those sensors because they are "on" way more often and can stay "on" for a long time. Having contact sensors as "on/open" reflect an outlier state (something open that is supposed to be closed).

I agree with you that "hiding" it may be an overkill but I would change the type to "contact sensor" at least.

**Comment by dgreif** [comment]
@YPyltiai changing it to a contact sensor isn't a simple change.  Because it's a different service from HomeKits perspective, it would break all automations tied to the current occupancy sensor when users update.  This would require a breaking release of the plugin, and I'm not confident users would understand the ramifications.  I'm still not seeing a lot of value in the change, so it doesn't seem worth the risk.

**Comment by YPyltiai** [comment]
@dgreif , BiC is a valid reason to hold on it, I guess. I will probably just patch it on my side then. Thanks for looking into it!

**Comment by dgreif** [comment]
Sounds good!  I appreciate your willingness to patch it on your side.  I hate saying "no", but I find it's becoming necessary more often.  Not many users are willing to tweak things themselves, so you rock!
