### ISSUE TITLE
Unable to see light switches

### ISSUE THREAD

**Issue by AdamMHardy** [dgreif/ring#75]
I’ve got all cameras and ring alarm connected but I’m unable to see my paired Leviton z-wave switches within the home app. Are these devices supported?

**Comment by dgreif** [comment]
I have a GE z-wave switch connected to my Ring alarm and it works great via the `homebridge-ring` plugin.  The Leviton ones should work just as well.  First, pair the z-wave switch with the Ring app and verify that you can see/control it there.  Then restart your homebridge server so that `homebridge-ring` picks up the new device.  Let me know if you have done that and are still having issues.

**Comment by AdamMHardy** [comment]
I have paired 3 switches with the Ring Alarm hub and am able to control them via the Ring app and using my Alexa devices.  I tried rebooting the server and also removed the and readded the bridge to Homekit (after deleting the persist folder within the Hombridge directory).  The camera works great on the new version by the way! But I'm still unable to see these switches for some reason

**Comment by dgreif** [comment]
I only had multi-level switches implemented.  I'm guessing your switches are simple on/off (non dimmer) switches which is why they aren't showing up.  Just added the logic to handle this type of switch in v`4.4.0`.  Give it a try and let me know if that fixes it for you.

**Comment by AdamMHardy** [comment]
Thanks for the quick turnaround! I've upgraded the plugin and tried everything I can think of short of uninstalling and reinstalling Homebridge, but I'm still unable to see the switches.  I can try a complete wipe later, if needed, but is there something I should be adding to the config to get these to show? The only preference I've set to True is hiding the siren.

**Comment by dgreif** [comment]
I wouldn't recommend reinstalling homebridge as it is not likely to fix your issue.  I think this is an issue with the `homebridge-ring` plugin not recognizing the device type for that particular switch.  Here's what I need you to do:

1. Clone the ring repo by running `git clone git@github.com:dgreif/ring.git` 
2. Go into the `ring` folder that command created and run `npm i` to install dependencies
3. Open `ring/examples/example.ts` and put your credentials in at the top.  Replace `env.RING_EMAIL!` with `'me@place.com'` and same for password.
4. Run `npm run example`
5.  You should see your locations, cameras and other devices logged.  Please post back with everything after the `Location xxx has the following xx device(s):` line.  What I need is the device type that Ring is reporting for those switches, which will be in that output.

If you could also send me the model number for the Leviton switches as well so that I have an idea of what they are capable of (dimmer, etc.).  Sorry for the trouble, hopefully we can get these working for you soon!

**Comment by AdamMHardy** [comment]
These are the 3 switches that show up in that list. I'm not sure if the identifiers are sensitive so I've replaced them with [device_id] - if you need the actual values as well, let me know

- [device_id]: Driveway Lights (switch)
- [device_id]: Patio Lights (switch)
- [device_id]: Floodlights (switch)

Thanks for all of your help so far

**Comment by dgreif** [comment]
That's exactly what I needed from the logs, thanks for walking through all of that!  The device type is simply `switch`, which is what I had guessed it would be.  The code that I added in v`4.4.0` _should_ have added those three switches into homebridge/HomeKit.  If you restart your homebridge server, you should see a log of all the devices that the plugin has recognized.  It would look something like this:

```
[Ring] Initializing Ring platform...
[Ring] Configuring cached accessory SOME-UUID Driveway Lights
[Ring] Configuring cached accessory SOME-UUID Patio Lights
[Ring] Configuring cached accessory SOME-UUID Floodlights Lights
...
```

Can you check to see if those three switches are logged in that output?  If not, please double check that you got updated to v`4.4.0` or higher.

**Comment by enriquecaballero** [comment]
Thought I'd chime in here. I just installed 4.5.0 and I'm getting this error when it attempts to add my regular on/off switches:
```
homebridge    | [7/28/2019, 9:54:47 PM] [Ring] Adding new accessory switch Backyard Light
homebridge    | [7/28/2019, 9:54:47 PM] [Ring] Error connecting to API
homebridge    | [7/28/2019, 9:54:47 PM] [Ring] TypeError: Cannot read property 'UUID' of undefined
homebridge    |     at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:49:35)
homebridge    |     at Switch.getService (/homebridge/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:19:28)
homebridge    |     at Switch.registerCharacteristic (/homebridge/node_modules/homebridge-ring/lib/homebridge/base-accessory.js:22:30)
homebridge    |     at new Switch (/homebridge/node_modules/homebridge-ring/lib/homebridge/switch.js:13:14)
homebridge    |     at allDevices.forEach.device (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:118:21)
homebridge    |     at Array.forEach (<anonymous>)
homebridge    |     at RingPlatform.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:96:28)
homebridge    |     at Generator.next (<anonymous>)
homebridge    |     at fulfilled (/homebridge/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:4:58)
homebridge    |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
The switches work great via the Ring app and also via Alexa.

**Comment by enriquecaballero** [comment]
I previously had 4.3.0 and everything worked except for the fact that I couldn't see my on/off switches.

**Comment by enriquecaballero** [comment]
Just downgraded to 4.4.0 and I'm also getting the same error.

**Comment by dgreif** [comment]
🤦‍♂ thank you for the error log.  I had a typo which was causing it to error.  `4.5.1` should work

**Comment by enriquecaballero** [comment]
Dude, awesome. This plugin is amazing. Thanks!

**Comment by dgreif** [comment]
I take it that worked? 😁

**Comment by enriquecaballero** [comment]
Yup! Like a charm 🙌

**Comment by dgreif** [comment]
Awesome! Sorry for the goof on that.  It's a lot easier when I have one to test with, but they only z-wave I have is a dimmer.  Thanks for testing it out!  @AdamMHardy it should work for you as well now.  Let me know if you run into any more issues or find another device that isn't supported yet.

**Comment by AdamMHardy** [comment]
That was it! All is working for me as well - thanks!
