### ISSUE TITLE
Unable to add door bell

### ISSUE THREAD

**Issue by black01gt** [dgreif/ring#76]
I have installed and Homebridge logs show my door bell but in HomeKit it doesn't show up when I try to add it.

7/27/2019, 9:20:50 AM] [Ring] Adding new accessory lpd_v2 Front Door
[7/27/2019, 9:20:50 AM] Front Door is running on port 64231.
[7/27/2019, 9:20:50 AM] Please add [Front Door] manually in Home app. Setup Code:

**Comment by dgreif** [comment]
Make sure your phone and homebridge server are on the same network.  If they are and you still can't find the camera with HomeKit, then you may have to change some settings on your router to allow the devices to see each other.  Every network is different so I won't be able to give you exact guidance.  See #58 for another user who got this fixed by reaching out to his ISP (assuming you have a router/modem provided by your ISP).

**Comment by black01gt** [comment]
Thanks. That worked.

**Comment by black01gt** [comment]
I spoke to soon. looks like the port changes every time Homebridge restarts?

**Comment by dgreif** [comment]
That’s correct, homebridge will choose a random port each time it starts up. I’m not sure how your network is set up, but maybe you could open all ports for that one device. This is a homebridge/HAP node level thing and isn’t something I can control from the homebridge-ring plugin

**Comment by dgreif** [comment]
@black01gt did you get everything working?  It sounds like this is specific to your network rather than an issue with this plugin

**Comment by black01gt** [comment]
Yes thank you everything is working great.
