### ISSUE TITLE
No devices Found: Ring Video Doorbell (Wired)

### ISSUE THREAD

**Issue by mpugerz** [dgreif/ring#771]
# Bug Report

### Describe the Bug
 No devices found for location when using the Ring Video Doorbell (Wired)

### Screenshots/Logs
![image](https://user-images.githubusercontent.com/24664492/134095573-55f99922-cd46-4283-a300-a16f92ec0039.png)

### Environment

 - OS: Raspbian
 - Node.js: v14.17.6
 - NPM: 6.14.15
 - ring-client-api: v9.21.2

**Comment by tsightler** [comment]
This is the wrong place to open an issue with ring-mqtt, you should open a request on the actual [ring-mqtt project page](https://github.com/tsightler/ring-mqtt).  While the ring-mqtt project does use the api library from this project, the problem above is unlikely to be related to ring-client-api.  Actually, the most likely cause of the issue is that you've failed to enable camera support as it is disabled by default.
