### ISSUE TITLE
Audio from iPhone to ring doorbell is muffled, only in Homebridge Ring

### ISSUE THREAD

**Issue by rfiorentino1** [dgreif/ring#801]
### Streaming Issue

If I start a live view from the Ring app itself, audio from the doorbell, and to the doorbell when I speak to someone is clear in both directions. However, when streaming through the Home app via this plugin, audio is clear from the doorbell to my phone, but I sound very muffled coming out the doorbell to the person at the door. I'm assuming this is either an issue with the Ring API and some kind of encoding setting/limitation, or an issue with the fmbeg library being used to encode, neither of which are likely in your control, but I wanted to just double check, and was genuinely curious. Not a show stopper, just an observation.

### Proposed Solution

Possibly check library being used for video/audio quality, and/or settings in the Ring API and see if there is a higher bit rate, etc available?

### Environment

Homebridge

### What operating system are you on?

Mac

### Honesty Time

- [X] I swear this is worth your time!

**Comment by dgreif** [comment]
This is likely due to encoding, but I'm limited on options between what Ring supports and what ffmpeg supports.  I've spent a lot of time on streaming, but I don't plan to put more time into it beyond bug fixes if it totally breaks.  You are welcome to open a PR if you find some configuration that works better for audio encoding.  Otherwise, I recommend using the Ring app if you plan to speak through the camera for the best experience.

**Comment by rfiorentino1** [comment]
Haven't looked too much further into this, but wanted to quickly add hear that whatever the nest camera plug-in is using works great, and sounds the same as using the Nest app, both ways, from the doorbell and from the iOS device. I haven't looked into the configuration of the plug in itself to see what the encoding settings are, but thought it might be helpful for you to know. :-)
