### ISSUE TITLE
 Ring Alarm Panic Button

### ISSUE THREAD

**Issue by techoin** [dgreif/ring#83]
This plugin is amazing. I have ring pro, spotlight cams and alarm. Everything works as expected. Thanks @dgreif

Is it possible to expose Ring Alarm Panic Zwave Button accessory as homekit switch something similar to Siren? Have not tried it yet but from description it seems currently not supported

**Comment by dgreif** [comment]
@techoin glad to hear the plugin is working well for you!  You are correct that the Ring Alarm Panic Button is _not_ currently supported.  I don't have one to test with, but I'm also hesitant to add functionality that will call the police/fire department.  I know a lot of cities have a fee from the police if you have a false alarm, and I wouldn't want anyone pointing fingers at me for liability...

Can you walk me through when you think it would be useful via HomeKit rather than just opening the Ring app for the panic button?

**Comment by techoin** [comment]
@dgreif Let me give you quick scenario of what I am trying to accomplish

I have DSC security system with envisalink IP gateway. I am able to access everything in homekit through envisalink homebridge plug-in. I can arm/disarm and monitor each wired sensor. Its professionally monitored through a third party monitoring service.   

I also have Ring doorbell pro, multiple spotlight and floodlight cameras and Ring Alarm. I got Ring Alarm mainly because their Ring protect plus subscription which is required for video recording of cameras also included alarm monitoring as well. 

Ring alarm is good but upon giving another thought I decided not to spend money on adding ring sensors to each door and window specifically when my existing DSC system is wired, reliable and works perfectly in homekit. So I am trying to find ways to trigger Ring Alarm whenever my DSC Alarm gets triggered. That way,  I can keep all existing wired sensors and can get rid of other professional monitoring I have. 

Since triggering alarm state is not available in homekit, I was looking at possibility of exposing Panic Button.  As it is nothing but a zwave button with predefined actions, I was hoping it is possible.

**Comment by dgreif** [comment]
@techoin I think that is a valid use case.  It will be tough for me to implement since I don't have a panic button, and I'm not sure how it works to "call it off" if you press it.  I'm still deep in the SIP/live stream stuff, but I will circle back to this in a few days.

**Comment by dgreif** [comment]
@techoin I'll make you a deal...you send me $35 via paypal (sponsor link at top of GitHub) and I'll buy a panic button to test this with and get it added to the homebridge plugin

**Comment by techoin** [comment]
@dgreif deal! sent you $35. lets hope this works. thanks again

**Comment by dgreif** [comment]
Not to be picky but...I didn't see any donations come through 😕

**Comment by dgreif** [comment]
Got it 💵 , ordered ✅.  Should have it added to the plugin sometime late next week.  Thanks for the panic button!

**Comment by techoin** [comment]
sure thing..looking forward for it.

**Comment by dgreif** [comment]
@techoin just wanted to give you an update.  I received my panic button and got it set up today (thanks again for that!).  Luckily my ring alarm is in practice mode right now due to a billing issue on Ring's end, so I was able to play around with triggering the alarm lots of different ways.  In the end, I have code that will allow me to dispatch either **police** or **fire** 🎉.  This code actually does not need to be tied to the panic button, so everyone using the plugin will get the option to add switches for these.  I'm out of time for today, but wanted to get your thoughts on how we should display these switches in Home.  I could add them as new `Panic Burglar` and `Panic Fire` switches under the `Ring Alarm` device, but that device already runs into issues with Siri when people try to turn on their alarm and accidentally get their siren instead.  Alternatively I could generate new, fake devices in HomeKit that would be stand alone switches.  My fear with that is that you could bump them by accident, without the need to click into a group of devices. 
 Another option would be to put these two switches in a single fake device, which would require you to click into it before you could turn either one on.  Any thoughts on how we should display them?  By the way, I plan to make these an opt-in option so that users have to be intentional about adding a slightly dangerous button.

**Comment by EarthRise626** [comment]
I think putting them both in a fake device would be best. It would ensure a more intentional trigger and preserve your good will with the local departments. ;)

**Comment by techoin** [comment]
@dgreif thats great..really appreciate your efforts

yes putting them in fake device will better. I just read the below details on ring website for different alarms. I assume you are able to trigger burglar alarm and smoke/fire alarm? In those cases emergency contacts are called first.

Upon reading below it seems Panic button was wrong choice as it dispatches authorities first.

---------------------------------------------------------------------------------
What happens after my Ring Alarm sends an emergency signal?

Depending on the type of emergency, there are different protocols in place.

**Burglar Alarm:** Emergency contacts are called first before the emergency responders are dispatched. If any emergency contacts are reached, they can confirm the emergency or cancel a false alarm by telling the monitoring center the verbal password. If no emergency contacts can be reached, the monitoring center may leave automated voicemails and then dispatch the police.

**Smoke/Fire Alarm** (triggered by Smoke & CO Listener or First Alert Smoke/CO Alarm): Your first emergency contact is called first before the emergency responders are dispatched. The remaining contacts on your list are called, and if anyone can be reached, they are notified of the emergency and may be given the opportunity to cancel if it's a false alarm. If none can be reached, the monitoring center may leave automated voicemails.

Carbon Monoxide (CO) Alarm: Emergency responders are dispatched first, and cannot be canceled even in the event of a false alarm. Next, all emergency contacts are called. If any contacts can be reached, they are notified of the emergency. If none can be reached, the monitoring center may leave automated voicemails.

Panic Button Alarm: Police are dispatched first, then the list of emergency contacts are called until someone answers. If any contacts can be reached, they are notified of the emergency and may be able to cancel if it’s a false alarm. If none can be reached, the monitoring center may leave automated voicemails.

Flood & Freeze Sensor:Your primary contact will receive an automated call from the monitoring center. If the primary contact doesn't answer the phone, the second emergency contact will receive an automated call.

----------------------------------------------------------------------------------

**Comment by dgreif** [comment]
@techoin thanks for posting those descriptions, they are very helpful!  My plan right now is to use the "Burglar Alarm" and "Smoke/Fire Alarm" functionality, each as their own switch within a single fake device called "Panic".  Does that match the functionality you wanted to see added?

**Comment by techoin** [comment]
@dgreif yes that is perfect. I can then use my DSC system burglar alarm to trigger ring burglar alarm and my nest protect smoke sensors to trigger Ring smoke/Fire alarm.

**Comment by dgreif** [comment]
@techoin v`5.5.1` should be ready to roll with panic buttons!  You have to set `showPanicButtons: true` in your config to get them to show up as I want these to be opt-in.  You will receive a call from Ring before authorities are dispatched, so you can probably give them a try to make sure everything works.  Turning the switch off should disarm the alarm (but you will still get the call).   Thanks again for the Panic Button!

![image](https://user-images.githubusercontent.com/3026298/62827576-666de280-bb86-11e9-9e1c-29be846f0594.png)

**Comment by techoin** [comment]
@dgreif excellent work. just updated and tested few times with self monitoring and worked perfectly. I will perform few more tests tomorrow afternoon and confirm. Thanks again.

**Comment by techoin** [comment]
@dgreif all good...everything is working as expected. thanks again.

**Comment by dgreif** [comment]
@techoin glad to hear it's working well for you!  I think this is a great addition to the plugin, so thank you for the request!

**Comment by pcziesch** [comment]
Hi @ll question for function of panic button do the button turm on all sirens or hust the sirene of the base station ?
