### ISSUE TITLE
Issue with Home.app-based Grouping of Ring Solar Pathlights When Using "Include in Favorites"

### ISSUE THREAD

**Issue by afroeagle** [dgreif/ring#841]
# Bug Report

### Describe the Bug
With the homebridge-ring Option "hideLightGroups" true or false, the following issue occurs within the Home.app: if I configure a Home.app-based light group of my 6 Ring Solar Pathlights, and then add that new Home.app-based Group to the Home.app "Favorites" by activating "Include in Favorites", all of a sudden 7 devices are added to Favorites (all 6 lights and the Home.app-based group). 

If the Ring-based light group is enabled ("hideLightGroups" set to false), this issue does not occur. However, the Ring-based light group only allows for "On/Off" functionality, where the Home.app-based light group allows setting the light level in addition to "On/Off".

### To Reproduce
 - Start Homebridge
 - Do as described in detail above
 - See issue

### Expected behavior
I expect the Home.app-based light group to be able to be added to Favorites by itself.

### Screenshots/Logs
Please let me know if you need these items and which ones would help.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

            "refreshToken": "XXX",
            "hideLightGroups": false,
            "avoidSnapshotBatteryDrain": true,
            "beamDurationSeconds": 32767,
            "platform": "Ring"

```

### Environment

 - OS: macOS Monterey 12.1
 - Node.js: 16.13.1
 - NPM: 8.3.0
 - homebridge-ring: 9.23.0
 - homebridge: 1.3.8
 - hoobs: N/A

**Comment by dgreif** [comment]
The grouping and "Favorite" behavior you described is completely controlled by the Home app.  If it seems like a bug that all lights from the group are added to favorites, I suggest you open an issue with Apple directly.

I'm guessing your suggested alternative here is that the group provided with `hideLightGroups: false` also support setting the level (instead of just on/off).  The Ring api only supports setting levels for individual lights and not by groups, so this isn't a feature that I can easily add.  I would love to hear more about your use-case that requires you to adjust a group level, but I don't think this feature would be worth the effort.

**Comment by afroeagle** [comment]
Thank you for your response and thanks for your work.
