### ISSUE TITLE
Homekit Secure Video

### ISSUE THREAD

**Issue by solbadguy2010** [dgreif/ring#860]
# Feature Request

### Description
Homebridge and the Ring Plugin does not support HSV until now

### Describe the solution you'd like
Homebridge just released V1.4 which supports HSV. Please add this feature to your plugin

### Describe alternatives you've considered
No

**Comment by rgerr** [comment]
+1

**Comment by tomsteenbakkers** [comment]
+1

**Comment by JSVarga** [comment]
+1

**Comment by galoiring** [comment]
Hoping you do so , or at least assist us retrieving the stream agrees for the "Homebridge Camera Ui" plugin.
thanks.

**Comment by YPyltiai** [comment]
+1. Worth a POC for sure

**Comment by adavison007** [comment]
Would be an awesome feature addition

**Comment by Stetocasa** [comment]
+1
This will drastically increase sales of Ring devices

**Comment by dgreif** [comment]
I'm considering it, but it might be a while if I decide to do it.  In the mean time, would you mind explaining _why_ you want HKSV? What are the benefits over the Ring app and having Ring store the video clips?

**Comment by BradMcGonigle** [comment]
One of the biggest advantages for doorbell owners (which I imagine is a very large majority of Ring owners/users) would be the ability to take advantage of facial recognition. https://support.apple.com/en-us/HT207314

**Comment by solbadguy2010** [comment]
> I'm considering it, but it might be a while if I decide to do it. In the mean time, would you mind explaining _why_ you want HKSV? What are the benefits over the Ring app and having Ring store the video clips?

My biggest plud would be, that i have then all the streams in the home app. Next to ring i have three more cams with direct HSV support and pay apple anyway. I dont know if this works, but i could maybe then downgrade my ring plan to the free one.

**Comment by Stetocasa** [comment]
> I'm considering it, but it might be a while if I decide to do it.  In the mean time, would you mind explaining _why_ you want HKSV? What are the benefits over the Ring app and having Ring store the video clips?

I think that I can speak as typical requester of HKSV integration in HomeKit.
In the market we have multiples cameras "HomeKit native" but video doorbell are expensive (more that 200$)
We have already 10$ month for HKSV service, we don't want to pay other money to Amazon just for the video door camera

**Comment by galoiring** [comment]
I think the facial recognition if will work will be great..
easier for now is just (if possible) to give us the address for the feed , and we will put it in the camera ui home bridge plugin..

**Comment by metalheadz** [comment]
Why do I want this integration? Because I already pay for icloud storage and I dont want to pay ring just to store videos on another platform...

**Comment by stefro** [comment]
I agree to all above comments. It would be great to have the video stored to iCloud, just as the other camera's do. 
Also the face recognition that is included in HKSV is really good. You should get a notification like "Mike rang the doorbell" and even see these labels in the timeline.

**Comment by adavison007** [comment]
In order of importance to me:

- Facial Recognition
- All videos with stored history available via one app (rather than going into various apps)
- iCloud storage already paid for (remove Ring storage costs
- iCloud Storage more secure than Ring Storage

**Comment by MoTechnicalities** [comment]
> +1
> This will drastically increase sales of Ring devices 

I don't care if Amazon's sales increase, but they didn't do what they promised us when they very first introduced the ring products! They promised us HomeKit compatibility, but rebounded on that promise because they are making good money on their video storage plan in direct competition to HomeKit. I went with Ring in the beginning (7 cameras) because I believed their promise! Adding HomeKit iCloud storage through Homebridge may finally be the way to make Amazon pay for going back on their promise! Make it happen!

**Comment by Moskvitch** [comment]
> > +1
> > This will drastically increase sales of Ring devices
> 
> I don't care if Amazon's sales increase, but they didn't do what they promised us when they very first introduced the ring products! They promised us HomeKit compatibility, but rebounded on that promise because they are making good money on their video storage plan in direct competition to HomeKit. I went with Ring in the beginning (7 cameras) because I believed their promise! Adding HomeKit iCloud storage through Homebridge may finally be the way to make Amazon pay for going back on their promise! Make it happen!

With Matter/Thread interoperability well underway, they just might make it compatible, in a rather convoluted way....

**Comment by jadenv** [comment]
[Scrypted](https://github.com/koush/scrypted) just [announced support](https://www.reddit.com/r/HomeKit/comments/saazzi/scrypted_adds_support_for_ring_homekit_secure/) for Ring + HomeKit Secure Video! 🎉

I just booted up the Scrypted Docker image on the same Raspberry Pi that I'm also running Homebridge on to try it out. It works flawlessly so far complete with facial recognition/package detection, all recordings showing up in the Home app, and everything else you would expect from a native secure video camera!

Since most of the Scrypted implementation is actually based on functionality from this repo, it seems like it would not be a ton of required effort to also bring this implementation to Homebridge now that it supports HKSV with the latest v1.4.0 release. 🚀

**Comment by putthegundownkinkade** [comment]
> [Scrypted](https://github.com/koush/scrypted) just [announced support](https://www.reddit.com/r/HomeKit/comments/saazzi/scrypted_adds_support_for_ring_homekit_secure/) for Ring + HomeKit Secure Video! 🎉
> 
> I just booted up the Scrypted Docker image on the same Raspberry Pi that I'm also running Homebridge on to try it out. It works flawlessly so far complete with facial recognition/package detection, all recordings showing up in the Home app, and everything else you would expect from a native secure video camera!
> 
> Since most of the Scrypted implementation is actually based on functionality from this repo, it seems like it would not be a ton of required effort to also bring this implementation to Homebridge now that it supports HKSV with the latest v1.4.0 release. 🚀

how fast do you find streaming ring video through scripted compared to using this plugin?

**Comment by Stetocasa** [comment]
I don't understanding if Skrypt could be integrated in this Ring plug-in in a more easiest way compared potential new development

**Comment by tbelcher** [comment]
As others have stated, integration with existing storage (iCloud), one app to access all cameras, and facial / animal / package recognition are at the top of the list for wanting this.

Tim

**Comment by dgreif** [comment]
I really appreciate the feedback from everyone!  Here's a quick recap:
* Facial & animal recognition
* Everything in one app (Home instead of Ring)
* Remove redundant clouds subscriptions, only paying for iCloud and not Ring

I see the benefit!  However, I also see a big liability as a developer.  I do not want to be personally responsible for users finding a way around the Ring subscription, which in the end costs Ring real money.  I have long held the opinion that Ring has _exceptionally fair_ pricing for both their hardware and their subscription fees.  Beyond taking away the subscription income, HKSV would continue to _cost_ Ring money because all of the streams will still flow through their servers.  

With that in mind, my official position is that I **will not be adding HKSV** support to the homebridge-ring plugin.

For anyone that still wants to use HKSV with Ring, I suggest you check out Scrypted.  They already support HKSV and will continue to improve the experience over time.

**Comment by BradMcGonigle** [comment]
I know others won't like this conclusion but I totally respect your decision around this how you communicated it above.

**Comment by metalheadz** [comment]
lol Costing Ring money... Are you serious? If Ring was fair, it would give their users choices, like many other similar products supporting homekit natively... With all smart products managed by amazon, the only good thing is the initial hardware pricing..After, you are literally forced to pay to use the product normally or you become the product yourself.

In fact its sad because I still wanted to use your plugin and having everything on homebridge.. Heading back to scrypted!

**Comment by solbadguy2010** [comment]
Hi Dustin,
thank you for your Answer and thought. I get what you say.
Wouldn't it be possible to allow adding HSV by making a Ring plan mandatory in the plugin? Do not know if this is possible.

**Comment by Stetocasa** [comment]
> lol Costing Ring money... Are you serious? If Ring was fair, it would give their users choices, like many other similar products supporting homekit natively... With all smart products managed by amazon, the only good thing is the initial hardware pricing..After, you are literally forced to pay to use the product normally or you become the product yourself.
> 
> 
> 
> In fact its sad because I still wanted to use your plugin and having everything on homebridge.. Heading back to scrypted!

Can you coach me how use Skrypted trough homebridge?

**Comment by Stetocasa** [comment]
> I really appreciate the feedback from everyone!  Here's a quick recap:
> 
> * Facial & animal recognition
> 
> * Everything in one app (Home instead of Ring)
> 
> * Remove redundant clouds subscriptions, only paying for iCloud and not Ring
> 
> 
> 
> I see the benefit!  However, I also see a big liability as a developer.  I do not want to be personally responsible for users finding a way around the Ring subscription, which in the end costs Ring real money.  I have long held the opinion that Ring has _exceptionally fair_ pricing for both their hardware and their subscription fees.  Beyond taking away the subscription income, HKSV would continue to _cost_ Ring money because all of the streams will still flow through their servers.  
> 
> 
> 
> With that in mind, my official position is that I **will not be adding HKSV** support to the homebridge-ring plugin.
> 
> 
> 
> For anyone that still wants to use HKSV with Ring, I suggest you check out Scrypted.  They already support HKSV and will continue to improve the experience over time.

From one side I appreciate your feedback and I respect your decision (you are the owner of this plug-in).
From other side I don't understand which was your expectation from this survey.
Everybody provided relevant and strong feedback that not let you change your initial idea to not adopt HKSV

I just was awaiting the implementation, your request generated in me some hope that now I need to forget

**Comment by putthegundownkinkade** [comment]
This is a great idea and I’d be happy to pay ring to let me use it with HKSV

**Comment by MoTechnicalities** [comment]
@dgreif 

RE: Your Recap

> I see the benefit! However, I also see a big liability as a developer. I do not want to be personally responsible for users finding a way around the Ring subscription, which in the end costs Ring real money.
> HKSV would continue to cost Ring money because all of the streams will still flow through their servers.

Your answer is laughably ironic! Because NOW, You really have give me the final solid reason to begin replacing my Ring products!
Any-which-way you look at it, there is going to be a loss for Ring!
There are some really good TRUE HomeKit options now.

**Comment by dgreif** [comment]
> With all smart products managed by amazon, the only good thing is the initial hardware pricing..After, you are literally forced to pay to use the product normally or you become the product yourself.

@metalheadz there is a reason that Ring products are cheap compared to others, and that is because they expect to earn money from you over time from the subscription.  That's not Amazon being some cruel overlord..it's just a business model.

> Wouldn't it be possible to allow adding HSV by making a Ring plan mandatory in the plugin

@solbadguy2010 this would be possible, and is one of the options I've considered.  However, I don't think there is a lot of value in me doing the work to add HKSV with restrictions when Scrypted already has a completely unrestricted implementation.  

> Can you coach me how use Skrypted trough homebridge?

@Stetocasa I have not personally used Scrypted yet, but I'm sure they have a good tutorial for getting set up on their website.

> Your answer is laughably ironic! Because NOW, You really have give me the final solid reason to begin replacing my Ring products!

@MoTechnicalities if HKSV is an important feature to you, I think you _should_ consider replacing your Ring products.  No matter how well Scrypted gets integrated, it will almost certainly be a worse experience when compared with the "true" HomeKit options.  Ring cameras all stream through the Ring servers, so there will always be some delay between when HKSV is told of a motion event and when the recording actually starts.  True HKSV cameras do all of this on your local network and should give you a much better experience. Ring cameras simply weren't designed to function in this way, and are optimized for storing video on Rings servers. This is a part of my reasoning for not supporting this feature - it's never going to be a perfect experience.  And if it's not perfect, I will continue to get issues opened from users wondering why it's not perfect.  Homebridge is a bandaid to "bridge" the gap until manufacturers add HomeKit support themselves, but it does not claim to be a perfect solution.

Again, I appreciate all of the feedback and hope that everyone can understand where I'm coming from.  I will continue to support and update `homebridge-ring` to the best of my ability for smart home automation purposes, but the camera integration will never be perfect.  Scrypted is aiming to make the best experience possible with the cameras, and I suggest you give it a try if that's your main use case for `homebridge-ring`.

**Comment by galoiring** [comment]
I have no problem with you decision and I would try to use Scrypted , but I need the video source address to use it and I can't find it in the plugin (only Token)

**Comment by solbadguy2010** [comment]
@galoiring
Wrong thinking. You remove this plugin from homebrige. Then you set up Scrypted (For example as a Docker on your Homebridge Pi) and install the Ring and Homekit Plugin inside it.

Scrypted and Homebridge do coexist and dosn‘t interact. You do not need a stream.

**Comment by galoiring** [comment]
oh sorry I wanted to use camera UI home bridge plugin ,
its easier to config...
and for them I need the address (I know that the ring plugin using the FFmpeg under the hood)

**Comment by Stetocasa** [comment]
> @galoiring
> 
>
> 
> Scrypted and Homebridge do coexist and dosn‘t interact. You do not need a stream.

I cannot find any tutorial or wiki to make both working on same PI :(

**Comment by solbadguy2010** [comment]
@stetocsde
Because there is no tutorial as far as in know. 
What i did:
1. Backup Homebridge
2. Download the latest Bullseye based Homebride image from homebridge.io
3. Restore backup and apt update and upgrade everything. 
4. Follow the Scryted Wiki to install Docker, the Scryted Docker Image and run it (i did not use Docker Compose).

https://github.com/koush/scrypted/wiki/Docker

Now you can access the scrypted Management Console. The Docker Container is running parallel to Homebridge. 
5. Install Watchtower to Auto-Update the scypted Docker image.

**Comment by putthegundownkinkade** [comment]
I haven’t tried it yet but this looks promising 

https://www.reddit.com/r/homebridge/comments/ra980o/how_to_install_dockerscrypted_on_official_raspi/


Will

**Comment by solbadguy2010** [comment]
@putthegundownkinkade 
Thats basically what i described above with extra stuff you don‘t need. But yes, Homebridge -> install Docker -> Run Scrypted Docker Image is the way

**Comment by adavison007** [comment]
Once you have Scripted installed, do you still also use the Homebridge-Ring Plugin within home bridge aswell? ? I don't want to move away from this plugin it works great, but I do want HKSV.. please advise.

**Comment by solbadguy2010** [comment]
I uninstalled the HB Plugin. Only using Scrypted currently. I think you can use both parallel, but you will then have the camera two times in home

**Comment by galoiring** [comment]
yes but I don't want to format my pi (after all the configuration for zigbee2mqtt etc..)
so I try to install the camera ui plugin for homebridge ...
the only problem is where to find the source address to enter it manually ..
it will be much easier then install docker

**Comment by solbadguy2010** [comment]
You also can do an upgrade of your existing Raspberry Pi OS. But it will not work without a soecific Ring Plugin that use the Login of the service.
As dustin already explayned video stream always go to Amazons Servers, then back to you. There is no local Stream.

**Comment by galoiring** [comment]
yes.
but the ring plugin also use FFmpeg so internally it has a video address link..
might be cool to be able to obtain this link and connect it to the camera UI plugin , so it won't necessary to install docker etc..

**Comment by dgreif** [comment]
@galoiring there is no rtsp address for Ring.  The `homebridge-ring` plugin does use ffmpeg for audio transcoding, but the video packets are forwarded from Ring servers to HomeKit manually.  You _cannot_ connect to the camera from `homebridge-camera-ui`.  Scrypted is your only option if you want HKSV.

**Comment by galoiring** [comment]
oh this is sucks...
thanks any way ...

**Comment by adavison007** [comment]
The Most annoying thing about this is that I purchased the Ring Pro door bell in 2016 as it was announced by ring that they would support homekit!!!! So actually it's Ring that has let us all down.

@dgreif  is there anyway you would change your mind on HKSV? maybe do a different plugin that clearly states no support for HKSV? or perhaps make people tick a checkbox in the config that says if HKSV is enabled they agree to no support? I for one would be more than happy to pay for this feature knowing the experience would not be the best.. 

Yours hopefully.

**Comment by dgreif** [comment]
I'll clearly state it here.  **I will not add HKSV to this plugin**.  If you want HKSV, please use Scrypted.

Locking this thread to avoid more of the same comments. I know users are disappointed, but I feel strongly that this is the right decision.  I built this plugin to make home automation with Ring easy, and that's what I will continue to focus on.
