### ISSUE TITLE
Homebridge Not working on 4G after 5.0 updates

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#91]
I'm not sure if this is a coincidence... but since the 5.X update when i'm not on the local network Homebridge hub is not responding on 4G... all other hubs are like Hue, Tado etc... I have rebooted my RPI, Apple TV, router etc and no change...

See screen shot, all other hubs working on homekit on 4G but not Hoobs (homekit) since ring 5.X update. thoughts, ideas?

![IMG_5534](https://user-images.githubusercontent.com/47482260/62331647-6c8fff00-b4b4-11e9-94a0-2991567320a9.png)

**Comment by dgreif** [comment]
Try downgrading to v`4.5.2` if that fixes it, upgrade back to 5+ and see if it breaks again.  Let me know how it goes

**Comment by dgreif** [comment]
@adavison007 do you happen to have the `homebridge-neato` plugin installed?  I just realized it was killing everything in my homebridge except for camera feeds (ironically).  Looks like @ifeign already opened an issue for it https://github.com/naofireblade/homebridge-neato/issues/42

**Comment by EarthRise626** [comment]
I am having a similar (but potentially unrelated?) problem. My camera feeds are showing as unavailable (“No Response”) in the Home app when on LTE. The Ring Alarm devices perform just fine and my other HomeBridge devices are responsive.

**Comment by dgreif** [comment]
I’m having the same issue (and am also on iOS beta). If I am off my home network I get No Response for all homebridge devices. Not just the ring plugin. And a lot of the devices still function even tho the way No Response. I reverted back to 4.5.2 and still had issues. It may be related to the alarm changes I made a few versions back, or it could be a different plugin causing issues. Unfortunately I am going to be unavailable for testing and fixes until Wednesday next week. If anyone can pin down what version of the plugin made things break, or find a different plugin that is causing the issue, I would really appreciate the help. I was so happy with all the progress this morning and then this issue totally ruined the mood. I would really really appreciate some help from the community on this issue so that I can get it resolved quickly when I’m available again next week. Thanks for reporting it @adavison007

**Comment by ifeign** [comment]
> @adavison007 do you happen to have the `homebridge-neato` plugin installed? I just realized it was killing everything in my homebridge except for camera feeds (ironically). Looks like @ifeign already opened an issue for it [naofireblade/homebridge-neato#42](https://github.com/naofireblade/homebridge-neato/issues/42)

could you add your logs to my issue on homebridge-neato? I'm still confused as to why it happened.

**Comment by Sunoo** [comment]
I just did some quick testing, and everything is working for me off-network, though things were a bit slow (which I seem to remember being about this speed often off-network).

I’m guessing it must be some other plugin or configuration that’s causing the trouble for the impacted users.

**Comment by dgreif** [comment]
I thought it was the neato plugin but it still happened after removing that one. I have a bunch of other but I didn’t try removing each of them individually.

**Comment by EarthRise626** [comment]
For what it’s worth in narrowing things down, the only plugins I have installed are:

homebridge-config-hi-x
homebridge-dummy
homebridge-platform-wemo

And this plugin of course. :)

My dummy switches and Wemo plugs work just fine via HomeBridge when off network, as well as all of the Ring Alarm devices. For me, it is only the cameras and associated devices that report “No Response”.

**Comment by Sunoo** [comment]
I have very few plugins in my installation, just this, WeatherPlus, and Harmony.

**Comment by dgreif** [comment]
@EarthRise626 sounds like your issue is different than mine and @adavison007. You might just need to remove and re add your cameras.

**Comment by EarthRise626** [comment]
@dgreif I had removed and added the cameras again earlier today after the upgrade to 5.0.0 (I’ve since upgraded to the latest release). I’m wondering if the issue might be that an iCloud backup has not run since that reconfiguration. I manually triggered an iCloud backup that is running now. Once complete, I will retest the off-network access and check back in with the results!

**Comment by adavison007** [comment]
@EarthRise626 thanks, how do you do the forces icloud backup???

@dgreif plugins I have are

-dummy
- harmony
- ring
- ZP
- SmartThings 
- Tado

**Comment by adavison007** [comment]
@dgreif how do I downgrade or install a specific version?

**Comment by dgreif** [comment]
‘npm i -g homebridge-ring@4.5.1’  

It looks like the only overlap we have are dummy and ring and I don’t think dummy had an update recently so it is probably ring...try going back several versions and see if you can find one that fixes the issue. I tried 4.5.2 and it still gave me No Response for everything when I switched to 4G.

**Comment by adavison007** [comment]
I spoke to Hoobs, they said they think I need to remove the home bridge from HomeKit and re do it with a new user name and code?/

**Comment by d0n4v4nb3ck3r** [comment]
> I spoke to Hoobs, they said they think I need to remove the home bridge from HomeKit and re do it with a new user name and code?/
> 

On the way bottom of the page on the Hoobs ui, there is a reset HomeBridge. If you want to try doing this.


I am not having any of these issues and have iOS beta and only the ring plugin on HomeBridge.

**Comment by EarthRise626** [comment]
@adavison007 Instructions for how to manually start an iCloud backup can be found at https://support.apple.com/kb/PH12520?locale=en_US&viewlocale=en_US

**Comment by adavison007** [comment]
Ok, so deleting Homebridge from homekit, then doing nothing else but then adding, all works!!!!

**Comment by adavison007** [comment]
> Ok, so deleting Homebridge from homekit, then doing nothing else but then adding, all works!!!!

and live video is immediate, intact faster than ring app!

**Comment by dgreif** [comment]
Mine started working today without changing anything. No idea what wrong but it think we are all good! Have a good weekend everyone!
