### ISSUE TITLE
Hide By Device ID not working for cameras

### ISSUE THREAD

**Issue by alockbox** [dgreif/ring#924]
I have the latest version installed on the latest version of HomeBridge. I have the device ids from the log (ex 77aa2ec0-4271-4897-a84c-c3bbc6c12625) and verify in the HomeBridge config they are showing up, but Home app still shows the cameras and loads snapshots.

**Comment by YPyltiai** [comment]
As a workaround - you can create a user in Ring for Homebridge specifically and grant them limited permissions to the devices you want there. This way you can just cut the camera access to that account and it will just work.

Also security-wise this is better since you can always revoke access to that account if anything goes wrong.

**Comment by dgreif** [comment]
I just tried this out and it seems to be working as expected (at least on the latest beta version).  You can grab the camera id from the homebridge logs, in the section that says something like `Configuring cached accessory 794fe292-xxxx-43dd-9723-xxxxx Camera Name`.  Note, this won't be the same ID as what is reported from the Ring API, this is the id that is generated and used by homebridge only.
