### ISSUE TITLE
Snap Shots

### ISSUE THREAD

**Issue by adavison007** [dgreif/ring#932]
Running the latest version and homekit snap shot are not updating.. see below, any ideas

<img width="1244" alt="Screenshot 2022-05-10 at 22 14 12" src="https://user-images.githubusercontent.com/47482260/167723150-6a1eb2a7-322f-478c-ab57-84aa724009ff.png">
?

**Comment by dgreif** [comment]
Interesting.  Do you have rich notifications turned on for that camera?  Are you on a paid plan?

**Comment by adavison007** [comment]
Hi, yes I had rich notification on some cameras, does that make a difference for this plugin? I’ve turned them off now.


Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 10 May 2022, at 22:57, Dusty Greif ***@***.***> wrote:


Interesting. Do you have rich notifications turned on for that camera? Are you on a paid plan?

**Comment by dgreif** [comment]
v11 leverages the images from rich notifications, so you will want to turn them _on_ for all of your cameras

**Comment by adavison007** [comment]
I also get this error when rebooting the server..



On 11 May 2022, at 15:39, Dusty Greif ***@***.***> wrote:


v11 leverages the images from rich notifications, so you will want to turn them on for all of your cameras

**Comment by soulcook** [comment]
I get this problem all the time with both my cameras. It's very frustrating.

They both have rich notifications enabled.

Snapshots can take a anything from 30 seconds to 20 minutes to load in the Home app. They never load rapidly (but snapshots on all my other cameras do). There's no problem with my network connectivity – snapshots on my Nest device load rapidly, Ring snapshots load rapidly in the Ring app, and streaming video loads rapidly in the Home app. But snapshots take forever to load in the Home app.

I get this message intermittently:
[5/14/2022, 12:56:10 AM] [Ring] Failed to reach Ring server at https://app-snaps.ring.com/snapshots/next/4426543.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

Any ideas?

**Comment by dgreif** [comment]
@soulcook see https://github.com/dgreif/ring/wiki/Snapshot-Limitations.  There is a difference between loading snapshots just for viewing them in the Home app, vs snapshots that should be delivered with motion/ding notifications.  If your cameras are battery powered, then you will hit the error you logged above any time you try to _view_ a snapshot while the camera is streaming.  However, on v11 you should get snapshots in your notifications reliably.

**Comment by dgreif** [comment]
> I also get this error when rebooting the server..

@adavison007 I don't see the error in your message..

**Comment by soulcook** [comment]
Thanks for the quick reply.

Based on the information you've kindly provided, and thinking about this, I
now see that the problem is *not* retrieving snapshots from Ring, but
rather delivering the snapshots from Homebridge to the Home app.

I've just been experimenting, and I've discovered something very strange.
In the Home app on Macs (I've tried two, on both ethernet and WiFi) the
initial Ring snapshots are retrieved immediately and they refresh every 10s
just like the snapshots from my other cameras. But on iOS (iPhone and iPad)
it can take ages to get the initial Ring snapshots (while the other cameras
are quick) and then they refresh only every 60s, while the other cameras
still refresh every 10s. This is on the same local network as Homebridge –
the other cameras (also Homebridge, via FFMPEG) seem to know this, the Ring
plugin seems not to.

Weird, huh? Any idea what's going on?

Thanks again

Paul

**Comment by Hackashaq666** [comment]
Aside from my ring doorbell, my other cameras use the camera-ffmpeg plugin which provides initial snapshot updates very quickly and then every 15 seconds for my 3 rtsp cameras. The ring camera does not update its snapshot in ios home app until after a livestream is opened, and then they update every 60 seconds. Thanks!

**Comment by soulcook** [comment]
Yes, this is almost identical to my experience, except that the Ring
doorbells do usually acquire a snapshot eventually without opening a
livestream if you wait long enough.

FWIW my Nest doorbell also refreshes only every 60s in the Home app. All
the direct IP cameras refresh every 10s.

**Comment by adavison007** [comment]
So, my Ring Homebridge cameras randomly update… they used to always refresh every 10 seconds… but since the last 12 IOS updates they do not update… 

The only error message I currently have is 

"Failed to reach Ring server at https://app-snaps.ring.com/snapshots/next/12323721.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds…”

This happens with and without rich notifications turned on.


Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 16 May 2022, at 12:24, soulcook ***@***.***> wrote:


Yes, this is almost identical to my experience, except that the Ring
doorbells do usually acquire a snapshot eventually without opening a
livestream if you wait long enough.

FWIW my Nest doorbell also refreshes only every 60s in the Home app. All
the direct IP cameras refresh every 10s.

**Comment by homersdonut** [comment]
I had to downgrade to 9.24 to get snapshot notifications back.

**Comment by EddieDSuza** [comment]
I can confirm with version 9.24 - there are no issues in the logs and the Ring doorbell works as intended in Apple HomeKit with rich notifications both on my TV and iO devices.

**Comment by pottisatish** [comment]
I just updated the plugin to the latest version 11.0.5 and since then I am seeing the same issue constantly - 
Failed to reach Ring server at https://app-snaps.ring.com/snapshots/next/59097283.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds...

On my iphone all the ring cameras show as "No response" with no snapshots and I cant see the live feed. But on my Mac I can see snapshots and notifications coming to my TV (through Apple TV) and able to stream the videos..

I keep getting "Could not complete operation. Turn on iCloud Keychain in settings then try again" message when I try to turn on activity notifications in iPhone.

Do I need to downgrade the plug-in to 9.24 to overcome these issues?

**Comment by adavison007** [comment]
@dgreif "interesting find for you.... So mac homekit app always does 10 seconds... on wifi and local network, makes sense... iOS Homekit app always does 60 seconds refresh even when on the local wifi network... HOWEVER... if your home hubs are off (I discovered when moving them around) the iOS app does it every 10 seconds..... so is there a way of you tuning the code, or even having an option in the settings that makes it always 10 seconds?

**Comment by dgreif** [comment]
That's an interesting find @adavison007, but unfortunately that is still outside the control of the plugin or homebridge. Only apple can dictate how often HomeKit makes the requests

**Comment by adavison007** [comment]
Thanks for the feedback

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 14 Jun 2022, at 17:22, Dusty Greif ***@***.***> wrote:


That's an interesting find @adavison007 <https://github.com/adavison007>, but unfortunately that is still outside the control of the plugin or homebridge. Only apple can dictate how often HomeKit makes the requests

**Comment by cmb991** [comment]
I'm seeing the same issue,  Failed to reach Ring server at https://app-snaps.ring.com/snapshots/next/123xyz.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds.

**Comment by cmb991** [comment]
![Screen Shot 2022-07-09 at 8 12 15 PM](https://user-images.githubusercontent.com/30929454/178126562-927f5b28-8345-4fec-b4d8-68b458efb18f.png)
Even if I try to manually navigate to the link its trying to pull the snapshot from (and yes I'm logged into ring.com via web).

**Comment by cmb991** [comment]
![Screen Shot 2022-07-09 at 8 14 20 PM](https://user-images.githubusercontent.com/30929454/178126601-17d0b30f-d414-4ed2-8aba-0481b5f406e0.png)
Also seeing it says it will try again in 5 seconds, but it just keeps trying over and over spamming the same link.  Could this cause some type on 'timeout' or 'temp ip ban' causing it not to load?

**Comment by dgreif** [comment]
@cmb991 can you try v11.0.7?  I updated the logging to hide these errors for snapshots.

**Comment by adavison007** [comment]
UPDATE! 

Since updating to ios 15.5 yesterday (including Apple TV) the snapshots in homekit now update immediately :) Error messages have gone…. the mac home kit app refreshes every 10 seconds and the iphone refreshes every 60 seconds. I guess the iphone is 60 seconds re battery life??

This seems normal now.

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 16 May 2022, at 12:40, Adam Davison ***@***.***> wrote:

So, my Ring Homebridge cameras randomly update… they used to always refresh every 10 seconds… but since the last 12 IOS updates they do not update… 

The only error message I currently have is 

"Failed to reach Ring server at https://app-snaps.ring.com/snapshots/next/12323721 <https://app-snaps.ring.com/snapshots/next/12323721>.  Timeout awaiting 'request' for 20000ms.  Trying again in 5 seconds…”

This happens with and without rich notifications turned on.


Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 16 May 2022, at 12:24, soulcook ***@***.*** ***@***.***>> wrote:


Yes, this is almost identical to my experience, except that the Ring
doorbells do usually acquire a snapshot eventually without opening a
livestream if you wait long enough.

FWIW my Nest doorbell also refreshes only every 60s in the Home app. All
the direct IP cameras refresh every 10s.

**Comment by adavison007** [comment]
Thanks, I have now turned on the rich notifications for all cameras and now I get the same error again on about50% of the cameras. When I turn off rich notifications the error goes.

Adam Davison
***@***.*** ***@***.***>
01276 63145
07748 761448

On 11 May 2022, at 15:39, Dusty Greif ***@***.***> wrote:


v11 leverages the images from rich notifications, so you will want to turn them on for all of your cameras

**Comment by dgreif** [comment]
@soulcook I'm not sure there is anything else to be done. The ffmpeg and nest camera plugins are able to fetch snapshots using a different protocol. The Ring api and round-trip-time for fetching snapshots are the real issue, and there isn't anything we can do to improve those.

**Comment by soulcook** [comment]
Hi. Thanks for the response.

Something here doesn’t add up.

- If I open the Ring app, I get a snapshot *immediately* (presumably using
the same Ring remote API)

- If I open the Home app on a Mac, I get a snapshot *immediately* – via
your plug-in, so definitely using the same API

- if I leave the Mac Home app open, I get a snapshot *immediately* on the
mobile Home app

- If I close the Mac Home app, I continue to get snapshots immediately on
the mobile app for a few minutes.

- But after that, snapshots on the mobile Home app take anything from a few
minutes to several *days* to appear. See attached screenshot. The cameras
labelled “Gate” and “Side Door” are both Ring cameras.

So it can’t be the Ring API being slow to respond, because it *isn’t* slow
to respond when I access it via Homebridge Ring from a Mac.

And it can’t be a bug in HomeKit or Homebridge, because the problem doesn’t
occur with other camera plugins.

It *must* be a bug in your Ring plug-in.

Is there a fault in my reasoning?

Happy to do whatever I can to help diagnose this.

**Comment by soulcook** [comment]
Sorry, here’s the screenshot.

**Comment by dgreif** [comment]
@soulcook please see https://github.com/dgreif/ring/wiki/Snapshot-Limitations, which explains why the plugin exhibit the behavior you are seeing. It comes down to snapshot caching and not _waiting_ for a snapshot if one isn't cached. The Ring app shows a snapshot "instantly" because it requests it and shows it as soon as it's ready. With homebridge, we can't _wait_ for the snapshot because waiting blocks the entire bridge. Instead we kick off the request and cache the image, but there is no way to tell HomeKit that a snapshot is now ready. Instead we have to wait for the next request, which can be 10s - 60s depending on your current connection (LTE, wifi, etc)

**Comment by soulcook** [comment]
Thanks Dusty.

I do understand what you're saying. But it still doesn't quite make
sense... because how come the snapshot functionality always works perfectly
on the Mac Home app, and it works perfectly on the mobile app when the Mac
Home app is open, but it doesn't work on the mobile Home app when the Mac
Home app isn't open?

If it were just a question of waiting 10-60s or so for the next request
from the app once the snapshot has been cached, that wouldn't be too much
of a problem. But that's not what's happening. It can take hours for a
snapshot to arrive, and sometimes it never arrives. See the screenshot in
my last message showing one of the cameras showing no snapshot refresh for
two days. I honestly think something is broken in the communication between
the mobile Home app and the plugin code in HomeBridge.

I also have to wonder how it is that homebridge-nest-cam manages to provide
snapshots reliably. Nest servers aren't any quicker at responding to
snapshot requests than Ring servers are – in fact they generally seem to be
slower. But the Nest snapshots always appear in the Home app within a few
seconds.

It's been a while since I've done any Homebridge coding, but I'm sure I
remember there being a pushEvent method that allows you to send data to the
client asynchronously rather than relying on a blocking request.

Sorry to go on about this, but there's definitely something wrong here.

Paul

**Comment by soulcook** [comment]
I’ve just upgraded to iOS16 and… the problem has vanished!

Hooray!

**Comment by Kaiserben** [comment]
I have an issue with Snapshots as well after a complete reinstallation of my Homebridge setup.

[16/12/2022 22:00:51] [Ring] No snapshot cached for Portail
[16/12/2022 22:00:56] [Ring] Failed to cache snapshot for Portail (15.005s), The camera currently reports that it is online
[16/12/2022 22:00:56] [Ring] Snapshot for Portail (lpd_v2 - Doorbell Pro) failed to refresh after 15 seconds

The livestream is working well, only the snapshots are not loading. I tried to clear the cached accessories, reboot the doorbell, reboot the hub, reboot home bridge without any success.

My config :
- Raspberry pi 2
- Raspbian 11
- Homebridge 1.6.0
- NodeJS v18.12.1
- Homebridge Ring 11.7

```
{
    "bridge": {
        "name": "Homebridge 39D3",
        "username": "***",
        "port": 51425,
        "pin": "***,
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "****",
            "hideCameraLight": true,
            "hideCameraMotionSensor": false,
            "hideInHomeDoorbellSwitch": true,
            "debug": true,
            "platform": "Ring"
        }
    ]
```
