### ISSUE TITLE
Unable to take Snapshots whilst Streaming - Can Streaming be Disabled?

### ISSUE THREAD

**Issue by ed0906** [dgreif/ring#973]
# Bug Report

### Describe the Bug

Apologies if this is the wrong place to submit this, I couldn't see a suitable alternative.
I am trying to generate a time lapse and have no need for motion streams/events, I just want a regular snapshot every 10 or so minutes. The trouble is, if the camera detects motion, it appears to block my ability to take snapshots during that detection period. 

Given I am trying to build a time lapse of a construction project, it's quite likely that the camera will constantly be detecting motion.
If possible I'd like to **disable motion detection** to conserve battery, but **retain** the ability to request snapshots. Is this possible?

Note: **I am aware the limitations of Snapshots for ring cameras**, especially battery cams as documented in the [wiki](https://github.com/dgreif/ring/wiki/Snapshot-Limitations). 
However I didn't see any docs around work arounds. I suspect either because there either isn't one, or because this is an odd use-case and most people actually want to keep the motion streams.

Any suggestions for routes I could take?

### To Reproduce
Steps to reproduce the behaviour:
 - Use the ring-client-api to request a snapshot whilst the camera has detected motion
 - Observe an error is thrown: `Snapshot for TimelapseCam (stickup_cam_v4 - Spotlight Cam) failed to refresh after 15 seconds.  This is normal behavior since this camera is unable to capture snapshots while streaming`

### Expected behaviour

A work around with the ability to disable streaming, but retain snapshot functionality

### Additional context

Using:
- Ring Client API
- NodeJS
- Spotlight Cam Battery

### Environment

 - ring-client-api: 11.0.1

**Comment by dgreif** [comment]
Unfortunately all of these restrictions come from Ring, so the `ring-client-api` can't do anything to get around the "snapshot while streaming" issue.  It's also unfortunate that Ring prevents snapshots entirely if you disable motion detection.  If you really don't care about recording at all, I think your best bet is to adjust your motion settings so that they are _very_ insensitive and then restrict the motion detection zone to some tiny section of the camera view that hopefully receives little motion.  Sorry I can't do more, Ring has some of this stuff built in an interesting way 😅.  Pretty sure it's all trade-offs to avoid battery drain.

Speaking of battery drain, the other alternative is to plug in the camera.  If you run a battery cam in "wired mode", it _is_ able to capture snapshots while recording.  Since it's a build site I'm guessing power may not be available, but if it is that's an option 😄

**Comment by ed0906** [comment]
Great suggestions, thank-you for getting back to me :)
