### ISSUE TITLE
Live Stream

### ISSUE THREAD

**Issue by RoyHobbs99** [dgreif/ring#99]
Hello, I just installed HOOBS and installed your Ring plug-in. Snapshots are working but live streams never start. 
In the logs I see preparing livestream and then waiting for livestream and finally stopped livestream. 
In the home app it says No Response the Camera is not responding. 
Both HOOBS and the plugin are on the latest versions. 
Any ideas?

**Comment by dgreif** [comment]
It's most likely a network issue where the plugin is unable to open ports on your router.  Check your router settings to see if you can turn on UPnP or NAT-PMP.  https://github.com/dgreif/ring/wiki/Camera-Troubleshooting#check-your-logs-in-homebridge

**Comment by RoyHobbs99** [comment]
Thanks, I’ll give that a look.

**Comment by RoyHobbs99** [comment]
UPnP is already enabled on my router

**Comment by dgreif** [comment]
Ok, I'm not sure what would be preventing the data from getting in then.  Were live streams working previously?

**Comment by RoyHobbs99** [comment]
Live-streams have never worked. I installed hoobs and the plugin yesterday. Snapshots work as intended

**Comment by RoyHobbs99** [comment]
I tried everything listed in the link you sent, including removing the camera and reading to Home. Livestream still isn’t working and now the home alerts have stopped for the Ring. Ugh, I give up!

**Comment by dgreif** [comment]
@RoyHobbs99 I'm really sorry you are still struggling with live streams.  NAT traversal is a complex issue and it is hard to write code that works in all situations.  Unfortunately I don't think there is anything I can do to help you at this point since I don't have a way to reproduce your issues.  If you are able to write code and debug the problem yourself, I would love to take a PR if you find a way to fix the issue for your network.  Otherwise...I'm afraid you will have to wait for official HomeKit support from Ring.

Just for reference, could you provide the model of the router you are using?

**Comment by RoyHobbs99** [comment]
No worries, I appreciate the work you do on the plugin and at least I have snapshots. I have the Netgear Orbi.

**Comment by ansuz07** [comment]
@RoyHobbs99 I was having a similar issue to yours and I managed to fix the issue on my end.  It turns out it was an IPV6 issue - for some reason, the Ring API has issues resolving live streams when IPV6 is used rather than IPV6 - disabling the IPV6 DHCP server (and only using IPV4) on the network fixed it for me.

Worth a try on your end.
